### ISSUE TITLE
Change ACCOUNT_ENABLED user tag to ACCOUNT_RESTRICTED

### ISSUE THREAD

**Issue by adamalton** [web3-storage/web3.storage#1002]
This is a proposal to change the `ACCOUNT_ENABLED` user tag that was added in #984 to be called `ACCOUNT_RESTRICTED` instead (and to invert its behaviour).

This came up when we (Potato) were discussing the implementation of #988, which in brief, will allow the disabling of some (but not all) of a user's account functionality.

The reason for changing `ACCOUNT_ENABLED` to `ACCOUNT_RESTRICTED` is two-fold:

1. The requirements of #988 are to restrict _some_, but not all, of a user's account functionality, so rather than being a binary on/off enabled/disabled thing, it's actually just putting a set of restrictions on the account. So "restricted" seems to make more sense than "enabled/disabled".
2. You would usually expect a user's account to be enabled/unrestricted by default (i.e. if a user creates a new account, you would expect its initial state to be unrestricted, rather than starting as restricted and requiring a flag to derestrict it). So it seems to make more sense that the tag in the `user_tags` table is for the _restriction_ rather than the lack of restriction.
    - Obviously we can choose what the behaviour is when this tag doesn't exist for a user, so it could be done either way round, but it just feels a bit more intuitive to do it this way round.

@vasco-santos @jsdevel @JeffLowe any objections to us making this change?

**Comment by adamalton** [comment]
> i don't like the idea of having boolean values with differing suffixes

I can see that having the data type implied by the suffix makes sense, but I don't think that that means that boolean values must all end in `_ENABLED`. Otherwise, how would we deal with things such as (hypothetically):

* `IS_BANNED`
* `HAS_EXCEEDED_STORAGE_LIMIT`
* `HAS_EVER_LOGGED_IN`

I think that enforcing a rule that every boolean tag must have a name ending in `_ENABLED` would likely force us into some very weird naming.

I agree with everything else you say though - we have to check the tag's value, not just its existence; and that check will likely be wrapped in a helper function. That's exactly what I've sketched up in this [pseudo code for proposed use case](https://github.com/web3-storage/web3.storage/issues/988#issuecomment-1043140263).

**Comment by vasco-santos** [comment]
> I think that enforcing a rule that every boolean tag must have a name ending in _ENABLED would likely force us into some very weird naming.

Yeah, I agree. Thanks for calling it out. I like to have the suffix specially when we are handling units like "BYTES".  Because is a number/bigint, but having a clear name on what that number represent helps a lot on code readability.

In the boolean situation, while it is nice to know for the name that it is a boolean, it is not so important, because you can always look into tag_type row. But with number, you might need to consider type and unit.

> you would expect its initial state to be unrestricted, rather than starting as restricted and requiring a flag to derestrict it).

Yes, I agree with this! Probably in terms of naming using `HAS_*` is the more versatile for boolean. And we can read it and infer immediately that the value behind the tag is a boolean. I think it is fine to not restrict to suffix only, but to have a prefix or suffix that clear shows what tag has:

- `HAS_ACCOUNT_RESTRICTED`
- `HAS_PSA_ACCESSS`

The most important is to name it in a way that is clear what it is, and that we don't need to fill it in previously, like the motivation behind this issue 👍🏼

**Comment by adamalton** [comment]
Ok, great.

@vasco-santos how do you feel about using `ACCOUNT_IS_RESTRICTED` (just reads slightly nicer), or would you rather stick with `HAS_ACCOUNT_RESTRICTED`?

**Comment by trigramdev9** [comment]
`HAS_ACCOUNT_RESTRICTION` would read better from a pure english perspective.

**Comment by trigramdev9** [comment]
`HAS_ACCOUNT_RESTRICTION` is somewhat too general though.   The motivation behind this right now is to support blocking a user.  Blocking a user right now means they can only login and READ their data.  I could see other account restrictions in the future.  Perhaps future restrictions will be along the lines of `HAS_ACCOUNT_TOKEN_CREATION_RESTRICTION`?

**Comment by trigramdev9** [comment]
@vasco-santos @adamalton so now that we're going down the lines of having the data type in the name, does it make sense for `_BYTES` to be a suffix and `HAS_` to be a prefix?

**Comment by adamalton** [comment]
I definitely agree it makes sense for `_BYTES` to be a suffix and `HAS_` to be a prefix. (But I don't think that we necessarily need to restrict ourselves to a particular rule; I think that making the names clear and meaningful should be primary thing that guides us.)
