### ISSUE TITLE
Error with ReactJS.

### ISSUE THREAD

**Issue by priyansuhub** [web3-storage/web3.storage#1013]
Followed the docs.
npm install web3.storage

Now // import Web3Storage from "web3.storage";
this err message shows up
Can't resolve 'ipfs-car/blockstore/memory'
I have seen this issue earlier here itself but how to solve it?

**Comment by dchoi27** [comment]
This should resolve your issue: https://github.com/web3-storage/web3.storage/issues/304#issuecomment-894172209
