### ISSUE TITLE
Refactor type name of db primary key

### ISSUE THREAD

**Issue by GaryHomewood** [web3-storage/web3.storage#1031]
The Fauna DB had `_id` as the primary key type name for tables.

The Postgres DB has `id` as the primary key column name. The `_id` type naming was left in place when the DB was migrated. We should refactor this and use `id` consistently throughout the DB package. These primary key ids should not be exposed in the API so the refactor should not break any API contract.

**Comment by mbommerez** [comment]
This is now obsolete. Closing ticket.
CC @flea89
