### ISSUE TITLE
Docs - Generalize answer in docs troubleshooting for any import error to use prebuilt module

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1048]
Right now, in https://docs.web3.storage/how-tos/troubleshooting#i-need-to-use-webpack-4
we recommend folks use the prebuilt module for Webpack 4

However, it's a generally good solution for import errors (most common one that comes up is `Can't resolve 'ipfs-car/blockstore/memory'`). We should change the question title to:
"I'm getting import errors when importing the Javascript client library"
And response to say: Some common situations where this might happen include:
- Using Webpack 4 (e.g., for create-react-app)
- Getting an error like `Can't resolve 'ipfs-car/blockstore/memory'`
- (would be good to do 10 min of research through old issues and the community channel to see what other situations this pops up in)

@mbommerez - @yusefnapora is pretty overloaded this and next week, mind if we get this in your queue?

**Comment by mbommerez** [comment]
Thanks @dchoi27 . Yea we can take that one 👍
