### ISSUE TITLE
Add rate limits to client libs

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1050]
We currently use `p-retry` for the client to handle rate limits from the HTTP API, which exponentially backs off when it gets a rate limit error from the API. Because we know our rate limits, though, we should just incorporate rate limiting into the client, which will be faster than retrying.

Let's add to JS for sure, and go if it's easy.

**Comment by lyz52789** [comment]
Is there a parameter that needs to be set to solve this problem?

**Comment by mbommerez** [comment]
Linked to a sister issue in NFT:
https://github.com/nftstorage/nft.storage/issues/1509
and PR: https://github.com/nftstorage/nft.storage/pull/1647
