### ISSUE TITLE
Docs troubleshooting note on updating to latest client if facing upload speed issues

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1052]
We need to add a note to the Troubleshooting section in the docs:
https://docs.web3.storage/how-tos/troubleshooting

> **I am experiencing slowness in uploads to web3.storage.**
> 
> Please make sure that you are using the latest version of web3.storage client: 3.5.6. There is an issue in the latest Node version (https://github.com/nodejs/node/pull/42117) and we reverted using native version of Blob in latest release until that fix is shipped.

---

Background info from Discord
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/db7e270d-7dfc-4dfd-9bf1-5e1815725240)

**Comment by mbommerez** [comment]
This needs to be redone in the main repo as the docs have now moved there from their separate repo.
@GaryHomewood have moved it back into the Sprint backlog.

@dchoi27 for your information - this hadn't been merged yet into the old docs. We will redo and then just get it merged without review from Yusef. Let us know if any objections.
