### ISSUE TITLE
Block web UI token generation for users with account restriction

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1056]
<img src="https://images.zenhubusercontent.com/619bc03a70247ff083158a94/a0e438b3-fac2-4f09-b358-8b1203bc275e" width="350">

<img src="https://images.zenhubusercontent.com/619bc03a70247ff083158a94/de5d6b04-b562-4ec1-85b9-617ed220e59d" width="350">

<img src="https://images.zenhubusercontent.com/619bc03a70247ff083158a94/fc471a36-71a2-408c-beed-f63ebb374b72" height="350">

**Comment by flea89** [comment]
@mbommerez Are we clear this is not required anymore?
If yes shall we close?

**Comment by mbommerez** [comment]
Yes, we can close this, as we won't be removing token management for restricted users.

For reference:

> Users who have exceeded their storage limit:
> Should they be able to delete uploads? YES
> Should they be able to unpin files that they have pinned through PSA? YES
> Should they be able to generate tokens? YES
>
> When a user’s account is restricted, this is probably because they’ve uploaded too much stuff, so we want to allow them to delete/unpin files. So for that reason, we should still allow their API tokens to work when their account is restricted. It may be the case that one of their API tokens has been leaked (possibly the cause of them going over quota), or may become leaked while their account is restricted. So we should still allow users to delete and create API tokens while their account is restricted; we should only restrict what they can do with those tokens (i.e. prevent them from uploading new files).
> 
> Similarly, we should still allow the user to delete/unpin files through the web API while their account is restricted.
> 
> On a sidenote - for accounts which are permanently banned (due to variety of reasons), it will be different. That is more likely to be a complete lockdown of the account.
