### ISSUE TITLE
Permanently banning users from W3s

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1067]
There may be a need to ban in a user in the near future
([tracked here for nft/admin.storage](https://github.com/nftstorage/admin.storage/issues/19)).

This came up when discussing account restrictions (due to exceeding storage limit or other reasons), which will:
* allow the user to log in to web3.storage
* allow the restrictions to be lifted
* not allow any upload whatsoever

However an outright ban (for graver reasons) would
* ban the user from even logging in
* other potential actions (remove files from backups etc?)

**Comment by dchoi27** [comment]
This is fully landed in admin.storage, right @JeffLowe ?

**Comment by mbommerez** [comment]
I think that is based on API tokens though. So maybe does not cover blacklisting user accounts outright?
(And other potential actions).

I added this ticket as this was brought up in a Slack thread on types of account restriction and Alan mentioned the two different levels (restriction vs permanent ban). Happy to remove if you consider it done.

**Comment by JeffLowe** [comment]
No.  Banning is not currently being worked on (reflected here in backlogged feature in nft https://github.com/nftstorage/admin.storage/issues/19).  It was triaged and prioritized as low and placed in backlog. 

Blocking a user is being implemented now in nft.storage (see https://github.com/nftstorage/admin.storage/issues/12 and https://github.com/nftstorage/nft.storage/issues/1383 for full featureset).  Blocking user will still allow user to login to client and have access to their uploaded files.

**Comment by dchoi27** [comment]
got it - thanks!

**Comment by dchoi27** [comment]
Sorry I got wires crossed between blocking a user and banning
