### ISSUE TITLE
Resubmit pins for status syncing

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#1084]
We need to resubmit pins for status syncing what have status != `Pinned` from https://github.com/web3-storage/web3.storage/commit/5ae212da21692da2fe9d08a53463b15875ec0cd7 to https://github.com/web3-storage/web3.storage/pull/1083

**Comment by vasco-santos** [comment]
This explains why https://github.com/web3-storage/repin-unpinned-cids never ended. I will resume it today and it should clean this up

**Comment by vasco-santos** [comment]
Job is now running again

**Comment by alanshaw** [comment]
This was done last week, 11m pins added to the queue, 86k still to process.
