### ISSUE TITLE
Add alert / metrics for Pin Reports

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1092]
Alert for dropoffs in updating pin status would tell us if something is wrong with the pin status updating - we'd still need to do digging into why, but could be a great catch-all since we rely on pin status so much today.

Should have metrics / alerts instrumented for rate (per second?) and within an interval window (within an hour).

**Comment by fabiolrodriguez** [comment]
Alerts instrumented for both environments on issue https://github.com/nftstorage/nft.storage/issues/1763
