### ISSUE TITLE
Include pin requests in Uploads in Grafana dashboard

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1100]
In NFT.Storage, we count uploads with `type='remote'` in the Grafana (since it's in the `upload` table anyway), but in Web3.Storage, we keep track of PSA pin requests in a separate table (and not in `upload`). We should include this data in some form. 

My understanding is that, to be consistent, we'd include everything in `psa_pin_request` (though someone should double check this - for instance, I'm not sure if in NFT.Storage, we only show an upload with `type='remote'` if we can grab the first block whereas potentially in Web3.Storage we show all requests in `psa_pin_request` whether or not we were ever able to find the content). But let's do whatever filtering, etc. makes sense + is consistent.

**Comment by flea89** [comment]
@dchoi27 
I can see `web3storage_pin_requests_total`, to be exposed in the metrics API endpoint.
Can you confirm it's what you expect?

From a quick look, the way Uploads and PinRequests are counted is consistent.
`pin_requests_total`
`uploads_total`
`uploads_total{type="${type}"}`
represent the total number of requests to upload/psa_pin_requests, whether they ended up being successful or not.

**Comment by mbommerez** [comment]
@dchoi27 Are you okay to close this out?

**Comment by dchoi27** [comment]
Sorry! Yes can close this out
