### ISSUE TITLE
Modify hover-over for "Storage Providers" and "Queuing" in Files page

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1114]
Sister issue to: https://github.com/nftstorage/nft.storage/issues/1650

**Comment by dchoi27** [comment]
@orvn FYI - would be great to get this in soon!

**Comment by orvn** [comment]
@dchoi27, updated in #1151. Feel free to check the build preview and merge into `main`.

**Comment by orvn** [comment]
Resolved in #1151
