### ISSUE TITLE
Backup for production DB

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#112]
We should take periodic backups of the production DB.

https://medium.com/@wallslide/automating-faunadb-backups-6f620727eedc

Acceptance Criteria:
- [ ] A copy of the db is created weekly
- [ ] Copy is secured
- [ ] Process is automated
- [ ] Backup restoration is tested once
- [ ] Procedure is documented

**Comment by olizilla** [comment]
Ruh roh

> Fauna Data Manager - This project is no longer in development and is not supported by Fauna.
– https://docs.fauna.com/fauna/v4/integrations/fdm/index.html

> Fauna does not currently offer a backup and restore solution.
– https://docs.fauna.com/fauna/current/api/best_practices?lang=javascript#backup
