### ISSUE TITLE
usdz file upload should not automatically convert to zip.

### ISSUE THREAD

**Issue by yosun** [web3-storage/web3.storage#1122]
Bug: usdz file upload should not automatically convert to zip.

Here is our test usdz file - open it on Safari on your iOS device for the native AR viewer to load: https://raw.githubusercontent.com/yosun/Photogrammetry_wiki/main/output-corgi2-low.usdz

When this file is uploaded via API to web3.storage store endpoint apparently it gets converted to a zip (which no longer enables usdz features): 
https://bafybeigsfckyoz2kywo2wgaasjjga2lid3qhed7qmvprb4geg4rilnxi2a.ipfs.dweb.link/

**Comment by dchoi27** [comment]
@alanshaw any thoughts? it looks like Usdz is a .zip file, so I'm guessing it's not a Web3.Storage thing, but how the gateway is returning things to the browser.

**Comment by vasco-santos** [comment]
@yosun did you try do resolve them outside the browser? I downloaded locally with curl specifying file name and extension, and looks like it worked.

So, I suspect this is something related to browser
