### ISSUE TITLE
Small account page snags in new UI

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#1127]
<img width="1094" alt="Screenshot 2022-03-18 at 11 50 27" src="https://user-images.githubusercontent.com/152863/158998316-e8e8e3d1-e12f-4018-8aa0-b2d98e66f049.png">

**Comment by alanshaw** [comment]
Not sure, it was an existing file i had. looks like it just has a long name with no space

**Comment by orvn** [comment]
> So weird, didn't see this in QA. Thanks so much for catching.

It's because it's a really large non-breaking file name (no spaces or dashes). Just a CSS fix.
