### ISSUE TITLE
Files pagination issues

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#1147]
Please see the screen recording: https://bafybeibe2wngdxvrvrusyzsuw5g752phepqsiwtjrlebisw7vldfjvqzpe.ipfs.dweb.link/Screen%20Recording%202022-03-21%20at%2010.38.42.mov

**Comment by alanshaw** [comment]
@orvn we need to optimise the DB query but in the mean time the UX for when a user has 1000+ items is not good, unusable. It takes a long time to request the data and then I cannot effectively paginate through it.

The site needs to request just the items for the page the user is viewing.

**Comment by mbommerez** [comment]
@orvn We have discussed this with @alanshaw and will take on this ticket to find a solution.

**Comment by mbommerez** [comment]
Closing this ticket in favour of:
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1362
