### ISSUE TITLE
Storage limit - Add MailChimp email service

### ISSUE THREAD

**Issue by adamalton** [web3-storage/web3.storage#1153]
### Overarching user needs / context:
* Users need to receive warning emails from support@web3.storage about their storage quota with specific messages and some dynamically generated data on how much they are using and what their current quota is.
* Admins (support@web3.storage) need to receive an email when a user has gone over their allowed storage quota.

### Scope of this ticket:
This is a subtask of #990. We want to take the `EmailService` class that's been stubbed out in that ticket and make it actually connect to MailChimp and send the emails.

* We'll use the _templated_ transactional emails, so that we can use the visual template editor in MailChimp and therefore don't have to deal with the nightmare of trying to create HTML emails that will work across different email clients; instead our API calls are just `"Send 'template_x' to 'user@example.com' with variables { ... }"`.
* We'll make this as a mini sub-package inside the "cron" package, but it will be entirely generic, so could be shifted out to somewhere else to make it reusable by the other packages.
* Calls to send emails will go through the `EmailSerivce` class, and MailChimp will be plugged in behind this, so in future we could switch to a different email sending provider without changing any of the rest of the application code.

### Acceptance criteria:
- [ ] Once we run this service (on-demand), it needs to take all users returned by the checks and send them the appropriate email with the correct details on their storage usage and how to request an increase.

**Comment by adamalton** [comment]
## Revised architecture

As we've built more of the storage limit and account restriction features, it's become apparent that there are several different cases where we want to send emails. So far:
* To a user when they reach a certain threshold of storage usage.
* To a user when their account is restricted (or de-restricted).
* To admins notifying them of users who are reaching/exceeding their storage limits.

And there will probably end up being more cases in the future for different features in the application.

This means that these emails are not just being triggered from inside the `cron` package, but from other places too (currently the `db` package). This means that:

* This `EmailService` should probably move out of `packages/cron`, probably into its own `packages/email`.
* There will emerge a circular dependency between the `db` package and the `email` package. (The `email` package relies on `db` to store a record of which emails have been sent, and `db` relies on `email` to send emails when certain user tags are updated.) Ideally we want to avoid that circular dependency.

So as well as moving the `EmailService` into a new `packages/email`, I propose that we also:

* Create some kind of "signals" or "events" which one package can publish and another package can listen to.
* The `db` package can publish a "user tag updated" event, which the `email` package can listen to to trigger the appropriate emails.
    - This will mean that `email` depends on `db`, but not the other way round.

**Comment by JeffLowe** [comment]
@adamalton To clarify here, no user email notifications are needed as result of User Blocking action on nft and web3.  I double checked with David to confirm this.  So you can remove that from this ticket to keep it entirely scoped to web3 storage limit notifications.

**Comment by mbommerez** [comment]
Hi @JeffLowe What do you mean by the following?
> no user email notifications are needed as result of User Blocking action on nft and web3

Do you mean you already have notifications in place? If yes, what are you using for this? How are they triggered and using what service?
Or does it mean there are no notifications needed to warn people their account is being officially restricted?

Let's sync on this as I feel there is confusion between "blocking" and "account restriction". I wonder if we should update the language to make sure we all have a shared understanding.

**Comment by JeffLowe** [comment]
To clarify:
When an admin user via the admin application blocks a user, there should be no emailed notification to the user that they have been blocked.

**Comment by flea89** [comment]
@adamalton Can this be closed?
cc @mbommerez

**Comment by adamalton** [comment]
Oh yeah, definitely!
