### ISSUE TITLE
New redesigned docs are missing recent content (e.g. pinning)

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1160]
The new https://web3.storage/docs is not displaying the added docs for PSA (pinning services API)

What's missing is:
* new left hand nav item 'Pinning Services API'
https://docs.web3.storage/how-tos/pinning-services-api
* added docs in the nav item 'HTTP API'
https://docs.web3.storage/reference/http-api/

The original PR with all the changes for Pinning docs is here:
https://github.com/web3-storage/docs/pull/224

**Comment by mbommerez** [comment]
@dchoi27 Who should this be assigned to? Feel free to close if I missed an existing ticket on this.

**Comment by orvn** [comment]
> @orvn did you already make a separate issue on this?

No, this issue works!

**Comment by mbommerez** [comment]
Moved this back to 'new issues' pipeline. Not sure we have a reopened column?
@dchoi27 would be great if we could prioritise this as the pinning docs have disappeared over a month ago since the redesign went live.
