### ISSUE TITLE
Link to the content?

### ISSUE THREAD

**Issue by aronchick** [web3-storage/web3.storage#1164]
@dchoi27 edit for clarity: Currently, in the /account page of the website, the user's files table shows the CIDs of the file, but there are no links to actually viewing the content through a gateway.

Can we make the text in either the file name or CID column a link to `ipfs.io/ipfs/{cid}` for the given row?

cc @orvn 

---
Is there a link to my stored content? I feel like i'm missing it :(

**Comment by orvn** [comment]
(Adding this as P1)

**Comment by dchoi27** [comment]
@orvn any updates here? #1175 asking for the same thing
