### ISSUE TITLE
Provide dweb link to saved file with filename search parameter as before

### ISSUE THREAD

**Issue by gyuri-lajos** [web3-storage/web3.storage#1175]
I really appreciate web3.storage it is a dream come true. A true game changer.
The new look is nice.
I did trust that search will be added later. Thanks for that.

![](https://dweb.link/ipfs/bafkreifrfryyi67v2yzr2jfixxbljkhmk3ed6aw6cp6wljlx6igb6btioi?filename=Account%2520-%2520Web3%2520Storage%2520file%2520search.png)

I've been experimenting with integrating  web3.storage client example 
into IndyLab powered Inter Personal Knowledge Graph pilot
and extended it so that it 
get's the link for the uploaded file as a dweb link and displays it,
so that it can be added to documents.

![](https://bafkreib6y2rqx77z3ytsnpfstlcj36ipqsi67bhhzpe2u5t3mvber7re4m.ipfs.dweb.link/?filename=indylab%2520web3storage%2520experiment.png)

Before that I was able to get to the link via the listing, clicking the listed link and get the link for the saved file that way.

The current search interface only gives the CID for the upload, though.

it would be nice for people who do not know, or wish to know about CIDs
to give them  a dweb link to the actual file eventually including the filename as a search parameter as before

except for the files still being processed the search listing  have all the information
needed to provide a dweb link to the uploaded file

like so
https://bafkreib6y2rqx77z3ytsnpfstlcj36ipqsi67bhhzpe2u5t3mvber7re4m.ipfs.dweb.link/?filename=indylab%2520web3storage%2520experiment.png

**Comment by dchoi27** [comment]
Thanks for flagging, tracking this in #1164 so closing this one!
