### ISSUE TITLE
Access to uploaded file takes up to half hour

### ISSUE THREAD

**Issue by johnwwk** [web3-storage/web3.storage#1177]
I have been facing this issue multiple times and currently, we are about to stop using the service because of this. I hope you won't give a generalized answer because the problem is not on our side.
Except for the image files, in most of the cases when I upload a file, accessing that file takes up to half-hour. Until then when I try to access the file, ipfs timeouts. 
I check the file status from the dashboard and I see "PinQueued" and "Queuing...". This happens in json files mostly and other files like bhv.
Please tell me is this how web3-storage works? Is it created for image files or do we have to tell users they should wait up to half-hour after uploading?(!) or does this happen because it's free?

**Comment by dchoi27** [comment]
Hi - our infrastructure was experiencing some issues today. Really sorry about that. A fix has been deployed if you don't mind trying again and letting us know if issues persist.

We're moving to an overhauled upload pipeline and infrastructure in the coming weeks (in the middle of rolling this out - we've been building this for many months!). This should give improved robustness and performance.

**Comment by Chrimle** [comment]
Hi, we recently experienced difficulties downloading files from Web3Storage. It started sometime yesterday out of nowhere, after troubleshooting, I noticed the files **are** available on IPFS, but Web3Storage lists them as "Queuing". Glad to hear this isn't an issue on our end!

However, we still experience these issues. Files have their status stuck on "Queuing", so does "Storage Provider".

**Comment by dchoi27** [comment]
Do the retrieval issues persist? Everything looks good from my end now. For files uploaded during the Mar 30 incident window (https://status.web3.storage/) you might need to reupload.

It can take a bit of time for files to get out of Queuing stage, but that doesn't mean they're not pinned and available. #1046 will give more information on what the statuses actually mean.

**Comment by Chrimle** [comment]
**Hi, the issue has been resolved.** 

Although like you stated, the Web3Storage-webpage does say that it is still 'Queuing' - even for new files.
