### ISSUE TITLE
Multiple links to dashboard page confusing on website menu

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1180]
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/dd63b5f9-1b72-4883-8e05-94f8c9c0fc66)

We have two elements in the Account dropdown that go to the same page - it's a bit confusing. Can we just call it "Dashboard"? Or "Dashboard / Files"?

**Comment by D3AS8A** [comment]
@svvimming replace both "dashboard" and "files" with "Manage Files"
