### ISSUE TITLE
Upgrade ipfs-cluster to v1

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#1184]
Cluster v1 has breaking changes, and significant perf improvements

Before we can use it we need to:

- [x] Deploy a staging v1 cluster. https://github.com/protocol/bifrost-infra/issues/1791
- [x] Update and release the cluster client library https://github.com/nftstorage/ipfs-cluster/pull/40
- [x] Update and release the cluster client librart with support for https://github.com/ipfs/ipfs-cluster/pull/1626 
  - client PR https://github.com/nftstorage/ipfs-cluster/pull/42
- [x] Update web3.storage api with the new client: https://github.com/web3-storage/web3.storage/pull/1227
- [x] Update staging deployment config to use staging v1 cluster.
- [ ] Update pin cron job with new client: https://github.com/web3-storage/web3.storage/pull/1228

From @hsanjuan: Updating web3.storage ipfs-cluster to v1.0.0-rc3 will take approximately 2 hours, but the part where writes are disabled should be short. The suggested deployment steps are:

- [x] Stop cron
- [x] Stop writes to cluster
- [ ] Upgrade cluster
- [x] Deploy web3.storage API with updated cluster client https://github.com/web3-storage/web3.storage/pull/1225
- [ ] Merge cron job https://github.com/web3-storage/web3.storage/pull/1234
- [ ] Enable writes to v1 cluster
- [ ] Restart cron
- [ ] Sit down and wait to see how it goes _(potentially downgrade if we don't like how things look)_

**Comment by olizilla** [comment]
Currently the staging api writes to the prod ipfs-cluster. This was convenient, but to be able to deploy an api change to cluster and test it, we are now going to need a staging cluster that we can update to v1 while leaving prod on v0.x

**Comment by olizilla** [comment]
@thattommyhall is setting up a staging cluster for us https://github.com/protocol/bifrost-infra/issues/1791

**Comment by thattommyhall** [comment]
ETA today!
