### ISSUE TITLE
Add "Add File" button to Files widget

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1186]
Right now, users who are focused on their Files list need to know to go up and click a button in a text-heavy area to upload more files. (i.e. you might be focused at the bottom of the screenshot, but when it comes time to add new files you have to visually exit the files area and know to click on the top area)

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/88f857fa-f9ce-450a-bdde-69cdef4820d4)

Think adding a "+ upload file(s)" button by the search bar should do the trick.

**Comment by orvn** [comment]
@dchoi27 what about 

> **Files**  `Upload more +`

Where `Files` is the heading and `Upload more +` is a smaller link just to the right of it?

**Comment by dchoi27** [comment]
yeah that works! just `Upload +` without the "more" would be my preference
