### ISSUE TITLE
Storage limits - automate the email job

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1193]
Related to #990

We need to automate the cron job that retrieves users who have gone over a certain treshold, and sends them an adapted email.

## Todo
- We need to figure out the best way to test this in staging and then release it to prod.

## Notes
- Setting this up as a manual action might help with testing (run it on staging).

**Comment by adamalton** [comment]
This is part of #1189.

**Comment by mbommerez** [comment]
Closing this ticket as the job has not been reactivated and will likely not be.
