### ISSUE TITLE
car delete fails with 404

### ISSUE THREAD

**Issue by ylempereur** [web3-storage/web3.storage#1202]
If I upload a car file using "POST /car", and then go to the "files" page and try to delete it, it fails with a 404 (the UI just fails, you have to look at the console to realize the API returned 404). This happens for any such car file, you can never delete any of them.

**Comment by vasco-santos** [comment]
Hey @ylempereur 

I sadly could not replicate on my end.

Can you give us more information on the error, like a screenshot? How long does it take from upload end to attempt to delete?

**Comment by ylempereur** [comment]
Here is an example of how I upload my car files (token redacted):

`curl -X POST -H "Authorization: Bearer <token>" -H "Content-Type: application/car" -H "X-NAME: dc.car" --data-binary @dc.car "https://api.web3.storage/car"`

The file appears on the Files page and eventually gets pinned and gets some providers.

Later on (days, weeks), after I upload a new version, I try to delete it using the Files page (tried to delete 1, tried to delete multiples, tried 3 different browsers), and the UI freezes after the confirmation dialog. Here is what appears on the console within 1 second:

<img width="557" alt="Screen Shot 2022-04-04 at 9 10 44 AM" src="https://user-images.githubusercontent.com/1845164/161587664-e0d22ba2-6f52-4c67-aa93-147826e5051d.png">

Please let me know if you need further information.

**Comment by ylempereur** [comment]
hey @vasco-santos 

I just had a thought: my car files use v0 CIDs internally, and your UI uses v1 CIDs, which it uses to call the delete api. Could this mismatch be the reason it fails to find the file to delete?...

**Comment by vasco-santos** [comment]
> 
hey @vasco-santos

> I just had a thought: my car files use v0 CIDs internally, and your UI uses v1 CIDs, which it uses to call the delete api. Could this mismatch be the reason it fails to find the file to delete?...

Thanks for the notes, it looks like it is!

**Comment by vasco-santos** [comment]
I created #1242 to fix that

**Comment by ylempereur** [comment]
Thank you. Please let me know when the fix is live.

**Comment by vasco-santos** [comment]
Hey @ylempereur 

Apologies for taking so long to get back to this, a solution was not deployed to use the CIDv0 and deletes should now be functional. Can you please confirm on your end?

**Comment by ylempereur** [comment]
@vasco-santos 

I can confirm that the problem has been fixed and that delete now works as expected.

Thank you for addressing this :)
