### ISSUE TITLE
Improve cron job testing for storage quota check

### ISSUE THREAD

**Issue by GaryHomewood** [web3-storage/web3.storage#1203]
The tests we currently have for the storage quota emailing are checking`stderr`.

We should improve this to test the actual data and function calls.

**Comment by mbommerez** [comment]
@flea89 I spoke with @GaryHomewood on this one and he wasn't sure this is still needed. 

Apparently all is good for the Storage CRON job as we are checking inputs & outputs and also he implemented SINON.JS testing at your recommendation.

Do you think we should be looking at other CRON jobs and improve the testing or we just close this?
