### ISSUE TITLE
Web3 account page - all files checked in Safari

### ISSUE THREAD

**Issue by GaryHomewood** [web3-storage/web3.storage#1214]
Go to https://web3.storage/account/

Safari Version 15.1 (16612.2.9.1.30, 16612)

The checkboxes for marking a file as selected are all checked by default and cannot be unchecked.

![Screenshot 2022-04-05 at 10.46.08.png](https://images.zenhubusercontent.com/6179717ee2ff102416686bc9/c00277a5-65ca-441a-9ac2-74cdf671ff8e)

**Comment by dchoi27** [comment]
cc @orvn
