### ISSUE TITLE
Add GitHub action requiring PR titles to follow https://www.conventionalcommits.org

### ISSUE THREAD

**Issue by gobengo** [web3-storage/web3.storage#1222]
Motivation:
* @alanshaw asked me to https://github.com/web3-storage/web3.storage/pull/1132#issuecomment-1088480397

Prior art:
* https://github.com/nftstorage/nft.storage/pull/1699

Parts
* [x] merge w/ approval #1223 
* [ ] verify the candidate solution using #1224

**Comment by yusefnapora** [comment]
Great idea! I often forget to do this, so it will be nice to have a robotic reminder.
