### ISSUE TITLE
H1 and H2 margins off in API docs

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1250]
The margins are off for the headers:
H1 is glued to the previous div
H2 has too much top margin

![image.png](https://images.zenhubusercontent.com/619bc03a70247ff083158a94/53ec5dee-fbea-408d-9f5f-b1e09cd0956d)

**Comment by orvn** [comment]
This was an issue that was resolved in shipping the new docs (#1138)
