### ISSUE TITLE
decode buffer response

### ISSUE THREAD

**Issue by dattp** [web3-storage/web3.storage#1262]
I want to fetch all files of a CID, code below

```
  const res = await client.get(cid);
  for await (const chunk of res.body) {
          console.log(chunk)
  }

```
but, i don't **decode** the chunk to `string` or `utf-8`... 
I want to read data to handle business logic.
thanks,

**Comment by alanshaw** [comment]
Hopefully this helps:

```js
const res = await client.get(cid)
const files = await res.files()
for (const file of files) {
  console.log(`${file.cid} ${file.name} ${file.size}`)
}
```

https://web3.storage/docs/reference/js-client-library#retrieve-files

**Comment by dattp** [comment]
> 

i try it, but when i get to a `cid` have big files (about 10k), i receive `throw new Error('Unexpected end of data');`
so, i want to stream each file to handle.
