### ISSUE TITLE
Complete the user blocking feature 

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1266]
Upon review of Web3 website on 4.20.22, certain parts of the user blocking feature were not operational.  
The following needs to be completed on the Web3.storage site to complete the user blocking feature. 

- [x] display UI message upon blocked user login
SPEC:  LOGIN UI- upon login to web UI, blocked user gets a message explaining their account was blocked, and to reach out to support@ if they haven't already reached out).  Email in copy should be to support@web3.storage

Observation:  Does not display UI message upon blocked user login*

Example of NFT.Storage UI message
![uponLoginwhenBlocked.png](https://images.zenhubusercontent.com/5285300029fe34596000054e/f04e214e-3afa-4a6f-ab06-c84ff217eaac)

- [x] When user is blocked, deactivate "new api" key, preventing users from creating new keys (buttons found on https://web3.storage/tokens/ and on https://web3.storage/account/).  Note, there is also a nav option to create new token which leads to this route https://web3.storage/tokens/ that needs to be handled. 
SPEC:  API KEY - blocked user unable to create any new api key. The "+ New Key" button is greyed out and deactivated.

Observation:  Blocked user able to create new api key (button needs deactivating with UI tooltip)

- [x] Add tooltip to blocked user's new api key button https://web3.storage/tokens/
SPEC:  API KEY UI - Blocked user gets ui message in new api key button tooltip or click action explaining.  

Observation (same as above):  Blocked user able to create new api key (button needs deactivating with UI tooltip)

Example of UI message and button in NFT.Storage
![NewKeyAttemptWhenBlocked.png](https://images.zenhubusercontent.com/5285300029fe34596000054e/85be25b6-b928-482a-908a-5226416c30af)

- [x] For blocked users, Grey out and deactivate the "Upload" buttons in UI (https://web3.storage/account/ )
- [x] For blocked user, add ui tooltip to upload buttons

SPEC:  UPLOAD UI - Grey out and deactivate the "Upload" buttons in UI on /files and /new-file routes. gets UI feedback in upload file button tooltip and on click action for reason.

Observation: *Blocked user able to initiate an upload. User uploads fail silently in UI, only shows “Failed” in upload modal screen. Console does show error response of “This account is restricted, email support@web3.storage for more information. But upload button need’s to be deactivated

Example of button and tooltip in nft.storage
![UploadAttempWhenBlocked.png](https://images.zenhubusercontent.com/5285300029fe34596000054e/c8c97371-f1d7-4a59-8446-6540491bd1b4)

- [x] ensure Pinning service request buttons (if any exist ) in site are deactivated for blocked user

SPEC:  PSA UI - blocked user unable to request access to the Pinning Service Allowlist, button does not show in UI

Observation:  Could not see any CTA button in UI for requesting Pinning Service Allowlist.  Not sure if I missed where the button was located, if Web3 doesnt need a button, or if a button is needing to be added.

**Comment by JeffLowe** [comment]
@dchoi27 
@orvn

**Comment by orvn** [comment]
Is the requirement for this solution to just visually stop the blocked user from performing certain actions (uploading, creating a token, etc.) on the frontend? 

Or is the ask to stop these action both on the frontend and via the applicable endpoints (and if so, is the latter part tracked in this ticket or a separate one for the API).

**Comment by JeffLowe** [comment]
The deactivation of the user ability to create new api key may be the only one that requires adjustment to endpoint.  If it is needed, that adjustment should be ticketed elsewhere.  
The scope of this ticket is frontend.

**Comment by JeffLowe** [comment]
Links to PRs that address any of the above features will be most helpful for whomever will finish them out.   
I added the note to the description above to clarify that these current features are not currently working in Web3 based on review from April 20.

**Comment by dchoi27** [comment]
Potato has someone who'll spend a few days next week landing this!

**Comment by dchoi27** [comment]
@JeffLowe once @mbommerez shares the right PRs, you all can just do the FE work to land this yourself (no need to wait on Agency Undone)

**Comment by JeffLowe** [comment]
confirmed complete on staging.  awaiting deploy to prod.
