### ISSUE TITLE
How can I upload a file from a URL? 

### ISSUE THREAD

**Issue by nxia416** [web3-storage/web3.storage#1277]
I guess I have to read the file as blob first? Then generate the File objects?

        async function getFilesFromURL(
          url = "https://example/file.jpg"
        ) {
          const blob = await Axios.get(url, {
            responseType: "blob",
          });

          const files = [new File([blob.data], "file.jpg")];
          return files;
        }

However it seems it generates a different file on IPFS...

**Comment by dchoi27** [comment]
Hi, not sure about your script, but depending on how IPFS's is calculating the CID (hashing algorithm used, [CID version](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats), chunking algo, etc.), you might get a different CID when using Web3.Storage vs. a local IPFS node.
