### ISSUE TITLE
Pinning with IPFS Go CLI won't load nor Pin CIDs

### ISSUE THREAD

**Issue by braxxaz** [web3-storage/web3.storage#1279]
Been using the IPFS CLI to pin 117 CIDs I go one by one with this command " ipfs files cp /ipfs/Qmc....... "/Worship" " to add it to the IPFS desktop app but when i run the command in the terminal stays there loading and loading and then wont add it to the list, then I used " ipfs pin remote add --service=web3.storage --name=<Desolation> QmNeMYu...... " but does the same stays there for a very long time and wont pin anything, also  I was able to pin a few that was able to retrieve from the pinata gateway but it wont show up in my web3.storage account. what can I do??
![Screenshot 2022-04-27 063527](https://user-images.githubusercontent.com/88421270/165520045-e173499b-b747-431f-bcd9-badb80aea96d.png)
![Screenshot 2022-04-27 063543](https://user-images.githubusercontent.com/88421270/165520072-679fc900-af7f-4919-88a8-fa0430cde1cb.png)
![Screenshot 2022-04-27 064102](https://user-images.githubusercontent.com/88421270/165520137-ee1b252c-3fad-4473-824f-6d8537f0f653.png)
![Screenshot 2022-04-27 064152](https://user-images.githubusercontent.com/88421270/165520307-302d215f-e6a8-460d-bf22-77080fefe3ca.png)

as shown above everything stays there like loading but nothing happens

**Comment by dchoi27** [comment]
Unfortunately, it's pretty difficult to debug why the Pinning Service API might not work for all files because so much is out of Web3.Storage's control. Are the same files the ones causing trouble with both IPFS Desktop and Web3.Storage? If so, sounds like it's likely an local issue for your IPFS node.

**Comment by olizilla** [comment]
When the `ipfs cp /ipfs/Qm...` commands don't return, it's likely that your local node is strugling to get all the data for the CIDs you are requesting.

The same is true when pinning them to web3.storage takes a long time. It's likely that are nodes are also struggling to find all the data from the network.

Are you hosting those CIDs on an IPFS node you run or some other service? If you know the peerID of a node that is supposed to be hosting the data for those CIDs you can check that they are correctly published using https://check.ipfs.network/

**Comment by vasco-santos** [comment]
Closing this issue for now. @braxxaz if this is still a problem please re-open and let us know
