### ISSUE TITLE
Ability To Delete Files From Javascript SDK

### ISSUE THREAD

**Issue by ratewar** [web3-storage/web3.storage#1292]
Currently in documentation it's not showcased how i can delete a file. While i login to account i have an option to delete. I have a use case where i need to retain files for certain period of time and later archive or delete. 

Can this be added to Javascript SDK so that i can use API call to delete data from my account.

**Comment by dchoi27** [comment]
Yes, that's in the plans though it probably won't get implemented for a few months (some blocking work is being done first)

Closing this issue, tracking in #386
