### ISSUE TITLE
Pinning Service Access Request

### ISSUE THREAD

**Issue by nosovk** [web3-storage/web3.storage#1303]
I've tried to create request for IPFS pining access.
There is a link in issue templates: https://mailxto.com/ta3m8b
It seems that link is not working anymore. When I try to visit it (even in incognito) - nothing happens.

**Comment by nosovk** [comment]
Probably it will be closed by https://github.com/web3-storage/web3.storage/issues/1294 in the future, but having some temporal solution would be nice.

**Comment by dchoi27** [comment]
Hm - @mbommerez can you take a look?

In the meantime, feel free to send an email from the email address associated with your account to `support (at) web3.storage` with a description of what your project is and what data you're looking to pin.

**Comment by JeffLowe** [comment]
With the new web forms for submitting user requests (found on the user's https://web3.storage/tokens page), these mailto links are now obsolete and will be removed in the days to come.
