### ISSUE TITLE
Migrate to wrangler v2

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#1317]
Wrangler v2 is the future. I think the notable changes for us are "better error messages" and "r2 support"
https://developers.cloudflare.com/workers/wrangler/compare-v1-v2/

There are a few tweaks to make to adopt it
https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/

**Comment by vasco-santos** [comment]
We did https://github.com/web3-storage/web3.storage/pull/1432 and https://github.com/web3-storage/web3.storage/pull/1603 for this.
