### ISSUE TITLE
Improve error message when pinning when api is read-only

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#1319]
We just drop a 503 service unavailable on the user. Can we give them a "API is read-only for maintenance. See https://status.web3.storage for details"

```console
$ ipfs pin remote add --service=web3stage --name="ayy2.jpg" bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle                                                   
Error: reason: "", details: "": 503 Service Unavailable
```

When we try to create a new api token during a read-only period we get a better error like
```
{"code":"ERROR_MAINTENANCE","message":"API undergoing maintenance, check https://status.web3.storage/ for more info"}
```

**Comment by olizilla** [comment]
Same issue when trying to list pins during a full "no reads or writes" maintenance mode

```console
$ ipfs pin remote ls --service=web3stage                                                                                                                                 
Error: reason: "", details: "": 503 Service Unavailable
```

**Comment by joshghent** [comment]
I believe this is resolved by #1710 
I cannot recreate the issue locally now

**Comment by flea89** [comment]
@flea89 to try to reproduce this one and close if not.

**Comment by mbommerez** [comment]
Closing ticket as issue couldn't be reproduced locally after fix.
