### ISSUE TITLE
Show a useful error message to blocked users trying to use the pinning service

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#1320]
as per #1319 when adding a pin as a blocked user today we get:

```console
$ ipfs pin remote add --service=web3stage --name="ayy3.jpg" bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle
Error: reason: "", details: "": 403 Forbidden
```

this could explain why, and what we want the user to do about it if anything.

**Comment by olizilla** [comment]
we could do better in the pinning service too, as per #1319 when adding a pin as a blocked user. currently we get

```console
$ ipfs pin remote add --service=web3stage --name="ayy3.jpg" bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle
Error: reason: "", details: "": 403 Forbidden
```

**Comment by olizilla** [comment]
Related https://github.com/web3-storage/web3.storage/pull/1302

**Comment by JeffLowe** [comment]
@olizilla I believe this requirement is captured here https://github.com/web3-storage/web3.storage/issues/1266
Were you thinking about something in addition to or different from 1266?

**Comment by olizilla** [comment]
Ah yes, thanks, #1266 covers the website part of it. The error for the pinning service seems like a seperate enough issue.

**Comment by olizilla** [comment]
@JeffLowe i've updated this to just focus on the pinning service error. But if that's captured elsewhere, feel free to close this out.
