### ISSUE TITLE
Dependencies not found while using web3strorage with Vue

### ISSUE THREAD

**Issue by jutivia** [web3-storage/web3.storage#1323]
I kept getting these errors while trying to integrate Web3Strorage with Vue
`These dependencies were not found:                                                                                        
 friendly-errors 09:37:43
 friendly-errors 09:37:43
* ipfs-car/blockstore/memory in ./node_modules/web3.storage/src/platform.web.js                                            
 friendly-errors 09:37:43
* ipfs-car/pack in ./node_modules/web3.storage/src/lib.js                                                                  f
friendly-errors 09:37:43
* ipfs-car/unpack in ./node_modules/web3.storage/src/lib.js                                                                
 friendly-errors 09:37:43
 friendly-errors 09:37:43
To install them, you can run: npm install --save ipfs-car/blockstore/memory ipfs-car/pack ipfs-car/unpack `

I've tried reinstalling the package, deleting my node modules and no progress.

**Comment by dchoi27** [comment]
Closing this for now.

**Comment by dchoi27** [comment]
Closing this for now.
