### ISSUE TITLE
Broken links for Account Limit Increase Request and Pinning Service Access Request

### ISSUE THREAD

**Issue by 2color** [web3-storage/web3.storage#1330]
When trying to request access to the pinning service the two links are broken:

- https://mailxto.com/ta3m8b
- https://mailxto.com/xy5ijb

<img width="951" alt="Screen Shot 2022-05-17 at 10 48 19 am" src="https://user-images.githubusercontent.com/1992255/168770482-e23b9d75-30fa-4542-84a6-f5fccd2d65ab.png">

Would be great to fix them.

On the same note, would it make sense to update the link in the [docs](https://github.com/web3-storage/docs/blob/main/docs/how-tos/pinning-services-api.md?plain=1#L15) to link directly to the request form? I'd be happy to submit a PR.

**Comment by dchoi27** [comment]
hey - team is looking at this

In the meantime, feel free to send an email from the email address associated with your account to support (at) web3.storage with a description of what your project is and what data you're looking to pin.

**Comment by JeffLowe** [comment]
This will be resolved with upcoming user request management feature (which includes web forms).
