### ISSUE TITLE
radius on storage usage meter is off-centre

### ISSUE THREAD

**Issue by adamalton** [web3-storage/web3.storage#1337]
This is a small visual bug which seems to have been introduced in commit `86ddacf9a` as part of #1300.

The border-radius on the storage meter progress bar isn't quite right, making it look off-centre.

**Existing version on the current website:**

<img width="1440" alt="storage-progress-old" src="https://user-images.githubusercontent.com/270255/169069927-49767f29-d835-4cd6-afa9-91809f6259d8.png">

**New version in `main` (currently at commit `b95b7868d59bf7ce01ac98abfad8d9cec377f5f9`):**

<img width="1440" alt="storage-progres-new" src="https://user-images.githubusercontent.com/270255/169069903-4ca94a0c-bc96-4761-a6c4-c0c697e79262.png">

**Comment by JeffLowe** [comment]
Reviewed and confirmed this is no longer an issue.
