### ISSUE TITLE
Document Whether the PSA Endpoint Will Always be Invite-Only

### ISSUE THREAD

**Issue by gitannex** [web3-storage/web3.storage#1350]
I'm building a project that uses the web3.storage API. When users want to store content that we know is already on IPFS, we use the PSA endpoint to pin the existing CID rather than re-uploading it. When I distribute this software, it will use the user's API key. 

I took this approach because I assumed that all web3.storage users would be able to use the PSA endpoint when the bugs were worked out, but I notice that there is still discussion over process around requesting access. Could you clarify in the documentation whether there is a timeline for general access to this endpoint, or whether it is intended to always be invite-only? FWIW, the latter case would make it unfeasible to use in software such as mine, so I'll need to rewrite it to make less efficient.

**Comment by dchoi27** [comment]
Hey, we'll try to make it more open (we're currently in the process of becoming a pay-for service with storage tiers, and at that point, can likely just open up the PSA). However, this is a huge vector of abuse (we've seen it before) and we have to be careful about how we allow users to use the PSA. So to be safe, my recommendation is to not rely on the assumption that users won't need to request access first as you're building your app.

Don't think it's necessarily useful to document this in the docs themselves though - given what's on the website currently, there's no reason to assume that it won't become open to use without requesting first.
