### ISSUE TITLE
Monetize downloads

### ISSUE THREAD

**Issue by pdr76** [web3-storage/web3.storage#1352]
You should implement paying users who use the platform by uploading files, monetizing downloads, you could create a token (in Ethereum, BSC, Polygon, Solana, Fuse, Cardano, etc...) and pay in that token. That would greatly increase the interest in using the platform.

**Comment by dchoi27** [comment]
Hey! This is similar to what the Filecoin network does (and all the data stored on Web3.Storage ends up on Filecoin). We do run public IPFS HTTP gateways that are free to use, but we are also looking at premium pay-for features as well (e.g. check out nftstorage.link, which is the gateway for our sister project NFT.Storage)

**Comment by pdr76** [comment]
But Filecoin does not pay who uploads and shares, but who lends their space and bandwidth.
