### ISSUE TITLE
website: about page collapsed section is haunted

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#1380]
The collapsed sections on the about page are rapidly opening and closing of their own volition. Probably haunted.

<details>
<summary><b>Flicker warning! Click to see! Defo ghosts 👻</b></summary>

![w3-about-chaos](https://user-images.githubusercontent.com/58871/171011994-37106cc7-3d76-44db-9226-fad02c4c435d.gif)

</details>

**Comment by orvn** [comment]
@JeffLowe it should be fixed in #1391 already (in review), but just needs some testing to make sure it works on different devices/browsers!
