### ISSUE TITLE
Refactor approach to navigation

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1385]
Although there are specific issues to resolve (listed below), we should look at how navigation is implemented comprehensively and improve implementation patterns/approach where needed. 

- [ ] fix the bounce in the Y translation effect where the nav item translates away from the cursor and has an undesired "bounce" effect. (first noticed https://github.com/web3-storage/web3.storage/issues/1458#issuecomment-1157665449 )
- [ ] At minimum, refine approach to avoid nested links 
https://github.com/web3-storage/web3.storage/blob/main/packages/website/components/navigation/navigation.js#L250

NOTE:  #1458 can be addressed at same time as this

**Comment by johnathonroach** [comment]
@JeffLowe the bounce effect/glitch should now be fixed prod. https://web3.storage/

**Comment by JeffLowe** [comment]
confirmed complete on production. good work
