### ISSUE TITLE
Wrong link for HTTP API docs

### ISSUE THREAD

**Issue by aschmahmann** [web3-storage/web3.storage#1393]
https://web3.storage/docs/how-tos/reference/http-api/ is used rather than https://web3.storage/docs/reference/http-api/, at least on the page https://web3.storage/docs/how-tos/store/.

**Comment by johnathonroach** [comment]
@JeffLowe @aschmahmann this appear to be in development with a merged PR awaiting deployment?

https://github.com/web3-storage/web3.storage/pull/1358
