### ISSUE TITLE
`/car` endpoint sometimes fail with `Worker exceeded resource limits`

### ISSUE THREAD

**Issue by Jorropo** [web3-storage/web3.storage#1400]
I'm uploading perfectly good cars ~98MiB, but they are failing for some reason. (note I can just retry right away with the same car and it usually works)

I guess the internal resource usage is inconsistent.

**Comment by dchoi27** [comment]
@yusefnapora can you add a line in the HTTP API docs for Web3.Storage and NFT.Storage telling people to bake in some buffer against the theoretical limit? It's pretty opaque.

**Comment by dchoi27** [comment]
This should be solved with the rollout of Elastic IPFS in production, please reopen if not!

**Comment by Jorropo** [comment]
Ok thx :)

**Comment by chaitanyaprem** [comment]
I have been noticing this inconsistent issue in our system where we chunk and upload CAR files to `/car`. 

I am using 90MB as chunk size just to be on safe side, and am still noticing this issue. 
The response from api.web3.storage is a HTML file which indicates 
"Worker exceeded resource limits" and it is coming from cloudflare. Attaching the html response for reference. 

[web3_storage_err_resp.log](https://github.com/web3-storage/web3.storage/files/9743608/web3_storage_err_resp.log)

**Comment by dchoi27** [comment]
Hey, my best recommendation is to check out the beta of w3up, our new upload API / associated clients: https://blog.web3.storage/posts/w3up-beta-launch

The CAR chunk size is larger (theoretically up to 4GB) and seems to handle things more predictably.

**Comment by chaitanyaprem** [comment]
Thanks for pointing me here @dchoi27  , I could only find front-end API's here.
Could not find HTTP API's that can be used, as the service which I am using to upload to web3.storage is golang based.

**Comment by dchoi27** [comment]
Ah, unfortunately it'll be difficult to use the API directly for a while (since auth is UCAN-based). There is a CLI option for w3up if you can make it work.

Otherwise, if you need to use an HTTP API directly, is it possible to use the current API with smaller than 90MB chunk sizes? Just so it's more consistent?

**Comment by chaitanyaprem** [comment]
I have reduced the chunk size to 50MB and that seems to have done the job with the` /car` API . Maybe the documentation for the old API can be updated with a smaller chunk size limit to achieve consistency. Will monitor and get back in case i run into issues again. 
Thanks a lot for the help.
