### ISSUE TITLE
Web3.storage is failed to npm install due to npm version

### ISSUE THREAD

**Issue by IntelMin** [web3-storage/web3.storage#1416]
I was trying to run `yarn add web3.storage`.
Following error occurred. My node version is `14.17.5`.

```
error ipfs-unixfs@6.0.9: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.17.5"
error Found incompatible module.
```

I found that `ipfs-unixfs@6.0.9` module is published a few days ago and this could be a reason of this error.
Is there anyway to install `web3.stroage` by not upgrading `node` to `16.0.0`?

**Comment by TeodorescuCostin** [comment]
Hi, 
In the package.json the node engine version is specified as "16.x" so I think (but I am not 100% sure) that you would need to update it. 
Here is the line of code:
```
"engines": {
    "node": "16.x",
    "npm": ">=7.x"
}
```
I think you can use [NVM ](https://blog.logrocket.com/how-switch-node-js-versions-nvm/)if you want to use multiple node versions.
