### ISSUE TITLE
Provide w3name functionality in Web3.Storage JS module

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1424]
### Context:

As w3name will be available as a separate package and extracted from web3.storage, we want don't want to break current users' setup.

### Scope of this ticket:

* Import and expose w3name package inside web3.storage

### Acceptance criteria:

- [ ] As a developer, I can continue using the web3.storage [mutability](https://github.com/web3-storage/web3.storage/tree/main/packages/client#mutability) API via w3name

**Comment by mbommerez** [comment]
Next steps:
- [ ] Figure out what is going wrong - fix compiler error in the PR 1707
- [ ] End to end test of creating a name record through w3storage (proxy to w3name) and see if all works as before

**Comment by mbommerez** [comment]
Still to be done: end to end test in Staging.

**Comment by mbommerez** [comment]
Stuck because waiting for #47 (w3name repo) about CORS headers.

**Comment by adamalton** [comment]
The various parts of this are now deployed.

Tested locally and it works as expected:
```
$ npx w3 name create
k51qzi5uqu5dgy4frpwc9k9klrh9rzjz3x3tmd12h1xyoyrpdvnikbcgenpzdm
$ npx w3 name publish k51qzi5uqu5dgy4frpwc9k9klrh9rzjz3x3tmd12h1xyoyrpdvnikbcgenpzdm /ipfs/bafkreid7fbwjx4swwewit5txzttoja4t4xnkj3rx3q7dlbj76gvixuq35y
$ npx w3 name resolve k51qzi5uqu5dgy4frpwc9k9klrh9rzjz3x3tmd12h1xyoyrpdvnikbcgenpzdm
/ipfs/bafkreid7fbwjx4swwewit5txzttoja4t4xnkj3rx3q7dlbj76gvixuq35y
```
