### ISSUE TITLE
'.' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by chengpengjava** [web3-storage/web3.storage#1439]
我拉取了web3.storage项目，然后进入到packages/tools目录下，先npm install导入依赖，然后根据package.json文件中的命令执行了npm run cluster:start，结果报错如下：
![image](https://user-images.githubusercontent.com/33616855/173034500-5cdaf633-28ad-4c56-bd9a-ea98a7e94921.png)

**Comment by dchoi27** [comment]
Hi - sorry, no one on our team can read Chinese. Closing this issue.
