### ISSUE TITLE
Fix issues with top nav active state

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1458]
Note:  #1385 can be addressed at same time

- [x] after visiting DOCS, the "DOCS" active state underline remains. User see's 2 active states.  Ensure this doesnt happen

- [x] Ensure all active states are visible, even with differing background colors. 

## Example of 2 active states after visiting DOCS
![Screen Shot 2022-06-13 at 9 47 58 AM](https://user-images.githubusercontent.com/2078567/173381175-1f42fb33-c99a-49a2-b591-23626f943930.png)
## Active state underline on PRICING page is not visible because it's a black underline on a black background. 
![Screen Shot 2022-06-13 at 9 48 08 AM](https://user-images.githubusercontent.com/2078567/173381237-49d5e8fb-ed03-47b0-9f26-75dd28dc34b1.png)

**Comment by johnathonroach** [comment]
@JeffLowe while tracking down the source of these issues, I also noticed a bounce in the Y translation effect where the nav item translates away from the cursor and has an undesired "bounce" effect.

![bouncy-fun-times](https://user-images.githubusercontent.com/1884440/174081044-a01b37f8-5bfd-4347-b61d-716d01830d2d.gif)

Should I deal with that in this task also or do we want to create another ticket and call that out?

**Comment by JeffLowe** [comment]
Good catch @johnathonroach 
I've included that observation in the navigation refactor ticket #1385 So go ahead an keep this one just focused on resolving the active state.
