### ISSUE TITLE
Resolve white background on magiclink login screen

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1472]
as started in #1446 we are resolving an issue with jarring white backgrounds on login screens.  The first part of the solution was resolved with that pr.  We found the magiclink page woudl be achievable, but take a bit more time, so ticketing separately.

**Comment by drewdelano** [comment]
I think we can fix this one:
![image](https://user-images.githubusercontent.com/22156330/173701191-064448fc-6feb-43c7-9d49-fd5e7cacce78.png)

I also noticed this one:
![image](https://user-images.githubusercontent.com/22156330/173701249-e959b470-a23f-4dc0-94f9-df5148ec9c50.png)
Which I don't think we can fix, but there might be some configuration settings on the magic link side

**Comment by drewdelano** [comment]
Looking around a little more in the settings for magic link and I think this is an option you can configure without code:
![image](https://user-images.githubusercontent.com/22156330/173701890-5c4df41d-3e82-4eec-bc22-a41b5769b73b.png)

**Comment by olizilla** [comment]
OK
- updated the logo
- set dark theme
- set primary color to #7E81FF

<img width="1413" alt="Screenshot 2022-06-15 at 19 07 40" src="https://user-images.githubusercontent.com/58871/173895585-81aa3793-f926-4fc3-907f-2c2bb586f246.png">

**Comment by olizilla** [comment]
Ok this is done for realz now.
