### ISSUE TITLE
My pins aren't showing up on the dashboard.

### ISSUE THREAD

**Issue by augustfr** [web3-storage/web3.storage#1473]
I've pinned a good number of files but none of them show up in the dashboard.

![Uploading Screen Shot 2022-06-14 at 3.25.53 PM.png…]()

**Comment by JeffLowe** [comment]
Likely related to #1449

**Comment by mbommerez** [comment]
Hello @augustfr 

One of your web3.storage tokens has been deleted. Is it possible you are trying to display pinned files that were pinned using that particular token?

Also, you screenshot isn't working. Can you upload it again please and provide as much context as possible? Thanks!

**Comment by mbommerez** [comment]
Hello @augustfr 

Will close this ticket. Do let us know if you encounter more issues!

Thanks
