### ISSUE TITLE
Uploads via Pinning API or capacity used in the storage bar from pinning API uploads doesn't work

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1474]
There are some reports of users, some of whom are heavy users of the Pinning Service API, not seeing these uploads in their dashboard or in the storage used bar.
 
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/a4503cc2-2ef4-4d76-8c1b-0069636ae825)

We should test to make sure the dashboard works properly for pinning service API users in a number of situations (users with a few uploads, users with many uploads, etc.).

**Comment by augustfr** [comment]
Yes this is the issue I've been having. I have around 16 files pinned. Over 20gb total. But none are showing up in the dashboard at all.

**Comment by JeffLowe** [comment]
Note @drewdelano some changes coming to accounts page with https://github.com/web3-storage/web3.storage/pull/1431
