### ISSUE TITLE
/user/uploads/:cid - new endpoint to display upload metadata for given CID

### ISSUE THREAD

**Issue by 3456091** [web3-storage/web3.storage#1481]
As discussed in #1376 I would like a way to limit the /user/uploads output to a given CID.

My motivation is that I want to determine whether a user has uploaded a given CID to w3s without having to iterate over the entire /user/uploads list. Currently, the worst case requires me to request every batch of uploads the user has ever made---and this needs to be sequential because the paging is based on upload dates.

I have no preference whether this is exposed as a query parameter on /user/uploads or a path rooted at /user/uploads. I'd appreciate a 404 being returned if the current user didn't upload the given CID. I suggest the docs specify that, like /user/uploads, this endpoint ignores content added via the PSA endpoint.

Thank you!

**Comment by 3456091** [comment]
Could this be merged please?

**Comment by joshJarr** [comment]
Hey @3456091, Apologies for the delay, but this has now been merged and deployed!
A new endpoint `/user/uploads/{cid}` has been added and documented here: https://web3.storage/docs/reference/http-api/
Let us know if this works for you.

Thanks!

**Comment by 3456091** [comment]
Thanks for this. I'll evaluate it soon and let you know of any problems.

**Comment by joshJarr** [comment]
Ace, thanks!

**Comment by mbommerez** [comment]
Thanks @3456091 , we will close this ticket in the meantime. Do let us know if you encounter any issues.
