### ISSUE TITLE
Add pagination to the /pins endpoint 

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1507]
As discussed on the [previous pagination ticket](https://github.com/web3-storage/web3.storage/issues/1362#issuecomment-1140105729), it may make sense to add pagination on the pins endpoint. This will help when loading a large set of pins and keep the endpoint consistent with the `GET /user/uploads` endpoint.

**Comment by JeffLowe** [comment]
Let us know once this lands @joshJarr so we can update the frontend to use it.

**Comment by mbommerez** [comment]
@dchoi27 Are you happy for us to add this into the psa follow up initiative as well? This would make things a lot easier for the pins table in the front end, as it will mean they use the same structure as the uploads table.

Let us know if you need more info and we'll be happy to explain further why that is the case.
CC @joshJarr

**Comment by joshghent** [comment]
This should have been done as part of https://github.com/web3-storage/web3.storage/pull/1718
