### ISSUE TITLE
Denormalise file size onto user uploads so that we can efficiently sort by it when fetching uploads

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1508]
When paginating uploads ([task 1362](https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1362))sorting is now applied in the API.
This makes it tricky and inefficient to sort uploads by file size as that data is not stored on the upload entity.
We should add a new column with the denormalised `dag_size` so that we can sort by file size when fetching these uploads with pagination.

**Comment by mbommerez** [comment]
@dchoi27 This is an API change we'd need to make and it might be quite meaty effort-wise, especially if we count tests & migration etc. Do you think there is a strong use case for people to sort their uploads by filesize in the W3s front end interface?

**Comment by jchris** [comment]
My opinion on this is we should defer the work to depend on w3query when it ships, rather than do a heavy lift that will only be temporary.

**Comment by dchoi27** [comment]
^ +1

**Comment by dchoi27** [comment]
let’s make sure requirements are captured in new uploads lib before closing
this out
