### ISSUE TITLE
Add searching for user uploads in the API

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1509]
BLOCKED: Until PL Product decision is made. 

When looking at pagination, we realised that the API also needs an option to search all uploads by name and CID ([as discussed here](https://github.com/web3-storage/web3.storage/issues/1362#issuecomment-1140105729)).
Currently searching is completed on the Frontend after fetching all data, when moving to using a paginated API this needs to be achievable either via keyword filtering in the `GET /user/uploads` or with a new search endpoint.

**Comment by 3456091** [comment]
See also #1481

**Comment by dchoi27** [comment]
@jchris is searching scoped into the new uploads client?

**Comment by JeffLowe** [comment]
Decision to not build out this new api right now, but will leave this open to ensure it's included in the uploads v2 spec.

**Comment by jchris** [comment]
closing this. it's not scoped explicitly into uploads v2, but as discussed today, the appropriate functionality should be "trivial" to implement once w3query is ready.
