### ISSUE TITLE
Create a script to populate large data sets of uploads and pins for testing

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1511]
I made a quick script to generate 1000 files for testing pagination and performance.
Feel like it could be useful, so plan on cleaning it up and committing it - could also be handy to do the same for pins.

**Comment by mbommerez** [comment]
@dchoi27 Are you happy for us to implement this? Could be helpful to test file lists and pagination for both uploads and pins. Alternatively, can put in backlog.

Put estimate at 1 days, but should definitely be less than that.

**Comment by dchoi27** [comment]
Let's scope into the PSA follow up issue! And do this if this would be useful for the other tickets in that set

**Comment by joshJarr** [comment]
I've had a little script to do this locally for a while, but a few people have asked me for it when building and testing the pagination for uploads and pins, so thought I'd just commit it

**Comment by flea89** [comment]
We identified an improvement, the script currently does not throw any error if pins can't be created.
@joshJarr to create a follow-up ticket for that.
