### ISSUE TITLE
Correct broken links throughout Docs pages

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1525]
Links throughout the Docs pages are broken. All seem to be links to markdown content files.  Below lists issues on just the homepage of the docs.  These broken links appear throughout the docs and need to be corrected to point to the right pages/sections. 
#1524 might address some of the issues. 

## page https://web3.storage/docs/
- [ ] "Query how-to guide" points to https://web3.storage/docs/how-tos/query.md#querying-for-status-information but should instead point to https://web3.storage/docs/how-tos/query
- [x] "JavaScript client library" broken.  Currently points to https://web3.storage/reference/js-client-library.md but should instead point to https://web3.storage/docs/reference/js-client-library
- [x] "content identifier (CID)" broken.  Currently points to https://web3.storage/concepts/content-addressing.md but should instead point to https://web3.storage/docs/concepts/content-addressing
- [x] "Store how-to guide." points to https://web3.storage/how-tos/store.md but shoudl instead point to https://web3.storage/docs/how-tos/store
- [x] "Retrieve how-to guide." points to https://web3.storage/how-tos/retrieve.md but instead shoudl point to https://web3.storage/docs/how-tos/retrieve
- [x] "reference API section" points to https://web3.storage/reference/js-client-library.md but instead shoudl point to https://web3.storage/docs/reference/js-client-library

## Page https://web3.storage/docs/how-tos/pinning-services-api/
- [ ] "API token" in the "Requesting Access" section leads to https://web3.storage/how-tos/generate-api-token but instead should lead to https://web3.storage/docs/how-tos/generate-api-token

**Comment by johnathonroach** [comment]
@JeffLowe I'd like to call out that the approach we are taking will fix the links in the docs sections of the website but will break previously-functional links when these `md` pages are viewed in Github-rendered markdown.

This may in fact be the desired result but I want to call it out in case the expectation is otherwise.

**Comment by JeffLowe** [comment]
Thanks for calling that out.  I believe having functional links in content when viewing the file from GitHub is far less important than having the links functional in the /docs UI on the site.

**Comment by johnathonroach** [comment]
@JeffLowe the issue with the #quickstart jumper may be a larger issue - I am seeing this with many of the jump links on the site. Example: deep linking down to run the script is not working either. https://web3.storage/docs/#run-the-script

Possible we could create a new issue for this?

**Comment by JeffLowe** [comment]
Ticketed here https://github.com/web3-storage/web3.storage/issues/1540
