### ISSUE TITLE
Improve spacing / styling of user request forms

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1534]
We have functional first pass implementation of the user forms (Pinning service API Access and the Storage Rate Increase).  David recently called out the " (the spacing in between lines vs. the spacing by the box looks a bit weird)?"

**Comment by cmunns** [comment]
We have an existing modal design. It feels like we should also move towards that. 
<img width="907" alt="Screen Shot 2022-07-20 at 11 01 51 AM" src="https://user-images.githubusercontent.com/1189523/180051534-851db82a-ceef-4b8d-9a60-fcb42f311cb0.png">
.

**Comment by JeffLowe** [comment]
Agreed, @cmunns
