### ISSUE TITLE
Remove or Fix "last updated" date on all /docs pages

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1539]
Regardless of the page's actual last edit, every page seems to list today's date.  We need to either correct this to pull the last edited date of the page, or just eliminate this from the page completely. 
![Screen Shot 2022-06-20 at 8 22 16 AM](https://user-images.githubusercontent.com/2078567/174673566-ef89e62f-6a88-4bdc-9c83-401fcc107410.png)

**Comment by e-schneid** [comment]
@JeffLowe I opted to just yank out the date.  The current code just pulls the date from the date of the deployment, but there isn't a good way to get page by page update dates currently (short of setting it manually for every page).
