### ISSUE TITLE
Upload file in existing CID 

### ISSUE THREAD

**Issue by rnobakht** [web3-storage/web3.storage#1543]
Hi.
We want to use Web3.storage for storing ERC1155 NFT meta data. In this contract we need constant base Address for URI. for example https://ipfs.io/ipfs/CID/TOKEN_ID. Since tokens minting is not at same time, we need to upload file in Existing CID with token id index. Is there any feature to do this?

Thanks.
Best regards

**Comment by Meowcat285** [comment]
Its not possible to use a existing CID, as the CID is based entirely on the contents of the upload. The CID is actually a hash.

Hope that clears things up!
(Note: I am not a official member of this project)

**Comment by dchoi27** [comment]
^ yup that's exactly right. For a folder, the CID is a unique identifier for the underlying folder. If your uploads don't need to be in the same "folder," we'd recommend just uploading each file separately and referencing each file's CID in the corresponding NFT (so you don't have dependencies on future uploads)
