### ISSUE TITLE
Docs on mobile has odd horizontal spacing

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1553]
On iOS Safari, page doesn't extend all the way to the right. 
![image](https://user-images.githubusercontent.com/11778450/175080871-dc41c774-4e6a-49fb-90d6-9b850d4942ad.png)!

Also bullets seem kind of funny (too much space between bullet and text)
[image](https://user-images.githubusercontent.com/11778450/175080880-34ad1af6-5c9a-4e45-ad9b-6ed44922f6ad.png)

**Comment by cmunns** [comment]
@dchoi27 I've tested simulators as well as real devices but can't replicate this. Do you mind testing again and closing out if it appears resolved ?

**Comment by dchoi27** [comment]
ah yeah it's fixed. thanks for flagging
