### ISSUE TITLE
Polish nextra docs on desktop and mobile

### ISSUE THREAD

**Issue by orvn** [web3-storage/web3.storage#1556]
The docs site, which was replatformed to Nextra (#1138) and now lives in the `website` package requires some additional polish to match the design quality of the rest of the site. For mobile there are some layout bugs. Screenshots are included at the end of this issue.

## Desktop

- [x] ToC navigation is abrupt, should have a transition applied
- [x] Lists (ordered and unordered) have excess space on the left, they should be modified to have more standard typographic indentation
- [x] Docs tabbed areas are missing transitions and hover effects
- [x] Hover effects for regular links should match the marketing site
- [x] Hover effects for previous and next buttons at the end of articles should match the marketing site
- [x] For code blocks, add copy to clipboard state that appears on hover (similar to what's on the site's home page)
- [x] Style inline code `elements` more clearly, currently they're just monospace text
- [x] Reduce margins on `<p>` elements when followed by lists or code blocks as their immediate sibling
- [x] Buttons are not vertically centred in the _was this information helpful_ area
- [x] Add transition to sidebar headings
- [x] Add syntax highlighting for unix shell codeblocks (any of `bash`, `zsh`, etc. should be okay)
- [x] Remove outline property on accordions and use the hover state as the focus
- [x] Add height transitions to accordions (HTTP API page)
- [x] Rotate the accordion chevron when opening/closing it (HTTP API page)
- [x] Adjust the margins between headings (HTTP API page)
- [x] Indent accordion chevrons (image gallery)

## Mobile
- [x] Main container is not 100% viewport width (on iOS)
- [x] Navigation background image open state should be stretched to avoid contrast issues
- [x] Tables and toggles (on HTTP API) are compressed
- [x] Algolia no search results state suggestions look a little condensed (_"Try searching for"_ section)

### Images from mobile
_(Tested on Android as well, but these images are from iOS 15 Safari on an iPhone 13 Pro)_

<img src="https://user-images.githubusercontent.com/3689720/175127165-151f7587-60e3-43c3-9d0b-0c73b5edd07c.png" width="300"> <img src="https://user-images.githubusercontent.com/3689720/175127162-9c66be54-9832-455f-ace7-38f312b837c6.png" width="350">

<img src="https://user-images.githubusercontent.com/3689720/175127453-42742b16-4333-46d8-9b9e-4d815e9bfafb.png" width="300"> <img src="https://user-images.githubusercontent.com/3689720/175127458-3d61fffe-b5fc-423f-87fe-f65668e75ea6.png" width="350">

**Comment by joannaong** [comment]
@orvn what do you mean by "Algolia no search results state suggestions look a little condensed ("Try searching for" section)"?

**Comment by orvn** [comment]
@joannaong I think it might be fixed by the whole canvas being compressed, but see the 4th screenshot above where there are no results. I see three issues:

- Excess line height in the suggested page link
- `»` double arrow/guillemet wraps to a separate line, but it should be in the same line as each link)

<img width="240" alt="algolia no results" src="https://user-images.githubusercontent.com/3689720/176000503-567e95c1-17e3-435d-94f1-46cbe91ab4b7.png">
