### ISSUE TITLE
Update /docs page link leading to /how-tos/store

### ISSUE THREAD

**Issue by freeduck** [web3-storage/web3.storage#1566]
Update the "storage how-to guide" hyperlink on the page https://web3.storage/docs/how-tos/generate-api-token/

It currently points here:  https://web3.storage/docs/store
It should point to here:  https://web3.storage/docs/how-tos/store/

**Comment by freeduck** [comment]
https://web3.storage/docs/how-tos/store/ this works 

update https://web3.storage/docs/how-tos/generate-api-token/

**Comment by e-schneid** [comment]
unable to reproduce -- already been fixed
