### ISSUE TITLE
invalid CID: length greater than remaining number of bytes in buffer

### ISSUE THREAD

**Issue by Schwartz10** [web3-storage/web3.storage#1569]
I uploaded several files to web3 storage via the javascript client using the `put` method and got back a CID `bafybeibd26bcxuy6qjgccycpn6fuzapvrqjjowhmhqqq7l5ue5o3zb5t7` 

When i try to fetch this cid on any ipfs gateway, I get back an error: 

```
ipfs resolve -r /ipfs/bafybeibd26bcxuy6qjgccycpn6fuzapvrqjjowhmhqqq7l5ue5o3zb5t7/: invalid path "/ipfs/bafybeibd26bcxuy6qjgccycpn6fuzapvrqjjowhmhqqq7l5ue5o3zb5t7/": invalid CID: length greater than remaining number of bytes in buffer
```

I've uploaded several files with very similar structures that work fine. Any idea why this could happen? Let me know what extra information is most helpful.

**Comment by ribasushi** [comment]
@Schwartz10 CID is malformed ( missing bytes ): https://cid.ipfs.io/#bafybeibd26bcxuy6qjgccycpn6fuzapvrqjjowhmhqqq7l5ue5o3zb5t7

99% this is a copy/paste error. For the 1%: we would need a set of steps to reproduce...

**Comment by Schwartz10** [comment]
Yeah actually re-uploading the same files resulted in the same hash, copied it again and it worked
