### ISSUE TITLE
Performance issue - User Account Storage calculation

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1571]
## Context
As part of the Storage Limit Notification [Epic](https://github.com/web3-storage/web3.storage/issues/851), we created a cron job to go through all the Web3.storage users, calculate their used storage (both uploads and pin requests) and send email notifications to users and admins.

To do so we created a [users_by_storage_used](https://github.com/web3-storage/web3.storage/blob/main/packages/db/postgres/functions.sql#L305) to get all the users in a specific storage range. The function can take a ‘user_id_gt’ and ‘user_id_lte’ to limit the query to a restricted amount of users.

From the cron job we iterate through 20 users at the time, run the query and send the required emails.

## Challenge
Running [users_by_storage_used](https://github.com/web3-storage/web3.storage/blob/main/packages/db/postgres/functions.sql#L305) is extremely slow.

The same job, on a comparable amount of data in staging, runs fairly quickly. 15m vs several hours in prod.
I compared the indexes, and unless I missed something they look the same in the 2 instances.

In production, for some batches of users, it takes up to 30 minutes to run the query. For other groups of users, it’s acceptably quick, ~1/2s.
With this kind of performance, the job can’t go through all the users without timeouting (360 minutes, that results in some (but not all) users receiving an email, and admin never get the list of users exceeding quota.

Auditing the query we found out the existing [user_used_storage function](https://github.com/web3-storage/web3.storage/blob/main/packages/db/postgres/functions.sql#L246) (used by [users_by_storage_used](https://github.com/web3-storage/web3.storage/blob/main/packages/db/postgres/functions.sql#L305)) can be extremely slow for some users.
Important to note the performance of the same exact query could be extremely different between different runs, order of 10 or more differences, suggesting it might also be related by infrastructure issues?

**Comment by mbommerez** [comment]
PR #1573 has been merged - needs thorough testing in PROD.

**Comment by flea89** [comment]
This can be closed for now. 
Job is running in the provided limits in prod
