### ISSUE TITLE
Audit usage of pin_status_idx index

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#1574]
## Context 
 In this [PR](https://github.com/web3-storage/web3.storage/pull/1573) we created a new index on `pin(content_cid, status)`.
 
## TODO

Can we audit how we're querying the `Pin` table and verify if we still need `CREATE INDEX IF NOT EXISTS pin_status_idx ON pin (status);`

If it's unused we should drop it.

**Comment by joshJarr** [comment]
Closing since it's no longer relevant.
