### ISSUE TITLE
Pinning Service Compliance Checker failures

### ISSUE THREAD

**Issue by SgtPooki** [web3-storage/web3.storage#1579]
Hey web3.storage, 

This is a friendly notification that your pinning service is failing some compliance checks. As mentioned in https://github.com/ipfs-shipyard/pinning-service-compliance/issues/125#issuecomment-1167880416, we won't be continuing to open issues moving forward, but I did open a PR https://github.com/ipfs-shipyard/pinning-service-compliance/issues/140 that could help keep you informed about your compliance results in an automated fashion. 

Latest report permalink:
https://github.com/ipfs-shipyard/pinning-service-compliance/blob/dbd8adcbb410579845dcbb584f097b3f74848c54/api.web3.storage.md?plain=1#L4-L28

Let me know if you have any questions/comments!

**Comment by flea89** [comment]
Thanks, @SgtPooki this is great!

Sorry, we've been busy with other priorities, but this looks ace! We'll set it up and tackle any problem raised
