### ISSUE TITLE
Implement blog subscription api endpoint

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1597]
Blog developers need a subscribe api endpoint for the "subscribe to blog" functionality. 
The desire is something similar in function to nft implementation https://github.com/nftstorage/nft.storage/blob/main/packages/website/lib/subscribe.js

Blog developer will do the frontend integration ( via this branch https://github.com/web3-storage/web3.storage/tree/feat/blog ) we are to implement just the api endpoint for them to use. 

- [x] implement stub immediately to unblock blog development
- [ ] once email service determined, complete buildout of endpoint.

**Comment by JeffLowe** [comment]
With the stub in place unblocking blog development, we now await decision on mail service so we can build out & connect the endpoint.

**Comment by joannaong** [comment]
hi @JeffLowe do you have ETA for the final API? cc @orvn
