### ISSUE TITLE
error: cannot drop extension uuid-ossp because other objects depend on it

### ISSUE THREAD

**Issue by chengpengjava** [web3-storage/web3.storage#1599]
Hello Team,I init database by "npm start" and then "npm run load-schema" .OK,I can see all tables by pgAdmin just no data.And then I add one data of public.user and one data of auth_key.Now I have a need to change the table structure of auth_key,so I attempt to change tabale in reset.sql like this:
![image](https://user-images.githubusercontent.com/33616855/176616350-d4359e09-3fcf-4391-8f71-4c752dfd31d5.png)
I add a column "test_col" to auth_key and noted othor "drop table..." because I don't want to drop table in database otherwise cause my data disappear,and then I add a command in package.json like this:
![image](https://user-images.githubusercontent.com/33616855/176617216-26eb1a90-eb73-4da0-a717-f213a3dc7e6b.png)
By the way,README.md is "node scripts/cli.js --reset db-sql",but I encountered this error after trying:
![image](https://user-images.githubusercontent.com/33616855/176618071-d21bd8df-4196-4750-95f5-82b3a5e888ad.png)
So I wrote "node scripts/cli.js db-sql --reset" in package.json,ok I can run but I encountered this error:
![image](https://user-images.githubusercontent.com/33616855/176619176-14a37a99-41a2-4047-b1d9-0e46f868961a.png)
I try to find where location "uuid-ossp" and then I find here:
![image](https://user-images.githubusercontent.com/33616855/176620052-64c27708-1edd-4769-ba9e-f50442a989c0.png)
but I don't know why and I don't know how to solve it

**Comment by vasco-santos** [comment]
@chengpengjava thanks for opening this issue. What is your motivation to run the DB?

This set of scripts have worked for all the team. Can you get us more information for debugging purposes?

**Comment by yusefnapora** [comment]
@chengpengjava I had a similar issue when setting up a local db using the official postgres docker image on docker hub while messing around with our DB setup scripts. Our setup uses the `supabase:postgres` image as a base, which includes some extension not installed in the default image. If you're using the default docker image or have postgres installed directly on your machine, you'll need to install the missing extensions yourself.

**Comment by chengpengjava** [comment]
Thanks,I have solved this problem because I'm not familiar with PostgreSQL,my mistake was to directly extend the database table,I solved the problem by creating a database myself
