### ISSUE TITLE
Odd preview image for link when used in google docs

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#1602]
<img width="352" alt="Screenshot 2022-07-01 at 10 19 52" src="https://user-images.githubusercontent.com/152863/176866082-580d751c-8a29-496c-8052-75e2216b86f4.png">

**Comment by e-schneid** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/99349687/190237175-b7e6b7f4-6578-46fc-88d6-0cae4d7c930f.png)

**Comment by JeffLowe** [comment]
Closing this out as no longer relevant.  Tested from Google Docs in Chrome, Safari, and Brave (MacOS latest).  Could not replicate.
