### ISSUE TITLE
Add E-IPFS node to peerlist

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1605]
- [ ] Align on and set up external domain for our E-IPFS node
- [ ] Add domain to dnsaddr (e.g., /dnsaddr/elastic-ipfs.com/p2p/bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm)
- [x] Add to Web3.Storage peer lists
   - [ ] https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
   - [x] https://github.com/web3-storage/web3.storage/blob/main/PEERS

**Comment by alanshaw** [comment]
The docs site should just be updated to link to our list on github. It's a PITA to keep multiple lists up to date.

**Comment by alanshaw** [comment]
https://github.com/ipfs/ipfs-docs/pull/1228
https://github.com/web3-storage/web3.storage/pull/1692

**Comment by alanshaw** [comment]
A task to update the PEERS lists in both dotStorage has been logged in the notion where Elastic IPFS jobs are currently being tracked.
