### ISSUE TITLE
Getting that error when "sudo w3 list"

### ISSUE THREAD

**Issue by TomThisIsIt** [web3-storage/web3.storage#1610]
Error: 400 Bad Request - invalid before date
    at Function.list (file:///usr/local/lib/node_modules/@web3-storage/w3/node_modules/web3.storage/src/lib.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async list (file:///usr/local/lib/node_modules/@web3-storage/w3/index.js:81:20)
And I can't load many previously uploaded files/directories...well I do admit I use A LOT the web interface to upload MANY individual files so my account has 10k++++ CIDs ;P What can I do? Should I request your pinning service? Thank you!

**Comment by dchoi27** [comment]
#1408 added pagination to the API (which you should be able to use today) and #1501 should add to the website. We'll also get it into the JS client in #1585

**Comment by olizilla** [comment]
Another report from #web3-storage discord
![image](https://user-images.githubusercontent.com/58871/178711801-b25b1426-433a-49be-862a-bd2d43a23d79.png)

**Comment by TomThisIsIt** [comment]
It is still not fixed on the website, can't go past 1000 uploads, I hope you fix it this week or the next one
