### ISSUE TITLE
Find a solution for cargo not updating 'claimed dag size'

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1614]
Follow up issue from #1059 

When we moved to a direct connection to cargo to retrieve the claimed size of a DAG, we assumed that cargo would be updating the claimed size everytime it pulls data from public content. However, we discovered this is not the case and so we have no way of knowing which DAG sizes were updated after running the CRON job.

**Comment by ribasushi** [comment]
🤔 ❓
