### ISSUE TITLE
Storage Notification - Further perf improv

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#1635]
Consider adding an index on `psa_pin_request` table `deleted_at`.
It's currently doing a seq scan on the table that might impact perf.

**Comment by dchoi27** [comment]
@flea89 any thoughts on whether this still should be done with this initiative wrapping up? cc @mbommerez  @vasco-santos

**Comment by flea89** [comment]
This is hopefully a really quick win🤞, so I suggest we do it.

**Comment by dchoi27** [comment]
sweet, if someone on our end needs to do it @vasco-santos @plwileverts can get it into the support initiative

**Comment by flea89** [comment]
I've created a PR [here](https://github.com/web3-storage/web3.storage/pull/1659)
