### ISSUE TITLE
Edits for w3name landing page

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1639]
Tracking edits to #1607 here

- [x] Change `web3storage` in Products dropdown menu to `Web3.Storage`
- [x] change the two "Get Started" cta button links to point to the docs page "/docs/how-tos/w3name/"

**Comment by mbommerez** [comment]
This is live in Production

![Image](https://user-images.githubusercontent.com/93770197/183436593-4396cf70-b3e8-465a-9315-2dba8deee8aa.png)
