### ISSUE TITLE
Timestamp in Files table seems odd?

### ISSUE THREAD

**Issue by jnthnvctr** [web3-storage/web3.storage#164]
The Files table (at least when using manual uploads) seems to be parsing timestamps in an odd way.  All three of these files were manually uploaded (one a week ago, one last night, one today).

Last night while testing, I got: 

![image](https://user-images.githubusercontent.com/21000523/126995222-b67359f8-fa7e-45d1-81a8-ff2a67a6aa25.png)

Today I got: 

![image](https://user-images.githubusercontent.com/21000523/126995162-ec0e1a1d-8f52-4925-8529-9d09726e6615.png)

I think ideally we'd want date + user's local time

**Comment by rafaelramalho19** [comment]
@jnthnvctr We can have whatever format you think it's most interesting.

So far we have
- If it's during the current day, it only shows the hour and minutes it was uploaded at
- If it was another day, it shows the Day, month and year.

Do you want it to always to just be Day, Month and Year?

**Comment by jnthnvctr** [comment]
I think intuitively it feels a bit weird to change formatting - my personal
bias is that we should just spit out date + local time for everything.

**Comment by rafaelramalho19** [comment]
Fixed in https://github.com/web3-storage/web3.storage/pull/172
