### ISSUE TITLE
About the uncertain behavior of hidden data contained in car file

### ISSUE THREAD

**Issue by qdwang** [web3-storage/web3.storage#1643]
I have 2 car files.
```
1.car
    cid_empty 

data in 1.car:
    cid_empty           4B  raw
    cid_x_1             2MB raw
    cid_x_2             2MB raw
    cid_x_3             2MB raw
    cid_y_1             1MB raw
```
```
2.car
    cid_root
        cid_file
            cid_x_1
            cid_x_2
            cid_x_3
            cid_x_4
            cid_x_5
            cid_x_6
            cid_x_7

data in 2.car
    cid_root           unixfs dir bytes
    cid_file           unixfs file bytes
    cid_x_4            2MB raw
    cid_x_5            2MB raw
    cid_x_6            2MB raw
    cid_x_7            2MB raw
```

After uploading these 2 car files to web3.storage, the files listed in web3.storage will contain two items:
```
2.car        14MB
1.car        4B
```
And I can access `cid_file` successfully under `ipfs.io/ipfs/`.

The problem is, if the `1.car` is deleted from the list:
1. Will it also unpin the `cid_x_1`, `cid_x_2` and `cid_x_3` blocks in the future?
2. Will it unpin the `cid_y_1` block?

**Comment by vasco-santos** [comment]
The GC should act to remove blocks that are not associated with a DAG. Given `cid_x_1`, `cid_x_2` and `cid_x_3` are associated with a different DAG they will not be selected for GC by deleting CAR 1

**Comment by qdwang** [comment]
Great. I'm wondering if this GC mechanism will be changed in the future?

**Comment by vasco-santos** [comment]
GC will never delete blocks that are currently known as needed and reachable in a DAG.

Closing for now, feel free to re-open if you need further assistance

**Comment by qdwang** [comment]
@vasco-santos I just found this method of uploading can cause a bug in web3.storage

![image](https://user-images.githubusercontent.com/403616/190569173-0c7cba83-a25b-4af8-9eab-5a5ae6f14c35.png)

My account's usage is always 0 no matter how many contents I've uploaded. And all the contents are available to download.
