### ISSUE TITLE
Do not store uploaded files in directories via HTTP API /upload

### ISSUE THREAD

**Issue by niushay** [web3-storage/web3.storage#1654]
Hello,
 I faced a problem when I wanted to upload a file from Ubuntu server to web 3 storage via HTTP API /upload and cURL. It is stored in a path like this /public/images/image1.png but I want to see just the image file when I load the CID in the URL, not in the embedded directory. What should I do?

**Comment by dchoi27** [comment]
Hi - you'll need to convert the file to a CAR file on your side with the root CID referencing the file itself, before using the /car endpoint to upload. You can learn more here: https://web3.storage/docs/how-tos/work-with-car-files/

The /upload endpoint will encase your upload in a directory.
