### ISSUE TITLE
https://dweb.link/ipfs/<root cid>  504 Gateway Time-out

### ISSUE THREAD

**Issue by newTap** [web3-storage/web3.storage#1677]
Copy the <.env.tpl> file to .env and set the values for the MAGIC_SECRET_KEY & NEXT_PUBLIC_MAGIC，
Modify the ip address of CLUSTER_API_URL, NEXT_PUBLIC_API, GATEWAY_URL
Running on my server according to the following instructions,
```
npm install
npm run load-schema -w packages/db
npm start
```
When web3.storage starts, log in and upload the file, the returned status is Pinned，When I get the corresponding file from the ipfs gateway, the browser shows 504 Gateway Time-out.
How should I modify the configuration file to upload the file to the ipfs gateway

**Comment by vasco-santos** [comment]
If you want to have your content accessible, why not uploading it to the web3.storage production API/website instead?

**Comment by newTap** [comment]
thank you very much

Yes I'm running a local ipfs cluster, but I don't know how I should get the local ipfs cluster to connect with the ipfs network. I tried to open port 5001 and according to webui
  The prompt on the page has modified the corresponding node, but it still cannot make me query on the dweb.link gateway

Also trying to deploy the api/website production environment in web3.storage

**Comment by newTap** [comment]
HI @vasco-santos 
Damn I asked a really stupid question, I should have to look it up through my local ipfs.

But I found another problem, when I upload dozens of KB files and query through https://127.0.0.1:8080/ipfs/<root cid>, the browser will always be in the loading state and cannot display the content, but on port 5001 It can be queried in webui.

When the query file is larger than 1MB, it is no problem to use https://127.0.0.1:8080/ipfs/<root cid>

**Comment by vasco-santos** [comment]
> The prompt on the page has modified the corresponding node, but it still cannot make me query on the dweb.link gateway

There are a lot of things to have in mind. For instance, if you are behind a NAT it might be more difficult to get a connection. I would suggest trying to get help from one of the IPFS support channels. web3.storage tries to help on this front by not requiring users to go through these challenges, given we operate the infrastructure and guarantee connectivity.

Regarding the 1MB limit, are you using nginx? I recall there was a limit on that for 1MB

**Comment by newTap** [comment]
Yes, I am using nginx, how should I solve this 1MB limit

**Comment by vasco-santos** [comment]
@newTap 

This should help https://www.tecmint.com/limit-file-upload-size-in-nginx/
