### ISSUE TITLE
Images on website are broken

### ISSUE THREAD

**Issue by orvn** [web3-storage/web3.storage#1697]
Recently, all Next image components (except the docs) began failing to render in Firefox. Firefox isn't accepting the new format with multiple sources and is detecting it as malformed.

~~Works fine in Chrome (which I imagine the feature was originally tested in)~~

Edit: Issue is cross-browser after all, not just Firefox

<img width="650" alt="images-ff-1" src="https://user-images.githubusercontent.com/3689720/182441049-ecc0c371-8391-455e-9a01-daf6d89c23e5.png">

<img width="650" alt="images-ff-2" src="https://user-images.githubusercontent.com/3689720/182441055-d821fb3e-9896-4868-8d74-c9910886d46b.png">

***

Tested on `Firefox 103`, `MacOS 12.5`

(Assigned `P0` because the Web3 ecosystem at large has a greater segment of Firefox users than other sectors)

**Comment by johnathonroach** [comment]
@orvn, It appears that images were actually broken in all browsers ( 500 errors from all image.web3.storage routes provided from cloudflare ). Trying to access the image in a new tab directly from the images url resulted in another error `Error 1104 "Script not found"`. Again, this only seemed to affect images loaded from images.web3.storage.

For now, the cloudflare-based images are back and being served and loading correctly in the site.

We're investigating further but it's possible that the images worker went down or the custom domain (images.web3.storage) pointing to the actual worker at https://images.protocol-labs.workers.dev/ went down. (the feature is currently in beta). 

So far I have not been able to find any useful logs that may point to the issue but I know a bit more where to look first if this happens again.

We'll continue to monitor.

**Comment by orvn** [comment]
@johnathonroach, that makes sense. Chrome must have worked for me because I had the images cached locally. You're right, when I do a hard refresh, they're broken in Chrome as well.

An improvement idea for the future might be to have the image loader get images from the static site in the event of an issue with CF images or any other related service.
