### ISSUE TITLE
New table component: reusable, accessible and api pagination compliant

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#1711]
# Context
Existing table components are tightly coupled with files and all assume to have all the items on load.
In order to have API paginated uploads and pins we need a table to allow for it.

# Acceptance Criteria
- [ ] The table component allows for api pagination
- [ ] The table component is reusable
- [ ] The table component It allows custom cell rendering
- [ ] The table component allows custom header rendering
- [ ] The table component is accessible

**Comment by mbommerez** [comment]
Reassigning from @flea89 to @joshJarr

**Comment by francois-potato** [comment]
Waiting for #1739 to be merged

**Comment by joshJarr** [comment]
Made a follow up ticket: https://github.com/web3-storage/web3.storage/issues/1834 To ensure styling is aligned across the site.
