### ISSUE TITLE
How-to for peering with Web3.Storage

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1725]
Once we have the final domain name for our E-IPFS node (in the next week or so, @francardoso93 is working on this and can follow up when ready), let's share the peer ID / info in a new section here under Reference, including information about what situations you'd consider peering (you're running your own IPFS nodes and/or gateway) and how to peer. It should also mention that it takes some time for new uploads' records to be picked up by the DHT (via indexers), and if you're using your own IPFS nodes to fetch data, you can circumvent this by peering.

Let's also stick a line in the Store docs that references this section as well as something to keep in mind!

Sister issue to: https://github.com/nftstorage/nft.storage/issues/2129

**Comment by yusefnapora** [comment]
I'm working on this now - @francardoso93 are these the right addresses?

dns6:
`dnsaddr=/dns6/elastic.dag.house/tcp/443/wss/p2p/bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm`

dns4:
`dnsaddr=/dns4/elastic.dag.house/tcp/443/wss/p2p/bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm`
