### ISSUE TITLE
Include query string parameters in the pagination Link URLs

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1737]
We should include _all_ querystring parameters in the pagination response header `Link` URLs for the list Upload and Pin endpoints otherwise clients will lose context when following the `Link` header for pagination.

e.g. setting `sortBy` for the first request, then using the URL in `Link` to get the next page.

_Originally posted by @alanshaw in https://github.com/web3-storage/web3.storage/pull/1408#discussion_r945588182_

**Comment by alanshaw** [comment]
I'll open a PR shortly
