### ISSUE TITLE
Used storage is not displaying properly in the accounts page.

### ISSUE THREAD

**Issue by nicholas716** [web3-storage/web3.storage#1766]
Hi, I've uploaded 26GB files to web3.storage, but I can't see used storage in the accounts page.
Please check the attachment, then you will be able to understand the issue easily.
FYI, my API Token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...DCbDKyao
Thanks
![bug_web3storage](https://user-images.githubusercontent.com/101858931/185417482-0163b175-9f8d-4947-87f0-b5a23a317c63.png)

**Comment by olizilla** [comment]
Is this still an issue? The quota calculations happen asynchronously, it should be showing the correct value now. Please let us know if this is still a problem for your account.

**Comment by mbommerez** [comment]
@nicholas716 Is this still happening? Can you confirm and close if all okay now?

**Comment by vasco-santos** [comment]
It is working for me and other folks. I am closing this, but please re-open if this is still an issue for anyone
