### ISSUE TITLE
Change "Storage" field name and description in accounts table

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#1788]
Right now, the column giving detail on Filecoin SPs storing data just says "Storage" which is confusing and doesn't represent the copy on E-IPFS. Can we:
- Change the `Storage` column to `Filecoin Storage`
- Change the description from `Filecoin storage providers provably storing replicas of this data` to `Filecoin storage providers provably storing redundant replicas of this data`

**Comment by JeffLowe** [comment]
Appears on the /account page in the Files table(s).  

![Image](https://user-images.githubusercontent.com/2078567/187265087-090bf124-b540-4804-9f8b-9e788fc0e847.png)
