### ISSUE TITLE
w3link returns blank page after refreshing 3-4+ times

### ISSUE THREAD

**Issue by aeongdesu** [web3-storage/web3.storage#1811]
![Screenshot_20220828-141404_Kiwi Browser](https://user-images.githubusercontent.com/50764666/187058684-23d8d086-42f8-4ab6-9996-d24fbcf20308.jpg)

![Screenshot_20220828-141421_Kiwi Browser](https://user-images.githubusercontent.com/50764666/187058688-88dfd906-70f6-41c2-8e8e-e890bf5141cb.jpg)

example link) https://bafybeiedv7sowwxamly4oicivudp45rsfvbklnf3fvbvonxrwoxqylhtwq.ipfs.w3s.link

it should be returned normally even if refreshing 3-4+ times

**Comment by vasco-santos** [comment]
Hi @aeongdesu 

Can you provide us more details? What browser are you using and how are you refreshing?

I was not able to replicate this behaviour. Also worth asking if you are performing a lot of requests from same IP, as this could be hitting rate limit on 200req/min?

**Comment by aeongdesu** [comment]
@vasco-santos, I'm using Kiwi Browser 105.0.5195.32, and device is Samsung Galaxy Note10+.
I don't think the ratelimit will be reached, also i tested on mobile data with kiwi browser and firefox nightly:

https://user-images.githubusercontent.com/50764666/187164966-ac7a9645-c7a7-4661-9fa6-d123c121cb30.mp4

**Comment by vasco-santos** [comment]
Thanks for the reproduction video. This should likely be related to the caching headers we add for client browser to keep the response cached. I will need to dig deeper into Kiwi browser to try to see what is happening there.

**Comment by vasco-santos** [comment]
@aeongdesu I just tried Kiwi browser 105.0.5195.32 on my device and could not replicate. Could you try in Chrome on your end?

**Comment by aeongdesu** [comment]
it's working now. 👍
