### ISSUE TITLE
Web3storage repo - Switch to a organisation-wide Cloudflare token in GH

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1815]
For maintenance sake and develop experience, we'd like to switch to org-level GitHub secret for Cloudflare token for the web3.storage organisation.

Once done, we can/should remove the `CF_API_TOKEN` secret from the individual repo's secrets.

**Comment by mbommerez** [comment]
PR to switch to org level token has been merged, not deployed.
Waiting for confirmation from @hugomrdias that the `CF_API_TOKEN` secret has been deleted from this repo's secrets.

**Comment by hugomrdias** [comment]
its gonna! we still have CLOUDFLARE_PAGES_API_TOKEN for some reason can you look into it please ?

**Comment by mbommerez** [comment]
thanks Hugo, we will look into this.

**Comment by francois-potato** [comment]
@hugomrdias `CLOUDFLARE_PAGES_API_TOKEN` and `CLOUDFLARE_ACCOUNT_ID` are used by `wrangler` for publishing staging and production websites.

If `CLOUDFLARE_PAGES_API_TOKEN` is the same as the new `CF_TOKEN`, we can remove `CLOUDFLARE_PAGES_API_TOKEN` and update the [GH action](https://github.com/web3-storage/web3.storage/blob/main/.github/workflows/website.yml). Is `CLOUDFLARE_ACCOUNT_ID` at the org level?

**Comment by hugomrdias** [comment]
yes its `CF_ACCOUNT_ID` and please update the gh action 
thank you

**Comment by francois-potato** [comment]
Thanks @hugomrdias; updated in https://github.com/web3-storage/web3.storage/pull/1848
