### ISSUE TITLE
Application error while viewing uploaded via pinning api files in file browser

### ISSUE THREAD

**Issue by michaelnguyenm** [web3-storage/web3.storage#1817]
Currently I get this error when I look at the file browser for my account after I click on the button for `Uploaded via Pinning API`.
![brave_2022-08-30_15-38-09](https://user-images.githubusercontent.com/8785414/187567079-10094bb2-1fd9-4974-9af6-bace893a0c2e.png)

In my browser console, I just get:
![image](https://user-images.githubusercontent.com/8785414/187568307-585939fc-078b-47fc-af9a-95bce45e4f3b.png)

Looking in my network requests, I see one made to `https://api.web3.storage/pins?status=pinned`
And I notice there are a couple of null values for the `results` (`pin.name`, `pin.meta`, `pin.pins.region`), maybe that's the issue?

If providing the json response will help, I can do that. For context, I only recently requested these pins via the API, so they may still be in the process of replicating/being processed. So I figure that it may resolve itself eventually but not really sure what this bug is specifically being caused by.

**Comment by mbommerez** [comment]
Thanks for posting this Michael, we'll have a look into this.

**Comment by joshJarr** [comment]
Thanks Michael. We've just made some changes to this section of the site, are you still able to replicate this issue?

**Comment by michaelnguyenm** [comment]
I was able to see the pins without any issues! Thanks a bunch!

Just one thing I noticed was the request appears to have changed from only requesting `pinned` status pins to all of the statuses but I guess that is more intentional since people are expecting to see all of their pins regardless of status.

**Comment by mbommerez** [comment]
Thanks Michael, that's great news!

And yes, that was intentional.
