### ISSUE TITLE
Gateway Time-out for car access

### ISSUE THREAD

**Issue by qdwang** [web3-storage/web3.storage#1819]
Recently I always encounter the **Gateway Time-out** issue when accessing the uploaded CAR content though the `https://api.web3.storage/car` API.

The CAR file is here -> [generated.car.zip](https://github.com/web3-storage/web3.storage/files/9461334/generated.car.zip)
The hash algorithm is `Blake2b`.
The block size is 256k and the root cid is `bafykbzacedhgyskynjhpndqungmzmpwqeiwrj5lhruucx3cgyqfcfntxgfvuy`.

After uploading the CAR file for several hours, accessing [https://w3s.link/ipfs/bafykbzacedhgyskynjhpndqungmzmpwqeiwrj5lhruucx3cgyqfcfntxgfvuy](https://w3s.link/ipfs/bafykbzacedhgyskynjhpndqungmzmpwqeiwrj5lhruucx3cgyqfcfntxgfvuy) will still return the **Gateway Time-out**.

My web3.storage account is just linked with this my Github account.

**[update]**
It's available now, it seems to take more than 8 hours to pin the CAR file. But i don't know why uploading file directly from `https://web3.storage/account/` page can instantly make the cid accessible for users?

**[update 2]**
After changing the hash algorithm to the `SHA2 256`, this issue disappears. Every CAR digested with `SHA2 256` will instantly be accessible after the uploading.

So I guess the backend server might be lowering the priority of the Blake2b cid blocks?

**Comment by hsn10** [comment]
Its normal that upload sometimes takes a while to become online - about tens of minutes. 

I use blake2b-256 and it works fine.

**Comment by qdwang** [comment]
All right, I'll test it again.
