### ISSUE TITLE
Implement the new /user/pins end point in FE

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#1830]

**Comment by joshghent** [comment]
Looks like this has already been done

**Comment by joshghent** [comment]
Already completed in this commit: https://github.com/web3-storage/web3.storage/commit/2ffe6d749628095a93d957836c6b4e8ad3b6acf9

**Comment by mbommerez** [comment]
@joshghent Do you mean this is part of the changes that went with https://github.com/web3-storage/web3.storage/pull/1739 (which is deployed in prod) ?
So we are now using /user/pins end point in production?

**Comment by joshghent** [comment]
@mbommerez Yes!
