### ISSUE TITLE
Ensure the new uploads table component is styled correctly for all instances

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1834]
There's a new shiny uploads table component included with [this PR](https://github.com/web3-storage/web3.storage/pull/1700) 
We should ensure the styling of this component aligns with the designs and that the designs for for each instance of the table.

**Comment by mbommerez** [comment]
Table styling in a good state, few minor things/tests to do once the previous ticket is done.

**Comment by joshJarr** [comment]
Closing as this should now be fixed as part of https://github.com/web3-storage/web3.storage/issues/1961
