### ISSUE TITLE
FE - Upload & Pins file manager table refactor

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/web3.storage#1836]
There's been a few issues related to the uploads and pins tables.

- Pagination code is tough to work with since there are many components changing data, and Upload and Pin logic is tightly coupled.
- There's some inefficiencies in calls, sometimes the table is loaded before requesting pins, resulting in content jumping shortly after loading
- when "View results" is change when on page 2 or more and causes the request to be out of range the table breaks. Refreshing does not fix this as the url params persist the broken state.
- Pins cannot be sorted
- We have lost pagination counts (only get prev, next, first, last), a user cannot jump to a page beyond these.

**Comment by mbommerez** [comment]
Closing this as it's covered by other smaller tickets.
