### ISSUE TITLE
Profile + Token Page UX / UI Improvements

### ISSUE THREAD

**Issue by jnthnvctr** [web3-storage/web3.storage#186]
1. When creating a new token make the default width of the third column large enough so "Copy" -> "Copied!" does not change the width of the column (and shift the API key around on the page)

![image](https://user-images.githubusercontent.com/21000523/127043837-09b9eef9-7946-4c14-814b-f73f0e5ba60f.png)

2. When you have no tokens created on the "Tokens" page, keep the "API Tokens" header anchored on the left. 

![image](https://user-images.githubusercontent.com/21000523/127044228-207d39ef-f7e6-467d-abee-b37bb2fbc029.png)

3. On the Profile page, when there are no tokens hide the "API tokens" section (Including the Manage your tokens, Create a new token button, etc). Just surface the "Getting Started" cards. Once a token has been created, hide the "Create your first API token" card.

**Comment by jnthnvctr** [comment]
- [ ] Adjust a minimum width of the table on the "Tokens" page such that clicking Copy does not shift the table around
- [ ] Keep the API Tokens header anchored on the left when there are no tokens on the Tokens page (the state you'd be in if you deleted your last token)
- [ ] Conditionally show the API tokens section on the Profile page only when at least one token exists. When no tokens exist, only show the "Getting Started" cards

**Comment by dchoi27** [comment]
@jnthnvctr can we close this?
