### ISSUE TITLE
Performance UX feedback 

### ISSUE THREAD

**Issue by jnthnvctr** [web3-storage/web3.storage#187]
1.  Pin status - when a user uploads a file, why is the pin status not immediately set as pinned? Users can get a URL showing something is in the gateway - seems like this should also be reflected as being pinned. If we need default text, we can say queued - but we should want this to reflect the pinned status basically immediately. 

2. Page loading when returning - when navigating around the page it seems that the "state" requires a refresh (perhaps this is a magic link thing)? Is there a way of avoiding this for users - it seems like you get this little loading screen if you're away from the page for a few minutes and come back

**Comment by jnthnvctr** [comment]
- [ ] Pin status - can we get this to update immediately as soon as an upload is complete? 
- [ ] Avoiding a reload of state when a user is away from the page for a few minutes

**Comment by atopal** [comment]
- [ ] Logging in using Github takes a very long time with little feedback, should either show a message or be faster.

**Comment by olizilla** [comment]
Please check for exising issues before creating new ones. This feedback is helpful, and goes with the epic where I'm collecitng perf related issues #94

**Comment by alanshaw** [comment]
I've added @atopal's feedback to #94. The issues @jnthnvctr raised originally have been addressed in https://github.com/web3-storage/web3.storage/pull/192 and https://github.com/web3-storage/web3.storage/pull/196
