### ISSUE TITLE
UI flows / views for different user states

### ISSUE THREAD

**Issue by gobengo** [web3-storage/web3.storage#1879]
New user versus legacy user views to support different flows

List of possible flows (product needs to revise and finalize):
- [ ] Registered user but logged out coming from any pricing cta links (like homepage)
- [ ] Unregistered user coming from any pricing ctas
- [ ] Logged in user viewing coming from pricing ctas
- [ ] Logged in user (or logged out user) with subscription coming in from link on storage notification email
- [ ] Logged in user with subscription wishing to cancel
- [ ] Logged in user with subscription wishing to upgrade.

**Comment by gobengo** [comment]
Does this have separate scope from https://github.com/web3-storage/web3.storage/issues/1869
@cmunns @JeffLowe ?

If not, lets close this in favor of that

**Comment by JeffLowe** [comment]
This is more of an epic, recording the need for identifying and building for the various user state flows.  States like:
*Registered user but logged out coming from any pricing cta links (like homepage)
*Unregistered user coming from any pricing ctas
*Logged in user viewing coming from pricing ctas
*Logged in user (or logged out user) with subscription coming in from link on storage notification email 
*Logged in user with subscription wishing to cancel
*Logged in user with subscription wishing to upgrade.

**Comment by gobengo** [comment]
@JeffLowe Okay. Can you turn those into checkboxes and track them then? I created this issue from a corresponding item on the project board, but I don't actually intend to shepherd this.

**Comment by gobengo** [comment]
I think the exact designs of those states are going to change over time as we iterate, so it might be hard to track when all of them are done in one ticket.
