### ISSUE TITLE
Querying status doesn't work

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#190]
During testing none of the participants was able to query the status of a file programmatically. The status was always "undefined". It's not clear that that is an issue with the docs or the API. If that's expected behavior, because the files had not been pinned or stored yet, we might want to update the API to provide a more useful response.

**Comment by terichadbourne** [comment]
@atopal Could you please confirm which docs they were referencing when attempting this? I'd love for @olizilla or  @alanshaw or @vasco-santos to follow our instructions and then tell us what's wrong with them (or confirm an expected delay, problem with API, etc.) to get clarity on the changes needed in the sister issue web3-storage/docs#64.

**Comment by alanshaw** [comment]
We need to know the CIDs that were being used in order to debug.

**Comment by terichadbourne** [comment]
@atopal @jessicaschilling Are these [the instructions](https://docs.web3.storage/how-tos/query/#querying-for-status-information) that were being followed by testers when it didn't work? If so, were they using their own files and CIDs when testing as opposed to pasting the example CID that's there? 

I assume this is either: 
A) The API is genuinely broken, in which case it won't matter what file we test with
B) There's a delay before status works that's expected by everyone on the Spark team but not by us or our users that we've failed to explain, in which case we'd get the same delay with any test file (maybe differing based on size) and could update the description to set better expectations
C) We wrote the instructions wrong, in which case it won't matter what file we test with

@alanshaw Are you game to skim through that section to see if there's an obvious flaw in our docs before we try to scrounge up specific CIDs to test?

**Comment by jessicaschilling** [comment]
@terichadbourne Can confirm those were the instructions they were using. Unfortunately, can't confirm they were pasting in correct CIDs (screen share was small for me, because I was also taking notes), but am pretty certain that was the case.

**Comment by alanshaw** [comment]
Maybe people were not using the root CID? It only works with the root CID you get back from `.put`.

**Comment by olizilla** [comment]
Definitely interesting that no one could use it. I've a tweak for the docs described here, https://github.com/web3-storage/docs/issues/87 but it shouldn't have prevented anyone from using it.
Perhaps their client was pointing at the production api rather than staging?

**Comment by alanshaw** [comment]
I just watched discordian's video. The [quickstart](http://docs.web3.storage.ipns.localhost:8080/#create-the-upload-script) currently references the staging API but the [docs for querying status](http://docs.web3.storage.ipns.localhost:8080/how-tos/query/#installing-the-client) do not.

This is almost certainly because the production API was being asked about a CID of an upload that was performed via the stating API.
