### ISSUE TITLE
Phishing website on w3s.link

### ISSUE THREAD

**Issue by InfobloxFSAT** [web3-storage/web3.storage#1904]
Hello, 

I am contacting you to report an account, which appears to be abusing your web hosting services. One of your users has created a fraudulent website, and we would like for you to investigate and suspend this account once you confirm our report.

https://bafybeigdwq36cyx2uvgoxu4dh6iipjie4vsch7nf4ahgzr32pbnzgxndjm.ipfs.w3s.link/alphash_cham-e2.html#bWVyamEtaGVsZW4ubGVodGluZW5AY2Vuc3VzLmdvdg==

104.18.22.52

If you have any questions, or require additional information, please contact me via the information below.

Regards,

Infoblox Federal Security
Incident ID: 68076
infoblox.com
Email: fraud_alert@infoblox.com
1-253-590-4100

**Comment by dchoi27** [comment]
Thanks for the info, forwarding this over to https://badbits.dwebops.pub/
cc @vasco-santos

**Comment by vasco-santos** [comment]
Hi @InfobloxFSAT 
Thanks for reporting. We just added this to badbits to be blocked by all IPFS gateways who subscribe to this list.
