### ISSUE TITLE
Fraud Accounts on w3s.link Services

### ISSUE THREAD

**Issue by johnburns1987** [web3-storage/web3.storage#1941]
Hello, 

I am contacting you to report two accounts, which appear to be abusing your web hosting services. The following URLs are resolving to active phishing pages:

https://bafybeiceuontqknyaghth7s64bcuilxevpbcf7ti3ux2ww75jkzdfmcvea.ipfs.w3s.link/siboil.ll_owa1.html#mark.ferguson@sba.gov

https://bafybeieil5elm7ju5tlpmzwhoommgvsjeluzwxyub3t33r7mfc76boe27i.ipfs.w3s.link/free.nazi_cham-ex.html#ZXJkLm1lY3MuZWJsYXN0QGNlbnN1cy5nb3Y=

104.18.22.52

If you have any questions, or require additional information, please contact me via the information below.

Regards,

Infoblox Federal Security
Incident ID: 68165
infoblox.com
Email: fraud_alert@infoblox.com
1-253-590-4100

**Comment by vasco-santos** [comment]
Thanks for the report @johnburns1987 . We blocked the malicious content from being served on the IPFS Gateways
