### ISSUE TITLE
Website: social media preview not rendering

### ISSUE THREAD

**Issue by meghansinnott** [web3-storage/web3.storage#1984]
The social media preview for web3.storage is not rendering.
![SocialMediaPreview](https://user-images.githubusercontent.com/45804536/193354291-e93a6f94-9ac3-49dc-ae88-4ffdbcd426b4.jpg)

**Comment by JeffLowe** [comment]
Thanks for the repot. Looks like the full route for the og image is not getting insert.  We'll get that fixed.

**Comment by meghansinnott** [comment]
@e-schneid the issue persists on for blog links. Is this something that can be fixed?

**Comment by jchris** [comment]
Here is an example of not working

<img width="625" alt="Screen Shot 2022-10-21 at 9 58 33 AM" src="https://user-images.githubusercontent.com/253/197249416-f1b08b82-1f3a-4efb-8e8d-5997dbbe2876.png">

https://twitter.com/Web3Storage/status/1583487397924605952?s=20&t=GPOpzxY-QypRSX2wdtbM6A

**Comment by e-schneid** [comment]
It's now in PR to fix this on the blog.

**Comment by meghansinnott** [comment]
@JeffLowe, @e-schneid, @jchris  - the preview is still not showing for the web3.storage blog when I share via Twitter.

**Comment by cmunns** [comment]
@meghansinnott I've done some testing on this and it appears that on the home blog url the preview only works if you add a trailing slash. I've confirmed that the twitter card meta tags are all present and correct and we aren't missing any optional settings that would help rectify this issue but at least we have a solution on how to fix. 

https://user-images.githubusercontent.com/1189523/203121198-fd04f1b4-f0ad-479b-a7a7-70e4a457b054.mov

**Comment by meghansinnott** [comment]
That's wonderful! Thank you, Adam!

**Comment by meghansinnott** [comment]
@cmunns - Sorry to report that the trailing hash hack isn't working. 
![TrailingHash](https://user-images.githubusercontent.com/45804536/205403449-b5967cfa-d356-48f2-ae72-4b5a1f9040c0.jpg)
