### ISSUE TITLE
Doubt about CID generated with web3.storage in IPFS

### ISSUE THREAD

**Issue by damianlluch** [web3-storage/web3.storage#1986]
Hi, I have been integrating your library and it has been very easy to work on the use case I needed, which was to upload all the files in the same folder.
However, the CID that you provide me with, if I take it to another site to verify it, it does not appear.
Where can I verify the CID generated by you on a site that is not yours?
Thanks

https://bafybeifxicud4le4zm44aypwl2qhsdxapwfb524yttunxpyzyyl4fl3mwa.ipfs.w3s.link/

**Comment by dchoi27** [comment]
What do you mean "if I take it to another site to verify it, it does not appear"? 

CIDs are generated client side using https://github.com/web3-storage/ipfs-car, you can verify the code yourself
If you're just looking to fetch the CID from another public gateway, just use this list https://ipfs.github.io/public-gateway-checker/
e.g. https://bafybeifxicud4le4zm44aypwl2qhsdxapwfb524yttunxpyzyyl4fl3mwa.ipfs.dweb.link/
