### ISSUE TITLE
I cant pay im getting: failed to get/put user billing info: {}

### ISSUE THREAD

**Issue by Shuberth** [web3-storage/web3.storage#1987]
Hi, i cant finalize a new payment ussing my credit card, im  getting this: failed to get/put user billing info: {}

**Comment by dchoi27** [comment]
Hey, are you doing this in the website? Mind trying again to see if the problem persists?

**Comment by alanshaw** [comment]
@gobengo have you seen this before?

@Shuberth is your github account the account you're signed in with and trying to add payment (just so we can look you up and see what happened)?

**Comment by heyjay44** [comment]
The issue has been resolved in PR #1988
