### ISSUE TITLE
Abuse of the w3.link domain. Create a form for reporting on website w3.link please. 

### ISSUE THREAD

**Issue by AJRepo** [web3-storage/web3.storage#2008]
Hello, 

Abuse of the w3.link domain to send phishing attacks. Looking at your website at https://web3.storage/faq/ there is no way to report issues - a concern for the vast majority of email users who have no github accounts. Request the following

1. Have a method for abuse reporting on the w3.link domain for users who are attacked and do not have a github account. 

2. Block https://  (spaces added to block markdown linking)   bafybeiak672bwkqsiubjzh636ak5ehkalxautezzooh54khbxdzkjb7bli.ipfs.w3s.link/henryr_cham-e2.html#REDACTED@REDACTED  which was sent by mail server 198.252.107.205

> Log: Received: from id-001zimlets.firewall-gateway.de (unknown [198.252.107.205])
> 	by REDACTED (Postfix) with ESMTPS id 60C671A3C37
> 	for <REDACTED@REDACTED>; Thu,  6 Oct 2022 07:48:19 -0500 (CDT)
> Received: by id-001zimlets.firewall-gateway.de (Postfix, from userid 33)
> 	id 19642D2564; Thu,  6 Oct 2022 11:25:56 +0000 (UTC)

Thanks in advance

**Comment by vasco-santos** [comment]
Hi @AJRepo 

Thanks for reporting this. First of all, provided content was blocked from our gateway. 

Good catch, thanks. Created a PR to add a method to report abuse in our TOS #2013

**Comment by vasco-santos** [comment]
Closing this given the reporting email is now on ToS. Thanks @AJRepo
