### ISSUE TITLE
Ensure web analytics receives needed KPI data & prototype dashboards

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#2030]
Initial request was to vet and ensure Countly analytics system was connected throughout sites.  However, decision was made to move away from countly and find/use an alternative.  Plausible and Simple are being vetted.  One should be selected and used. 
Eg current Countly Metrics ([https://countly.ipfs.io/dashboard#/60fe7ce4d7c3b807836603d7/](https://countly.ipfs.io/dashboard#/60fe7ce4d7c3b807836603d7/))

- [x] vet Plausible analytics
- [ ] vet Simple Analytics
- [ ] ensure we use a Dag.House account (opposed to  a protocol labs account)
- [ ] Ensure this Data is present in analytics system so that it can be easily tracked
        - Heaviest web traffic sources
        - Time spent on docs
        - Blog post visits / time spent on post
        - Blog subscriptions

- [ ] Ensure we are capturing the data for, and the following funnels are clear in report
        - Conversion / churn from new users landing pre-login and creating account (also should include time to create account)
        - Conversion / churn rate for new users from pre-login pricing page to creating account to putting in their credit card to signing up for a plan

- [x]  Resolve Weird buggy things (likely requires ensuring that cta's pass more info into countly to clearly label what was clicked...at minimum)
        - What are the steps in this funnel? [[https://countly.ipfs.io/dashboard#/60fe7ce4d7c3b807836603d7/funnels/detail/59297a90c81b7c19b27c63c0a6620079/{}](https://countly.ipfs.io/dashboard#/60fe7ce4d7c3b807836603d7/funnels/detail/59297a90c81b7c19b27c63c0a6620079/%7B%7D)](https://countly.ipfs.io/dashboard#/60fe7ce4d7c3b807836603d7/funnels/detail/59297a90c81b7c19b27c63c0a6620079/%7B%7D)
- [ ] create minimal dashboards in analytics system displaying above KPIs so others can go in and know how to build the ones they need.

**Comment by JeffLowe** [comment]
@dchoi27 Do we also need to build out minimal dashboards in Countly, or  just ensure the data get's into Countly correctly so it can be used/referenced?

**Comment by dchoi27** [comment]
minimal dashboards would be appreciated so others can go in and know how to build the ones they need to (sometimes the tag names are hard to decipher)

**Comment by JeffLowe** [comment]
Did preliminary check in Countly, now doing checks in codebase.  Getting Adam on this while Johnathon finishes up a larger item on blog.  Things are moving forward on this.

**Comment by cmunns** [comment]
Prelim thoughts for moving forward. So far as I can tell the only code updates would be to add/update the new blog repo with countly tracking which would automatically track blog post visits / time spent on post ?

We'd need a custom event for blog subscription form.

The funnels need to be created/configured in countly for understanding churn, order of events does matter here. The one existing funnel for Signup/Log in isn't working simply because the final step is measuring success for a /profile page but we need it to check for /account page instead.

**Comment by dchoi27** [comment]
checking in here!

**Comment by dchoi27** [comment]
checking in here!

**Comment by cmunns** [comment]
Let me follow up, I think countly recently got added to the blog. Will report back.

**Comment by cmunns** [comment]
After vetting Plausible a bit its obvious that it isn't feature rich enough for this task. There is no ability to create funnels or even complex goals without hacking it in a way that would be too difficult to extract data from. 

I have found a similar solution called Simple Analytics and am vetting that now as they have more robust events with a similar base feature set. They are also launching a redo of events next month that should give us exactly what we need and is also testable via localhost and with domain sharing (blog vs www). Here is the feature sample https://twitter.com/adriaanvrossum/status/1589672095705096192?s=46&t=ftrx4z1xSJ9RYuPStiX6iA

**Comment by JeffLowe** [comment]
Updated the spec in the description to reflect what's currently needed here.  Countly has been eliminated as option, as well as Plausible.  Simple Analytics is currently being vetted.  @cmunns let us know here what you find and when you determine whethere or not Simple Analytics will meet our needs.
