### ISSUE TITLE
Storage calcuation timing out in web3.storage account dashboard

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#2033]
Storage calculation in the dashboard section of web3.storage is timing out in Production, but it is not in Staging. 

Behaviour: it gets stuck on loading for multiple minutes and then it displays 0.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/93770197/195878108-96491bcd-5874-4fbe-870f-223cdb3c26dc.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/93770197/195878028-b373b9b1-9226-43ca-89e1-fa67ba7ffa8b.png">

**Comment by heyjay44** [comment]
@cmunns could you take a look at this, please?

**Comment by JeffLowe** [comment]
@heyjay44 could also have Drew take a look.  he was looking into another likely related issue #2044

**Comment by drewdelano** [comment]
![image](https://user-images.githubusercontent.com/22156330/197892552-10d6585b-a1be-4b31-bb48-e5a89aa362f9.png)

**Comment by mbommerez** [comment]
Discussed between @vasco-santos and @flea89 
PR created by Vasco: #2069
