### ISSUE TITLE
Remove "Web Apps" link from the website footer

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2067]
We no longer need the "web apps" link in the footer.  we need to remove it. 
- [ ] remove from all footers (website, docs, blog, etc)

Right now, it takes you to the Terms of Service page.

<img width="1053" alt="github" src="https://user-images.githubusercontent.com/5795335/198000649-1a80f30a-4987-4f55-9add-53d01afa2cd0.png">

**Comment by JeffLowe** [comment]
@heyjay44 Where is the intended target of "Web Apps"?  Just need a url and we'll get it updated.

**Comment by JeffLowe** [comment]
Confirmed with @dchoi27 in slack, we should just remove this from all footers.

**Comment by JeffLowe** [comment]
Closed with #2087
