### ISSUE TITLE
Serve website from our own gateway

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#208]
Currently we host on the public ipfs.io gateway. We're pinning our website to our cluster, so we could host it from their too, but using the storage cluster as a gateway node is undesirable as we'd want to load balance, and could end up pulling pinned content onto more nodes than the replication factor. Instead we're going to set up our own dedicated gateway nodes and host it from there.

TODO
- [x] create dedicated gateway in Piñata
- [ ] create dedicated gateway in our infra for redundency
- [x] peer all cluster nodes with all gateway nodes.
- [ ] update DNS for web3.storage and staging.web3.storage to point to new gateways.

**Comment by atopal** [comment]
related: https://github.com/web3-storage/web3.storage/issues/138

**Comment by dchoi27** [comment]
Could #382 be related?

**Comment by olizilla** [comment]
@dchoi27 i don't think so. the error message in #382 comes from the graphql endpoint on Fauna.

**Comment by olizilla** [comment]
We're not able to use the Pinata gateway for dnslink based hosting of our websites, as it is not currently supported.

**Comment by dchoi27** [comment]
Should we close this given #435 has been merged?

**Comment by atopal** [comment]
We're serving HTTP from cloudflare pages now, so this is no longer needed.
