### ISSUE TITLE
Phishing URL still active 4 days after report

### ISSUE THREAD

**Issue by InfobloxFSAT** [web3-storage/web3.storage#2080]
Hello,

Infoblox has been made aware of a hacked website under your control that is hosting a live phishing website.

https://bafybeihce3tglv7stlocseqo2uzov2b3r27ok5t5xhbnj5s4jlcbq3v4gu.ipfs.w3s.link/onedriveob5.html/?james.vinson@sba.go

IP: 104.18.41.121

We are requesting that you immediately investigate and suspend this content as soon as possible to prevent continued theft of this private information. Additionally, as the result of this page is likely the result of a compromise, it is important that additional security measures are taken to prevent reentry by the hackers.

Please do let us know if you need additional data, have any questions, or wish to confirm removal of the illicit contents.

Thank you for your time and efforts.

Best regards,

Infoblox Federal Security Analysis Team
infoblox.com
Email: fraud_alert@infoblox.com
1-253-590-4100

**Comment by vasco-santos** [comment]
Hi @InfobloxFSAT 

Where did you report this too? I am not aware on this report, please next time If you encounter content that violates the [Terms of Service of IPFS.io](https://discuss.ipfs.io/tos)(e.g., spam/phishing content or your unauthorized copyrighted content), please reach out to abuse@ipfs.io

I am getting the given CID to our denylists for operated IPFS Gateways

**Comment by InfobloxFSAT** [comment]
We have sent three emails to 
support@web3.storage, abuse@ipfs.io, security@ipfs.io

**Comment by vasco-santos** [comment]
Thanks for making the effort to guarantee it is taken down.

Did the email made it to us? Sometimes these emails get blocked by mail providers and you get a response saying it. The workaround is encoding a bit the url like:

```
hxxps://bafybeihce3tglv7stlocseqo2uzov2b3r27ok5t5xhbnj5s4jlcbq3v4gu.ipfs[.]w3s[.]link/onedriveob5.html/?james.vinson@sba.go
```

**Comment by vasco-santos** [comment]
It is now blocked in w3s.link, nftstorage.link, dweb.link and ipfs.io

It might still be cached on your client for a bit
