### ISSUE TITLE
looking for a better tutorial for web3.storage -- specifically how to w3name 

### ISSUE THREAD

**Issue by nin-j** [web3-storage/web3.storage#2096]
I feel the tutorials in **web3.storage** and **nft.storage** are lacking ... web3.storage should have simpler, easier to follow tutorials for lay people. I have been able to upload files to web3.storage using js but i'm completely lost following w3name (ipns) tutorials. Any assistance would help tremendously ... spent many days without success

**Comment by yusefnapora** [comment]
Hi @nin-j, thanks for reaching out. I've started outlining a w3name tutorial, but I haven't had time to flesh it out yet, and realistically it may take a few more weeks before I can wrap it up. In the meantime, if you have a minute to write up the biggest pain points / stumbling blocks that you encountered, that would help me to make sure I'm covering the right stuff.

I'm also available on [Filecoin slack](https://filecoin.io/slack) as `@yusef` if you want to send me a ping; hopefully I can help get things working.
