### ISSUE TITLE
How to check for filename through content ID (CID) 

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [web3-storage/web3.storage#2097]
if my assumption is correct, we can't really see the actual filename with `w3 list <CID>` command

and it gets even more confusing if you are sending the CID to someone, they don't know the actual name of the file **until it is downloaded**

can you add an API command that will allow us to see the actual filename, just by using the CID ?

**Comment by alanshaw** [comment]
@SyedMuhamadYasir do you have an example? What do you mean by "downloaded" - viewing via an IPFS gateway or something else?
