### ISSUE TITLE
lot of time is taken to get response from 'https://w3s.link/ipfs/<CID>' url after upload of file

### ISSUE THREAD

**Issue by Dygnify** [web3-storage/web3.storage#2100]
Steps to reproduce
1. Upload any file and get the cid of that file (we use SDK for the upload of files to web3.storage, though it should not matter)
2. try to access 'https://w3s.link/ipfs/cid' url in browser

Actual result: It takes lot of time to get response and most of the times request gets timed out
Expected: request should not timeout and provide response quickly

**Comment by vasco-santos** [comment]
Hi @Dygnify 

Changes we did recently should make this really fast (if data is stored in web3.storage, so using our SDK actually matters)

Can you give me more information about the files you are uploading? 
- how big are the files? (most of the issues I see like these end up being problems with the actual upload not being completed)
- can we get a CID for them?
- can you let us know what region of the world the request is being made?
- is this previous experience, or current experience? (we landed something to improve this experience a couple of weeks ago)

**Comment by Dygnify** [comment]
@vasco-santos this is linked to the previous issue that i raised https://github.com/web3-storage/web3.storage/issues/1810

as per your suggestion, we are trying to do fetch with w3s.link url formation.
So first we try to get the file using SDK if that fails then we try accessing file using your recommended method, but that also takes lot of time.

use case is simple, upload any file and then try to get it immediately after receiving cid with either method SDK or w3s link
and this happens with small size files also

**Comment by vasco-santos** [comment]
can you give us metrics on how slow it is?

Looking at https://github.com/web3-storage/web3.storage/issues/2061 , this writes and immediately tries to read. Looks like it is reading ok every time

**Comment by Dygnify** [comment]
it seems like getting file from SDK is taking time, and after your suggestion, we took a hybrid path where we trying to get files with the SDK option first and if that fails then we were fetching file using w3s mode
