### ISSUE TITLE
w3s link works on some computer and doesn't on some

### ISSUE THREAD

**Issue by Dygnify** [web3-storage/web3.storage#2109]
Following url works on some computers but doesn't work on some
 https://bafkreihyplrv4jjmuqoqqisxbebccvbtvo4utl6ctb4c63ina63lmp4syi.ipfs.w3s.link/

what could be the reason?
we are 5 people team and this works on 2 people's computer and doesn't work on 3 but interestingly it works fine on each one's mobile

**Comment by vasco-santos** [comment]
Hey @Dygnify 

Could you get this fixed? IF not, can you please give us more details?

**Comment by vasco-santos** [comment]
Closing this issue given it might be unblocked by ISP by now. If still not the case, please let us know what ISP is blocking w3link
