### ISSUE TITLE
Determine and refine source of truth for pricing information

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2119]
Discussion [here](https://www.notion.so/Source-of-truth-json-stripe-ceab6509ff734eba817ed33bdd253129)

Desire is for Stripe to become the source of truth for all pricing/products. 
Possible approach is blended.  Have the standard prices in the repo (to avoid overfetching), and only fetch ffrom stripe if there are non-standard prices.

**Comment by drewdelano** [comment]
Looking through the Stripe APIs it looks like it's pretty easy to list the subscriptions:
https://stripe.com/docs/api/subscriptions/list

Or search through them if we only want to look at a subset:
https://stripe.com/docs/api/subscriptions/search

That would give us the ability to actually look them up in Stripe, but Stripes fault tolerance and latency may not line up with what we want to do.

I assume the basic flow would be:
1. Setup a job that, towards the end of the month
2. Using SQL, search all (active?) users 
3. Match them to their customer records by calling Stripe's customer API: getOrCreateForUser
4. Before all of this, we should probably store Stripe's subscription information about each client in the DB's user record.  That way we can...
6. Calculate the storage amount that the user has used
7. Subtract their plan's base storage amount
8. Calculate the overage fees
9. Add a separate non-recurring cost to their subscription for the overage fees (I can't tell if Stripe is smart enough to automatically bill for a price if it's not recurring, but the data/price has been updated, probably worth investigating)
