### ISSUE TITLE
Account limits - Handover

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#2123]
Create an handover doc for Acoount Limiting feature

As part of this I've created a [PR](https://github.com/web3-storage/web3.storage/pull/2124) to add an option to run the cron job in prod without sending real emails

**Comment by flea89** [comment]
Link to [draft](https://www.notion.so/Account-Limits-Handover-1cc6b6669d174e5ba3e0e8ce866fbdfb)

**Comment by adamalton** [comment]
This looks really good. I've basically just fixed a few typos and added the odd sentence or two to clarify things.

**Comment by adamalton** [comment]
Assigning to @mbommerez to find out where this page should be moved to in the PL Notion and get it moved.

**Comment by mbommerez** [comment]
This has been moved here: https://www.notion.so/Account-limits-07b8e95b62814fe9abe02994c1d1de4a in the handover notes.
Closing ticket.
