### ISSUE TITLE
write script to add migrated user custom prices to Stripe

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2127]
We need to automate price creation so that the groups outlined [here](https://www.notion.so/Early-Adopter-to-Custom-Plan-Requirements-6d39bbb145ef4106ad00febcaf02b94c) are reflected in the dashboard.

**Comment by JeffLowe** [comment]
Script is written.  Closing as complete.  
Will ticket separately if we need to modify it further
