### ISSUE TITLE
Store necessary pricing and user id data in json

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2128]
Make json object in repo to connect user and price IDs. This will allow for efficient linking of user to prices through price IDs. These prices will have been previously populated in this [ticket](https://github.com/web3-storage/web3.storage/issues/2127). 

needs #2127

**Comment by JeffLowe** [comment]
may instead use tag within stripe to identify and lookup

**Comment by e-schneid** [comment]
@heyjay44 @JeffLowe , I don't believe this ticket is relevant anymore since we're going to assume that users already have a Stripe customer before we run our script.  We'll create the price and link these customers to those prices simultaneously.

**Comment by heyjay44** [comment]
@e-schneid correct, good catch!
