### ISSUE TITLE
pull actual price data (including custom) and display in UI

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2129]
For custom users with new stripe subscriptions, we need the details of their plan to be displayed in the UI of the payments and accounts page. Please find the UIs sketches [here](https://www.notion.so/UIs-for-custom-plans-post-migration-df237239d19049e999e2284478ed372d)

- [x] ability to pull data from stripe
- [x] pulling and displaying data in the actual UI

**Comment by JeffLowe** [comment]
blocked until we have clear spec on what UI should show (what fields, labels for pricing level, migration group specifics...show or not show tiers)

**Comment by e-schneid** [comment]
@JeffLowe @heyjay44 we could attach this ticket to [this PR](https://github.com/web3-storage/web3.storage/pull/2152) (which allows pulling and displaying price data from Stripe) and create separate tickets for functional and cosmetic UI changes so they can be assigned to @drewdelano
