### ISSUE TITLE
pinning service API needs to reject IPLD codecs we don’t support

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2154]
- pinning service API needs to reject IPLD codecs we don’t support (for both web3.storage and NFT.Storage)
-  document that we support remote pinning the following codecs raw dag-json dag-cbor dag-pb in the root node and outside of that, we’ll reject (here https://web3.storage/docs/how-tos/pinning-services-api/ and https://nft.storage/docs/how-to/pinning-service/)
- also add to the API reference docs of each
- easiest way we can get this enforced in the API for now is to return non-200 responses to the pinning service API  (decode the cid in full, get its codec, compare, reject)

**Comment by flea89** [comment]
Doc updates are tackled in a separate [PR](https://github.com/web3-storage/web3.storage/pull/2160)
