### ISSUE TITLE
 put method query

### ISSUE THREAD

**Issue by Taxuewuhenzz** [web3-storage/web3.storage#2158]
I am using web3.storage to upload my files to IPFS by using the client's put method.
I found that each put method calling will cost around 1~2 seconds to upload the file even though the file or the folder is small (below 40KB), is that normal? And is there any way to reduce the time spent?
Also, it will throw 'rate limited' error when sometimes I keep calling it to upload my files. Can I ask what is the rate limit of this method?
Thanks!

**Comment by vasco-santos** [comment]
Hi @Taxuewuhenzz 

Thanks for reaching out. Regarding rate limits you can read more in https://web3.storage/docs/reference/http-api/

For uploading, we are working on a new upload API that will offer a better performance and UX. This is still beta preview, but you can try it out already https://github.com/web3-storage/w3up-client

**Comment by vasco-santos** [comment]
Closing this issue. @Taxuewuhenzz let us know if you have further questions
