### ISSUE TITLE
check that simple analytics is capturing data from blog.web3.storage

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2171]
dashboard shows web3.storage/blog not blog.web3.storage
- [x] make sure that metrics are displaying relevant info for blog.web3.storage

**Comment by cmunns** [comment]
@heyjay44 This was how I was able to setup a unified dashboard including the separate subdomain. It had to be setup using /blog because with two root domains e.g. blog.web3.storage and web3.storage you would have two properties being tracked simply with `/` which would throw off reporting.
