### ISSUE TITLE
Storage Providers Queuing!?

### ISSUE THREAD

**Issue by totedati** [web3-storage/web3.storage#2181]
If i remember corectly in the recent past my older uploaded files was in the complete status range with 3 separate filecoin bukets backups but now i see all files as Queuing! What is going on here?

How i can retrieve that old filecoin bukets CIDs? Is still here? Somewhere?

Files is ok, can be retrieved and vieved online but now im confused about the status of that «filecoin guaranteed backup» status for my older files! I dont deleted or moved or renamed that files, my first tests of web3.storage as an early adopter geek, was as fresh as that first upload! That means i have 1 TB of free storage! Yay!

i mean 
`CID                                                        Complete file?  Storage Providers   Date
bafybeiepro74twxcj2jhpkwdiiq7y73pbsve552mookpnnowsgxqnlzkgi Complete        Queuing             21.02.2022
bafybeif2j7cjc7akd25hpxzcuiqdyeofa6ggbxfwledzslf7zgyqyyxmxq Complete        Queuing             26.12.2021
`

and at that Complete files? = Complete status i see that both is "The upload is fully pinned on 3 ipfs nodes"
so ... what is going on? Is not an urgent bug more something like a better UI hint for average joe users

**Comment by vasco-santos** [comment]
Hey @totedati 
We are running a bit late with Storage providers deals based on a bug we had. We are working on it and getting the backlog of data pending a deal into there. 
You can subscribe to updates on https://status.web3.storage/

**Comment by totedati** [comment]
well, check again a month later that two files is now 
Storage Providers = Stored(3)
so all ok, 3 separate filecoin backups and 3 separate ipfs CDN pins butt .... my other two files, uploaded a month ago has only 1 ipfs pin and a month later is still in Queuing state! Im talking about this two not so new files
`CID                                                        Complete file?  Storage Providers   Date
bafybeiazrh6jmv4wvqyyqubq7xm7hkkjaueog5oixnzb7eh66ru44cxwwm Complete        Queuing             06.01.2023
bafybeian4gqi3z735khyvlbymmklof2mtwbsuyhcgnk3cxxsc6p4o43ngi Complete        Queuing             06.01.2023
`

As a Web UI improvements can sugest same style as on filecoin status for IPFS pinning buckets? Complete(1) for 1 pin and Complete(3) for 3 separate ipfs pins?
