### ISSUE TITLE
create new docs website

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2190]
### Problem Statement
We need a place to point users who are using the new stuff. We currently don't have this. 

### Proposed Work
P0 - a site with the client docs generated (ready for Jan 27)
P1 - continue adding docs, in order of priority, to this skeleton site 

### Success Criteria
A website where all required documentation for the new world is available so that users can easily pick up our products and use them.

First round to include:

- [x] quick start for CLI & w3up-client
- [ ] overview of w3ui
- generated API docs (typedoc) for:
  - w3protocol:
    - [x] capabilities
    - [x] access-client
    - [x] upload-client
  - [x] w3up-client

**Comment by yusefnapora** [comment]
New docs repo is at https://github.com/web3-storage/w3up-docs with deploy preview at https://keen-sundae-c3a11f.netlify.app/

Will make issues in the new repo to track remaining P1/P0 work & close this issue once that's done.
