### ISSUE TITLE
issue with nft storage blog post on mobile site

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2194]
This [post](https://blog.nft.storage/posts/the-definitive-guide-to-wallet-security-for-nft-creators-collectors) is cut off on the mobile site. Other posts do not have the same issue. 

We want to correct this issue as quickly as possible and, if it is obvious, document why this happened.

**Comment by e-schneid** [comment]
This is caused by the long example public addresses in the blog: "Example: 0x63FaC9201494f0bd17B9892B9fae4d52fe3BD377".

I'm pushing a fix that will allow words to "break" before they cause overflow.
