### ISSUE TITLE
Typescript, eslint in production dependencies 

### ISSUE THREAD

**Issue by korostelevm** [web3-storage/web3.storage#2195]
Installing `web3.storage@4.4.0` - the most recent npm version - with the production flag or after running prune, results in typescript and eslint packages still being included in node_modules and produces a very large bundle - 157mb.

<img width="1864" alt="image" src="https://user-images.githubusercontent.com/531306/217002900-a56e5c58-0e19-4a0a-9d9c-f65f9004302f.png">

This is causing issues with deployments on serverless functions

**Comment by alanshaw** [comment]
Coming from `w3name`:

```console
$ npm ls typescript
test-2195@ /Users/alan/Desktop/test-2195
└─┬ web3.storage@4.4.0
  └─┬ w3name@1.0.7
    └─┬ ts-standard@11.0.0
      ├─┬ @typescript-eslint/eslint-plugin@4.33.0
      │ └─┬ tsutils@3.21.0
      │   └── typescript@4.9.5 deduped
      ├─┬ eslint-config-standard-with-typescript@21.0.1
      │ └── typescript@4.9.5 deduped
      └── typescript@4.9.5
```

**Comment by alanshaw** [comment]
🙈 and we already knew about it https://github.com/web3-storage/w3name/issues/96

**Comment by korostelevm** [comment]
Thanks @alanshaw, that did it
