### ISSUE TITLE
"reason":"ERROR_PINNING_UNAUTHORIZED"

### ISSUE THREAD

**Issue by duelinggalois** [web3-storage/web3.storage#2212]
Using the instructions from your docs
```bash
curl -X POST 'https://api.web3.storage/pins' \
  --header 'Accept: */*' \
  --header 'Authorization: Bearer <YOUR_AUTH_KEY_JWT>' \
  --header 'Content-Type: application/json' \
  -d '{
  "cid": "<CID_TO_BE_PINNED>",
  "name": "PreciousData.pdf"
}'
```
 with a jwt token created on https://web3.storage/tokens/ I try to pin a CID and get the following response
 ```
{"error":{"reason":"ERROR_PINNING_UNAUTHORIZED","details":"Pinning not authorized for this user, please visit https://web3.storage/docs/how-tos/pinning-services-api/ for instructions on how to request access."}}%
 ```

Navigating to https://web3.storage/docs/how-tos/pinning-services-api/  I see I need to go back to [your token management page](https://web3.storage/tokens) and find a button labeled "Request API Pinning Access"

I do not see a button labeled "Request API Pinning Access"

![Screen Shot 2023-02-20 at 2 20 38 PM](https://user-images.githubusercontent.com/26027325/220200183-5322d517-ce80-4ae2-85e9-a52e3102f229.png)

**Comment by vasco-santos** [comment]
Hi @rev3ks 
Thanks for the feedback. There is a button `Request Bulk Pinning API Access`  a bit on the left of your screenshot.
