### ISSUE TITLE
not able to upload and retrieve data from web3.storage

### ISSUE THREAD

**Issue by ayush4345** [web3-storage/web3.storage#2224]
![image](https://user-images.githubusercontent.com/99096397/221360481-21ddce47-320d-49e9-83f6-6f022f5663ff.png)

Sometimes files are getting uploaded, and sometimes doesn't.
It is happening after 20 Feb 2023

I have checked multiple times.

Also not able to retrieve some of the old data that already have been uploaded.

**Comment by dchoi27** [comment]
hey, we don't recommend using the client's get() - use the w3s.link gateway for reliable reads from web3.storage
