### ISSUE TITLE
remove code that automatically signs up new user to free tier

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2225]
Originally, we had automatically signed up all new users to the Free Tier, but this no longer necessary. Removing the code will simplify management in the future.

**Comment by e-schneid** [comment]
This is tested in staging by creating a new account and confirming that there is no corresponding customer being create in Stripe.

For manual regression testing:

1. Ensure that adding a payment method still works while the user has no customer in Stripe (as expected, this will create a new customer in Stripe).
2. Check that names and emails are properly being updated in Stripe on subsequent logins to web3.storage (after adding a payment method or subscription)
