### ISSUE TITLE
docs button on site not working

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/web3.storage#2237]
clicking on docs button doesn't take user to docs site.

**Comment by e-schneid** [comment]
It appears that the auto-events.js code is interpreting https://web3.storage/docs as the URL to a download.  Explicitly removing the 'doc' extension from the data-extensions attribute fixes this, but we're doing this as a workaround for what appears to be a bug.

<Script data-extensions="pdf,csv,docx,xlsx,zip,xls" src="https://track.web3.storage/auto-events.js" />

This is tested by clicking the Docs link and noticing that we now properly navigate to the /docs page.
