### ISSUE TITLE
Faild to fetch error

### ISSUE THREAD

**Issue by yahorshumski** [web3-storage/web3.storage#2262]
I received Failed to fetch error in IPFS Desctop application

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/6130763/233089394-d5dade10-374a-4459-a19e-6e050e6a76f1.png">

**Comment by vasco-santos** [comment]
Hi @yahorshumski 

You will need to contact us to get authorization to use Pinning Service API as described in docs page https://web3.storage/docs/how-tos/pinning-services-api/#requesting-access . Feel free to re-open the issue if you have further questions
