### ISSUE TITLE
docs: typo in introduction - curl

### ISSUE THREAD

**Issue by laurentsenta** [web3-storage/web3.storage#2289]
https://web3.storage/docs/how-tos/store/#storing-ipfs-content-archives

```sh
curl --headers "Authorization: Bearer $API_TOKEN" --data-binary @mydata.car
```
gives "curl: option --headers: is unknown"

Is it possible we meant:

```sh
curl --header "Authorization: Bearer $API_TOKEN" --data-binary @mydata.car
```

**Comment by alanshaw** [comment]
Thanks @laurentsenta I've opened an PR to fix :)
