### ISSUE TITLE
After creating new account, hovering over account->create API token, leads back to login page. 

### ISSUE THREAD

**Issue by bambooverystrong** [web3-storage/web3.storage#2303]

**Comment by heyjay44** [comment]
There were some issues with Magic Link recently. I recommend you try again and report back if there continue to be issues.

**Comment by marcelofrayha** [comment]
I'm facing the same issue

**Comment by alanshaw** [comment]
What browser are you using? Is it just hovering...or did you actually click the link?

After you have logged in, you can access the API token page here if all else fails: https://web3.storage/tokens/?create=true
