### ISSUE TITLE
Failed to Delete Multiple Files For Example 50/100 at Once

### ISSUE THREAD

**Issue by termireum** [web3-storage/web3.storage#2304]
I tried several times to delete multiple files simultaneously, after waiting for over an hour the spinner did not stop and the files were not deleted. Please investigate this issue ASAP, thanks!

**Comment by heyjay44** [comment]
Have you made any progress? In the first instance, I'd suggest trying to delete smaller batches at a time.

**Comment by termireum** [comment]
I'm still facing the same issue.
Sometimes, deleting more than 20 files at once takes quite a while and
often leads to infinite loading. I waited for over 60 minutes, but the
loading animation didn't stop until I refreshed the page. This problem
seems to happen randomly.

**Comment by termireum** [comment]
Hi Jay
How do I remove my credit card from web3.storage?

**Comment by heyjay44** [comment]
Please send an email to support@web3.storage.
