### ISSUE TITLE
Need assistance completing a 9gb upload as car files - all files uploaded successfully but only 2 of 75 files show complete after 5 days.

### ISSUE THREAD

**Issue by Mulanzo** [web3-storage/web3.storage#2309]
Hello,

I have a 9gb directory pinned to Piñata and pinned Locally - however it is too large to upload to web3storage so I broke it into smaller CAR files and tried to upload them - 75 files total.  The uploads for each file completed with no errors but after more than 4 days they are all showing Pinning and 0kb with the exception of 2 files out of 75 that show complete (but still 0kb).  I need to have these files pinned to the web3storage account so I can close my Piñata account before the next billing date which is next week.  Can you please provide some assistance with ensuring these are pinned to my account appropriately?  I'm quite a noob so I can't really do anything programmatically.  I used the HTTP thing to upload the files.  
Thanks,

**Comment by heyjay44** [comment]
I'm sorry you've run into issues. Without more details, it is hard to know why this is happening. To start, I recommend taking a look here: https://www.npmjs.com/package/@web3-storage/w3
