### ISSUE TITLE
API tokens should not permit admin operations

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#231]
Our API tokens currently allow access to the whole API. In leu of proper scoping for tokens we should lock down certain endpoints to be accessible only with a Magic.link token.

Proposal:

* 🤲 `GET /car/:cid`
* 🤲 `HEAD /car/:cid`
* 🔒 `POST /car`
* 🔒 `POST /upload`
* 🤲 `GET /status/:cid`
* 🤲 `POST /user/login`
* 👮 `GET /user/tokens`
* 👮 `POST /user/tokens`
* 👮 `DELETE /user/tokens/:id`
* 🔒 `GET /user/uploads`
* 👮 `DELETE /user/uploads/:cid`
* 👮 `GET /user/account`

🤲 = open 🔒 = authenticated 👮 = admin

The 🔒 endpoints will be accessible with an API token or Magic.link token. The 👮 endpoints are only accessible from the website using a magic.link token.

**Comment by dchoi27** [comment]
Can this be closed by #237?
