### ISSUE TITLE
dashboard getting redirected to login page when we click `create API token` or `API tokens` (Added GIF)

### ISSUE THREAD

**Issue by madclaws** [web3-storage/web3.storage#2311]
![loginredirect](https://github.com/web3-storage/web3.storage/assets/17821575/6889485b-a6f5-4283-8049-00d036075d80)

**Comment by heyjay44** [comment]
@madclaws sorry you are running into this issue. I can't seem to reproduce. Have you tried opening without opening in a new tab / changing browsers?

**Comment by heyjay44** [comment]
If the above doesn't work, once logged in, you can also go directly here: https://web3.storage/tokens/?create=true

**Comment by madclaws** [comment]
@heyjay44 I think this was due to brave's adblocker and stuff, i have tried in chrome and it is working fine :+1:
