### ISSUE TITLE
unable to create an api key 

### ISSUE THREAD

**Issue by Rahulguggilam2003** [web3-storage/web3.storage#2313]
https://github.com/web3-storage/web3.storage/assets/94698414/1b7901a6-f5cd-4a46-8c15-bc3b011c323e

**Comment by heyjay44** [comment]
@Rahulguggilam2003 my apologies for the delay. My first suggestion would be trying in a different browser. Additionally, could you share your browser logs? You can share via email if you prefer: support@web3.storage.
