### ISSUE TITLE
Failure to compile with Webpack in Vue project

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#260]
A few folks are getting the following error when using the JS client library with Webpack in Vue:
```
These dependencies were not found:

* ipfs-car/blockstore/memory in ./node_modules/web3.storage/src/platform.web.js
* ipfs-car/pack in ./node_modules/web3.storage/src/lib.js
* ipfs-car/unpack in ./node_modules/web3.storage/src/lib.js
```

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/e7ef0e19-e349-4a20-a427-bb67738ab476)
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/76c09651-406e-4d2e-af8e-2dbe11084b14)

**Comment by alanshaw** [comment]
you’ll need to use webpack 5, webpack 4 doesn’t support package.json named exports which is what that module is using

**Comment by pooja** [comment]
Can we add this to a troubleshooting section (or similar) in the docs site? cc @terichadbourne

**Comment by jordaniza** [comment]
Can confirm this works flawlessly with a new Vue CLI 5 project, although I was not able to upgrade an existing project due to a merge conflict with Babel.

**Comment by alanshaw** [comment]
You can work around the issue in webpack 4 by using the prebuilt bundle:

```js
import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
```
