### ISSUE TITLE
Establish and document rate limits

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#269]
People would like to know what the rate limits are for our APIs, so they can throttle operations accordingly and avoid expected errors. 

- [ ] rate limits are added to the API docs.

**Comment by dchoi27** [comment]
@alanshaw thoughts on the rate limit we can quote?

**Comment by dchoi27** [comment]
Bumping this as something we want to probably work on soon (next week?). We should reach out to Cloudflare support to understand when users might run into rate limiting issues, and match that up with where Cluster might face scaling issues.

**Comment by atopal** [comment]
Now that we have rate limits, we should document them.

**Comment by vasco-santos** [comment]
To create visibility until documented:

We rate limit when 30+ requests for 10 seconds with the same auth header

**Comment by mikeal** [comment]
![IMG_0337](https://user-images.githubusercontent.com/579/144457401-45e16256-2994-4c34-8ea0-e59b028fb8e3.jpeg)
