### ISSUE TITLE
Allow file removal from within a folder

### ISSUE THREAD

**Issue by markg85** [web3-storage/web3.storage#271]
Hi,

I'll first need to explain some concepts for this feature to make sense in the right context.

In IPFS you can add a folder. So say `ipfs add -r <somefolder>` would give you a unique Qm... with the contents of your folder.
If you then decide to remove a file from that folder and re-add it you get another new unique Qm... with the contents of your now new folder.

That's just IPFS.

Now if a user wants to "remove" a file from a folder but keep the Qm... the same, the user should use IPNS.

For clarity. I know removal isn't necessarily possible on IPFS. It's a matter of not a single user pinning the file which effectively removed the file. By removing in this context i merely mean for the file to not be there in the Qm.. of the folder.

With this background in mind, onto the actual feature request.
In web3.storage one is allowed to add a folder. A folder can have a ton of files.
But in a folder, same idea as if you were browsing a folder on your local pc, you might just want to get rid of a file. It doesn't even have to be done out of a need to conserve storage. It might just be to organize it better.
This very usecase, removing a file from a folder, isn't possible at all on web3.storage.

You can "workaround" it but it's quite costly. You can remove your entire folder and re-upload it with that one file gone.

What i would like to request is a feature like IPNS for web3.storage. This would allow one to (seemingly) remove a file from their folder.

Best regards,
Mark

(edit, based on a discussion with "atopal" on discord)
If there were a delete API method id expect it to take at least these arguments:
- CID file to delete
- CID of parent

The return argument should be the CID of the (new) parent.
In case IPFS is used (so no IPNS) then the parent should become a new CID.
In case IPNS is used the parent CID should be the same as it was.

IPNS mechanics have my preference.

**Comment by atopal** [comment]
now handled in #959
