### ISSUE TITLE
Pin cron shouldn't ask for DAG size of the same CID more than once

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#272]
Can cache in memory and only update for CIDs not yet "sized".

**Comment by dchoi27** [comment]
@alanshaw when you have a sec can you add a prioritization label to this issue?

**Comment by alanshaw** [comment]
This was resolved in https://github.com/web3-storage/web3.storage/commit/4646fc4ca654600de362fb5192c555c0168ea98e
