### ISSUE TITLE
"Calculating" in uploads table in web3.storage site doesn't fit column

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#275]
The tooltip hover over ? button also looks odd on the far right of the column header

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/842dc9e1-d4ec-4f21-8648-e5d5c7edb559)

**Comment by alanshaw** [comment]
Fixed in https://github.com/web3-storage/web3.storage/commit/52b10be5a26e2fc4a9ecac787fdcb1326ec67a5c
