### ISSUE TITLE
Add a "upload a file" getting started option

### ISSUE THREAD

**Issue by momack2** [web3-storage/web3.storage#277]
Add a "upload a file" getting started option to the onboarding screen of web3.storage
![image](https://user-images.githubusercontent.com/618519/127925654-32c28259-7a6e-4918-bf94-2d943c1436a8.png)

 that immediately takes you to the files page (before creating any API token) so you can add your first file

![image](https://user-images.githubusercontent.com/618519/127925601-3b8e7b63-a846-45c6-ab3c-551a087b3bb0.png)

**Comment by atopal** [comment]
Is the reason that we want to give people an immediate "win", before we ask them to do something more complicated?

**Comment by momack2** [comment]
Yep! Imho Some people may just want to try it out and get a feel for
latency and ease of use before they get started with the api directly (and
for those that don’t want to, adding the option here shouldn’t hurt).

**Comment by dchoi27** [comment]
@jdiogopeixoto We should add a warning about uploading sensitive data and that deleted data is not ensured to be deleted from the network (so still might be accessible by CID), similar to this one before users upload their first file (both in getting started in the Files tab).

Example in docs (which probably should also discuss the delete part):
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/64ae50e2-cf81-4ade-a49d-933a3a0e1198)

**Comment by jdiogopeixoto** [comment]
@momack2, what should we add as the description? I guess for the title and button we just want a simple "upload your first file" as the image below.

<img width="350" alt="Screenshot 2021-08-23 at 16 08 06" src="https://user-images.githubusercontent.com/34691925/130471341-9d28f601-0cf6-491d-b5fb-f7032834c6a3.png">

**Comment by dchoi27** [comment]
Assuming the following is true, we probably want to say that (1) Try uploading a file to Web3.Storage, (2) a new API token will be created if you haven't created one yet, and if you have already created a token, we'll use the first token you generated for the upload, and (3) you can upload more files by going to the "Files" tab at the top.

When will this appear in Getting Started? We should probably take it out if the user has already uploaded their first file.

**Comment by jdiogopeixoto** [comment]
(2) I don't think that is true, just tried uploading a file without having a token and still had no token after the upload.
(3) I would say that's not necessary as we will redirect user to the `/files` page when they click on the button. 

> When will this appear in Getting Started? We should probably take it out if the user has already uploaded their first file.

Either as the first or second step, what do you prefer? And yes, I'll hide it when the user has already uploaded their first file.

**Comment by dchoi27** [comment]
Ah good to know on (2)! And makes sense on (3).

Let's put this as the first step, maybe in its own row for now (so it's centered above the two existing boxes)
