### ISSUE TITLE
[research] Cannot retrieve file through web gateway after upload

### ISSUE THREAD

**Issue by Trott** [web3-storage/web3.storage#278]
My web3.storage/files interface includes this link:

https://bafybeia76qn4cxtqilptkqkytxgsgb7akz2tintvadmcbgxwfi2si7mbna.ipfs.dweb.link/

Alas, that URL always 502's for me. I suspect my file size is a factor.

**Comment by dchoi27** [comment]
Ah sorry to hear that! Could you provide more details on how you uploaded the file, what type of file it is, and how large it is?

**Comment by Trott** [comment]
> Could you provide more details on how you uploaded the file, what type of file it is, and how large it is? Have you been able to upload other files?

I have a directory that contains a few thousand files. Using the `put-files.js` from the getting-started tutorial, I tried to upload them like this:

```
find my_dir -type f | xargs node put-files.js  --token=$_API_TOKEN
```

Unfortunately, it only uploaded one file and I don't know which one it is. And that's the file in question.

I thought it might be the first file that comes up with `find`, so to test that, I used `-n 1` with `xargs`:

```
find my_dir -type f | xargs node put-files.js  --token=$_API_TOKEN
```

But that uploaded a different file, and that file (which is a 200 MB .tsv file) seems to be working just fine. (Unfortunately, that also appears to have stalled after a single file. I'm on much less reliable wi-fi than I usually am on and I suppose that might be a factor.)

When I use the `-size` flag for `find` to specify only relatively small files, things go much better and I can upload many files consecutively.

**Comment by Trott** [comment]
Not sure if this is relevant or not, but on my web3.storage/files, the smaller files show up fine:

![image](https://user-images.githubusercontent.com/718899/127953996-f5bb978f-688f-46ef-b02a-94dc38611c52.png)

But the large files (including the one that won't load at all via the web interface that I'm reporting here) that I uploaded some time ago, seem to be stuck with the size (last column) still being calculated:

![image](https://user-images.githubusercontent.com/718899/127954094-d93becf5-b550-4828-9937-c96d23c8bd19.png)

**Comment by atopal** [comment]
possibly related: https://github.com/web3-storage/web3.storage/issues/318

**Comment by Trott** [comment]
I also can't seem to delete this file from my web3.storage account. It shows in the interface but it won't let me select the checkbox to delete it.

**Comment by atopal** [comment]
For now, we'll just make sure the error is visible in the UI

**Comment by atopal** [comment]
We need some sort of toast that surfaces the errors to the users instead of swallowing it.

**Comment by atopal** [comment]
related to https://github.com/ipfs-shipyard/nft.storage/issues/404

**Comment by Gozala** [comment]
Slow retrieval has been reported also here https://filecoinproject.slack.com/archives/C027XP5BTGB/p1636300373060800

**Comment by vasco-santos** [comment]
#543 added error banner to avoid these cases. Moreover, we are already tracking slow retrieval work in https://github.com/web3-storage/web3.storage/issues/688 and we will be working on it. So, closing this to avoid duplicated issues.
