### ISSUE TITLE
Expose more info from /user/uploads?

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#284]
It currently exposes a subset of what you get from `/status/:cid` for each item. The issue is just that it requires a join with `PinLocation` and I don't know if there's a problem returning this amount of data for our max page size (100).

**Comment by atopal** [comment]
Vasco might have done that already. @cc @vasco-santos can you confirm?

**Comment by vasco-santos** [comment]
We currently return the Pin locations from the `/user/uploads` route as well. The `/user/uploads` route returns specific upload metadata while `status` returns content specific. Given this, I think we already return exactly the same relevant information.

Status:

```ts
{
  created: definitions['content']['inserted_at']
  cid: definitions['content']['cid']
  dagSize?: definitions['content']['dag_size']
  pins: Array<PinItemOutput>,
  deals: Array<Deal>
}
```

List Uploads:

```ts
{
  _id: string
  type: definitions['upload']['type']
  name?: definitions['upload']['name']
  created: definitions['upload']['inserted_at']
  updated: definitions['upload']['updated_at']
  cid: definitions['content']['cid']
  dagSize?: definitions['content']['dag_size']
  pins: Array<PinItemOutput>,
  deals: Array<Deal>
}```
