### ISSUE TITLE
Expose API for uploading CAR files

### ISSUE THREAD

**Issue by mikeal** [web3-storage/web3.storage#288]
We just need to abstract the current `put()` method a little. Probably turn this into an `_` method https://github.com/web3-storage/web3.storage/blob/main/packages/client/src/lib.js#L131 and write a small function on top like “`putCAR()`” to call the `_` method.

**Comment by terichadbourne** [comment]
Taking a first stab at this at Mikeal's request; hope to circle back this afternoon with a draft.
