### ISSUE TITLE
Querying status for something that's not yet `Pinned` returns `undefined`

### ISSUE THREAD

**Issue by 0xMartian** [web3-storage/web3.storage#301]
Trying to query and display the status of individual pins on my interface but always getting undefined for pins that are not yet pinned (queued, pinqueued...).

Is this intended the behaviour?

#### Code
```js
const status = await client.status(cid)
console.log('s', status) // undefined
if (status) setStatus(status)
```

#### Console error
```
GET https://api.web3.storage/status/bafkreidgegxb5w5yopnj4aqw6nav42jyxjlbkx2y3g6r3hhvukmsyraonu 404
```

**Comment by alanshaw** [comment]
I can't see that CID in the database are you certain it's listed in your UI?

**Comment by 0xMartian** [comment]
Yes, pretty sure. Here are a few other ones:
```js
{
    params: {
      cid: 'bafybeihbxdv2cvc2jb54nvd4wwld2uekbkbw4aixleax76rwhwghqxztia'
    }
  },
  {
    params: {
      cid: 'bafybeidbe7cyumtq5xxj4giurdotjbjinm26t23xpqyapgbwojnrsmzyhm'
    }
  },
  {
    params: {
      cid: 'bafybeicjwwybxqim5x3dqpr6waq62ib67k4rnoelk27edwlbiarrpwhxve'
    }
  },
```

**Comment by 0xMartian** [comment]
Might be something on my end - if I paste it in directly it seems to work:
```js
    const status = await client.status(
      'bafybeicfzuupft5pitdb77wrtl2enoxwpoztdy4blhga2mmy5fdee5yi2u',
    )
    setStatus(status)
```
Will update.

**Comment by alanshaw** [comment]
yeah these other ones I can find and are not returning 404.

**Comment by 0xMartian** [comment]
Figured it out...

I was passing in a `cid` of a file inside my pin, not the `cid` of the pin.
