### ISSUE TITLE
Language describing storage space utilized in "Account" on website

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#303]
Thought this was phrased kind of oddly:
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/d9a16930-b69e-4e61-8206-9ded344f272c)

`Storage Capacity` refers to the total amount of storage you are able to utilize. The number displayed is the amount that is currently utilized. I would either change it to something like `Capacity Utilized` or make the bar the complement and call it `Capacity Remaining`.

**Comment by jdiogopeixoto** [comment]
<img width="435" alt="Screenshot 2021-08-17 at 14 27 11" src="https://user-images.githubusercontent.com/34691925/129734172-8723b86e-a7d1-46d1-ace3-65e04d467a53.png">

@dchoi27 what do you think about changing to this?

**Comment by dchoi27** [comment]
LGTM!

**Comment by dchoi27** [comment]
Hm weird - I'm seeing the old language still @jdiogopeixoto 
![image](https://user-images.githubusercontent.com/11778450/131586484-04888af0-498e-486b-abfe-86671a486736.png)
LMK if there's something weird going on and I can help debug

**Comment by jdiogopeixoto** [comment]
I did change this but I think the website hasn't been deployed for a while now, that's why you're not seeing it.

**Comment by jdiogopeixoto** [comment]
@dchoi27, this is live now.
