### ISSUE TITLE
Module not found: Can't resolve 'ipfs-car/blockstore/memory' from web3.storage/src/platform.web.js

### ISSUE THREAD

**Issue by tomosaigon** [web3-storage/web3.storage#304]
In the popular hackathon boilerplate scaffold-eth which uses Create React App, adding web3.storage to the React site results in a "Failed to compile" error with the reason being "Module not found: Can't resolve 'ipfs-car/blockstore/memory'" which is referenced from the file web3.storage/src/platform.web.js.

Create React App's react-scripts depends on webpack v4 and others have said web3.storage works with webpack v5 but not v4. For now this means popular packages like scaffold-eth and create-react-app won't work with web3.storage.

**Comment by alanshaw** [comment]
Hi @tomosaigon I just tested in Create React App successfully - you should be able to use the prebuilt bundle like this:

```js
import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
```

Please let me know if this doesn't work for you.

**Comment by jaccos** [comment]
I tried import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js' and that works fine

**Comment by Udit-takkar** [comment]
> Please let me know if this doesn't work for you.

Not Working

**Comment by aronchick** [comment]
+1 - does not work. 

```
Cannot find module 'ipfs-car/blockstore/fs' from '/workspaces/collectorx/node_modules/web3.storage/dist/src/lib.cjs'
```

**Comment by alanshaw** [comment]
Did you both try importing the prebuilt bundle as mentioned above?

**Comment by aronchick** [comment]
thanks! didn't know if that would work in browser situations, but got info that we only support webpack. so switched over. 

Would be great if this could be part of the docs, but since i moved on, we can punt on this for now. 

(to be clear, i got here from Google, so this is linked via SEO)

**Comment by tas2017** [comment]
Also struggling with this: 
I tried: import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
Keep getting this error 
![image](https://user-images.githubusercontent.com/36696601/143943452-b750c35b-494a-4121-a407-a69a868635cc.png)

**Comment by natethor** [comment]
I'm also having the same problem with my React App.
- Node 16.13.2
- Yarn 1.22.17
- React 17.0.1
- react-scripts 4.0.3
- web3.storage 3.1.0

I've tried with both import { Web3Storage } from 'web3.storage' and import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'

**Comment by nirban256** [comment]
> Hi @tomosaigon I just tested in Create React App successfully - you should be able to use the prebuilt bundle like this:
> 
> ```js
> import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
> ```
> 
> Please let me know if this doesn't work for you.

Thanks it worked for me.
