### ISSUE TITLE
uploads stalling

### ISSUE THREAD

**Issue by Trott** [web3-storage/web3.storage#309]
I'm using the `put-files` script from the "getting started" example to upload several thousand files. Uploading them with one invocation of the script didn't seem to be working so I'm passing one file path at a time to the script. I also have the files ordered from smallest to largest, so right now I'm dealing with files that are less than 1 Kb in size. The uploads stall every so often and I need to restart them. No errors are reported, no timeout error shows up...the script just says it's uploading a file and pauses to wait for the CID and it never moves on again until I manually terminate it and restart it. (Maybe it's a simple demo script and I need to add some rudimentary error handling?)

**Comment by alanshaw** [comment]
An upload will be retried up to 10 times with an exponential delay starting from 1 second - so could potentially be retrying for 15+ minutes. Have you observed stalling for significantly longer than this?

**Comment by Trott** [comment]
I do not know if I've observed stalling for longer than 15 minutes. I am now on a more reliable network (I had been traveling) and ran an upload-one-at-a-time job overnight and noticed that it did *seem* to stall a few times but then came back. I'll stop the job now and re-start it with a modification to print elapsed time for each upload.

I'll close this as it seems to be "working as expected" and re-open if I find something unexpected.

A feature that might be useful (maybe it's already there?) is a debug or verbose mode where it will tell you something like "upload failed, retrying in N seconds" perhaps along with other messages that might be helpful.

Thanks for the information/help!
