### ISSUE TITLE
Prebuilt web3.storage library

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#312]
Create a prebuilt library for folks having bundling issues (like webpack 4 as used by create react app and scaffold.eth).

e.g. https://github.com/web3-storage/web3.storage/issues/304

**Comment by alanshaw** [comment]
Turns out, this is already in the published package and you can use in webpack 4 like this:

```js
import { Web3Storage } from 'web3.storage/dist/bundle.esm.min.js'
```

**Comment by ivanschuetz** [comment]
@alanshaw is there an updated link for this?
