### ISSUE TITLE
Clients in different languages

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#315]
We should make clients for various programming languages

**Comment by zhorsex** [comment]
希望添加 deno、python 的客户端支持，感谢~

**Comment by zhorsex** [comment]
I hope to add support for Deno and Python clients. Thank you!

**Comment by jonyg80** [comment]
Please, for dart also.

**Comment by dchoi27** [comment]
Note: #152 will generate docs for the HTTP API

**Comment by atopal** [comment]
We now have a client for Go. I'd suggest we close this epic and open epics  for each language specifically, so that we can individually prioritize.
