### ISSUE TITLE
Can't resolve 'ipfs-car/blockstore/memory'

### ISSUE THREAD

**Issue by jaccos** [web3-storage/web3.storage#321]
this is what i get when i did npm install web3.storage

in my react webpage added import { Web3Storage } from 'web3.storage'

./node_modules/web3.storage/src/platform.web.js
Module not found: Can't resolve 'ipfs-car/blockstore/memory' in '/Users/jaccostokx/Projects/benb/node_modules/web3.storage/src'

**Comment by siosw** [comment]
check out this issue: https://github.com/web3-storage/web3.storage/issues/304
