### ISSUE TITLE
Support non-EN file names for upload

### ISSUE THREAD

**Issue by jnthnvctr** [web3-storage/web3.storage#326]
A user in the Filecoin slack noted that he was getting upload errors for files that were named with non-EN characters. We should add support for other languages.

**Comment by atopal** [comment]
Is this just any non-ascii character?

**Comment by jnthnvctr** [comment]
Unclear here's the exact convo: 
![image](https://user-images.githubusercontent.com/21000523/128908062-38bc1e05-8df2-4752-b652-7525db3053a9.png)

https://filecoinproject.slack.com/archives/C027XP5BTGB/p1628528150077300?thread_ts=1628523694.075300&cid=C027XP5BTGB

**Comment by atopal** [comment]
I can't reproduce this. Non latin and bidi seems to work fine. See here: https://bafybeicjsrhxl2hsflnlhiy7hbmfshlom6z4nc2fwxzvogtn7i5rvnk7em.ipfs.dweb.link/

**Comment by dchoi27** [comment]
Closing for now, if others come across the same issue feel free to reopen
