### ISSUE TITLE
Add static naming for data

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#330]
If data changes and is reuploaded to nft.storage, the CID changes. However, there are some use cases where we want static pointers to this data. Support for this in web3.storage / integration with existing tools (e.g., IPNS, Ceramic stream IDs, ENS) could expand the use cases for web3.storage.

![image](https://user-images.githubusercontent.com/11778450/128909967-55965885-dc91-4a2a-89d7-526cf916ba79.png)

**Comment by atopal** [comment]
now handled in #659

**Comment by atopal** [comment]
now handled in #659
