### ISSUE TITLE
I deleted file but yet still appears into IPFS public network!

### ISSUE THREAD

**Issue by salespaulo** [web3-storage/web3.storage#331]
Hello everyone!

First, I would like to thank you for the excellent work you have done on this tool.

I'm having a behavior that in my view is wrong, because I deleted the file I stored but this file is still available at https://bafybeid4k5guxm3yea6pao4g45ijhoa6np4r3desz5ta7egz2k4gfbth4u.ipfs.dweb.link.

I would like to know if there is any time to wait until the file is deleted at once?

Thank you and I am available here!

**Comment by insanity54** [comment]
I don't think that's a bug. From https://docs.web3.storage/how-tos/store/#preparing-files-for-upload--

> IMPORTANT
> 
> Deleting files from the Web3.Storage site's Files page will remove them from the file listing for your account, but that doesn't prevent nodes on the decentralized storage network from retaining copies of the data indefinitely. Do not use Web3.Storage for data that may need to be permanently deleted in the future.

**Comment by atopal** [comment]
That's correct. Once files are added to IPFS there is no set expectation that any given node/gateway will ever delete it again.

**Comment by atopal** [comment]
Additionally, even if it's removed from the gateways, a copy might still be saved in Filecoin.

**Comment by alanshaw** [comment]
@salespaulo hopefully the above answers your question. Please let us know if not.
