### ISSUE TITLE
Use indexedDb as blockstore in the client

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/web3.storage#336]
We are currently using the `MemoryBlockstore` in the [Browser](https://github.com/web3-storage/web3.storage/blob/main/packages/client/src/platform.web.js#L1) and `FsBlockstore` in Node.js. We should change the browser blockstore to IndexedDb to support bigger files

**Comment by olizilla** [comment]
we should do some more robustness testing of the IndexedDB flavour. I'm concerned that it will leave many empty dbs as it empties the db rather than deleting it when it is done.

**Comment by olizilla** [comment]
Closing this as it's not something we need right now. If folks want it, we can re-open later.
