### ISSUE TITLE
Ability to get file names associated with CID

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#340]
Sometimes users want to get the filenames within a CID. If we can display this data easily, the `status()` method would probably be a good place. 

![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/04787500-f181-4d2c-9601-791b36c9cc72)

**Comment by olizilla** [comment]
Yes, we should make this possible. Maybe a typo, there is no `query` method on the client. There is the `status` method and http endpoint, but that can only return info about the DAG that is true for everyone. the name that a user provides on an upload is associated with their account, so we may need to provide a new endpoint to get personalised info about an upload that includes the name you provided.

We could customise the reponse from calling status to include the name you gave a given CID if you provide an auth token.

In the meantime there is the `list` method which returns all your personal list of uploads, including the name. Here is example output from `w3`

```console
$ w3 list
  Content ID                                                   Name
⁂ bafybeibkozbrqfcbrtvxt5j5ifswz27lvf5u3wscckicd7d7kbjw6rdlry  Upload at 2021-08-10T13:38:08.853Z
⁂ bafybeibdbrvyxi3opjfvgp4z75msuigrpvvmmbrcfcuq4k4li5xjgpldba  Upload at 2021-08-10T13:37:27.054Z
⁂ bafybeigxve4jcuc5o5cq3sjifgw5ukzteb23xsqalzjltavk5bzn4bi3w4  Upload at 2021-07-29T18:36:30.908Z
⁂ bafybeiajdopsmspomlrpaohtzo5sdnpknbolqjpde6huzrsejqmvijrcea  Upload at 2021-07-29T09:09:55.100Z
⁂ bafybeidwfngv7n5y7ydbzotrwl3gohgr2lv2g7vn6xggwcjzrf5emknrki  Upload at 2021-07-29T09:08:25.770Z
⁂ bafybeifpaez32hlrz5tmr7scndxtjgw3auuloyuyxblynqmjw5saapewmu  Upload at 2021-07-29T09:07:28.991Z
⁂ bafybeid3x34ovqmnqsb6p6j25warb53yzpsbsiphm5wo6igzlvyl4ezhze  Upload at 2021-07-29T09:04:50.147Z
⁂ bafybeifs3ldy6yfwqm2utbkg4h55jszq6whko76wlcynhvhpmdwl6y7co4  Upload at 2021-07-29T09:04:10.438Z
⁂ bafybeidluj5ub7okodgg5v6l4x3nytpivvcouuxgzuioa6vodg3xt2uqle  olizilla.png
  9 items – 1.7MB stored 
```

**Comment by easonchai** [comment]
@olizilla Yes, thank you for helping me to correct the `status` method! The `list` method is great, however we only get the name of the archive rather than the list of names of files within the archive. It would also be best that each user actually generates their own keys and use it if we use the `list` method. That means that our frontend will need to handle API key generation, which is not yet available in web3storage. 

So ideally having a method that we can call to extract the metadata from the uploaded files would be great without having to download the entire archive first

**Comment by olizilla** [comment]
Ah ok! We need to do better job at explaining how web3.storage works, and how it fits in with IPFS & Filecoin! Uploads to web3.stroage are all added to the public IPFS network as well as added to Filecoin deals. Existing IPFS tools and APIs can tell you what is inside each upload, using the root CID.

If you run IPFS locally then you can ask it, p2p style

```sh
# upload a directory with 3 pictures in
❯ w3 put ./pics
# Packed 3 files (0.5MB)
# bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q
⁂ Stored 3 files
⁂ https://dweb.link/ipfs/bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q

# ask ipfs to list out the contents of that root
❯ ipfs ls bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q
bafybeifpaez32hlrz5tmr7scndxtjgw3auuloyuyxblynqmjw5saapewmu - pics/

# you append the path to the root cid to look into sub directories
❯ ipfs ls bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q/pics
bafkreiabltrd5zm73pvi7plq25pef3hm7jxhbi3kv4hapegrkfpkqtkbme 94482  dr-is-tired.jpg
bafkreidrsgkip425zjamc3pvmil7dpatss7ncedyaatepxyionxi7py5fq 414201 not-distributed.jpg
bafkreiaqv66m5nd6mwgkk7h5lwqnjzj54s4f7knmnrjhb7ylzqfg2vdo54 55415  youareanonsense.jpg
```

your ipfs node will pull down the blocks it needs to get the directory listing, but it wont pull down the entire tree unless you ask it to.

IPFS HTTP Gateways also provide an API to do the same thing remotely if you need to, and pathing into subdirs works the same there:

```
❯ curl "https://dweb.link/api/v0/ls?arg=bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q" -s | jq
{
  "Objects": [
    {
      "Hash": "bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q",
      "Links": [
        {
          "Name": "pics",
          "Hash": "bafybeifpaez32hlrz5tmr7scndxtjgw3auuloyuyxblynqmjw5saapewmu",
          "Size": 0,
          "Type": 1,
          "Target": ""
        }
      ]
    }
  ]
}

# list the contents of the pics dir
❯ curl "https://dweb.link/api/v0/ls?arg=bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q/pics" -s | jq
{
  "Objects": [
    {
      "Hash": "bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q/pics",
      "Links": [
        {
          "Name": "dr-is-tired.jpg",
          "Hash": "bafkreiabltrd5zm73pvi7plq25pef3hm7jxhbi3kv4hapegrkfpkqtkbme",
          "Size": 94482,
          "Type": 2,
          "Target": ""
        },
        {
          "Name": "not-distributed.jpg",
          "Hash": "bafkreidrsgkip425zjamc3pvmil7dpatss7ncedyaatepxyionxi7py5fq",
          "Size": 414201,
          "Type": 2,
          "Target": ""
        },
        {
          "Name": "youareanonsense.jpg",
          "Hash": "bafkreiaqv66m5nd6mwgkk7h5lwqnjzj54s4f7knmnrjhb7ylzqfg2vdo54",
          "Size": 55415,
          "Type": 2,
          "Target": ""
        }
      ]
    }
  ]
}
```
