### ISSUE TITLE
Can't resolve 'ipfs-car/blockstore/memory' 

### ISSUE THREAD

**Issue by Jacky-Liu1** [web3-storage/web3.storage#343]
Getting this issue 
`Module not found: Can't resolve 'ipfs-car/blockstore/memory' in /my_project/node_modules/web3.storage/src'`
when I add 
`import Web3Storage from 'web3.storage`
I have tried npm installing web3.storage, ipfs, ipfs-car, and level-blockstore

**Comment by vasco-santos** [comment]
Hello @Jacky-Liu1 
what are you using while building your project? This should be related to the bundling issues in https://github.com/web3-storage/web3.storage/issues/312 . Using the prebuilt library should work around your problems

**Comment by Jacky-Liu1** [comment]
Thank you! That did the trick

**Comment by jilt** [comment]
Hey guys, I found this problem again and solved with the NFT.storage solution mentioned [here](https://stackoverflow.com/questions/70063600/cant-resolve-ipfs-car-blockstore-memory-when-importing-nft-storage)
[This is the link](https://github.com/jilt/near-spring-challenge-4) one of the two repositories I'm building for my microgrant, I excluded the web3.storage package for people to be able to download it modified from there, the app already works with near and signer wallet, still working on the interface to upload..
Justt wanted you guys to know there are still issues on this, with webpack 5
