### ISSUE TITLE
Unable to see progress with storeWithProgress 

### ISSUE THREAD

**Issue by hellopaidco** [web3-storage/web3.storage#346]
I'm using the storeWithProgress from the example (pasted below as reference) but don't see onChunkStored getting invoked so unable to access the progress information. The upload and everything else works fine however.

```
async function storeWithProgress(files) {  
  // show the root cid as soon as it's ready
  const onRootCidReady = cid => {
    console.log('uploading files with cid:', cid)
  }

  // when each chunk is stored, update the percentage complete and display
  const totalSize = files.map(f => f.size).reduce((a, b) => a + b, 0)
  let uploaded = 0

  const onChunkStored = size => {
    uploaded += size
    const pct = totalSize / uploaded
    console.log(`Uploading... ${pct.toFixed(2)}% complete`)
  }

  // makeStorageClient returns an authorized Web3.Storage client instance
  const client = makeStorageClient()

  // client.put will invoke our callbacks during the upload
  // and return the root cid when the upload completes
  return client.put(files, { onRootCidReady, onChunkStored })
}
```

**Comment by vasco-santos** [comment]
Hello @hellopaidco 
What is the size of your files? Each chunk will have [~10MB](https://github.com/web3-storage/web3.storage/blob/main/packages/client/src/lib.js#L33). Per the [interface docs](https://github.com/web3-storage/web3.storage/blob/main/packages/client/src/lib/interface.ts#L93-L97)  this is clear, but I agree that users should not need to dive into this.

**Comment by hellopaidco** [comment]
@vasco-santos - thanks for the quick reply and explanation. I've tried a single file well over 100MB but do not see the progress displayed in the console.

**Comment by vasco-santos** [comment]
Oh, I see what is the issue. Where did you get this code?

The parameter that `client.put` should receive is `onStoredChunk` and not `onChunkStored`

**Comment by hellopaidco** [comment]
@vasco-santos That fixed it! Thank you very much :) 

I found the snippet here: https://docs.web3.storage/how-tos/store/#uploading-to-web3-storage

**Comment by vasco-santos** [comment]
Happy to help. And thanks @hellopaidco for directing me to the docs issue, already PRd a fixed for the docs https://github.com/web3-storage/docs/pull/157
