### ISSUE TITLE
Upload stuck in queuing state ... possibly interrupted

### ISSUE THREAD

**Issue by jimpick** [web3-storage/web3.storage#355]
@ribasushi asked me to look into a particular CID i was uploading to web3.storage => "we managed to not get it pinned, trying to understand what could have been..."

CID: bafybeig7qnlzyregxe2m63b4kkpx3ujqm5bwmn5wtvtftp7j27tmdtznji

<img width="1098" alt="Screen Shot 2021-08-16 at 3 50 43 PM" src="https://user-images.githubusercontent.com/20886/129638777-d5cfd4d8-ccfe-45a3-b3fa-ea00108d950a.png">

I was uploading using this script (the same as in the tutorial):

https://github.com/jimpick/miner-report-spark/blob/main/web3-storage-archive/put-files.js

I’m not 100% sure … but it’s possible that it was still uploading when the power to my computer failed.

**Comment by alanshaw** [comment]
The size is reported as 2,128,796,832 but I'm only able to get hold of 914,687,084 bytes of it.

I suggest re-uploading and using the [`onStoredChunk` callback](https://docs.web3.storage/how-tos/store/#uploading-to-web3-storage) to keep track of how much gets uploaded (and also to give you an idea that things are progressing).

**Comment by alanshaw** [comment]
@jimpick did you manage to figure this out? Is there something we could do to help you out here?

**Comment by jimpick** [comment]
I only filed the issue because @ribasushi asked me too... I was hoping he'd
elaborate on it. I'm guessing his thinking is that the upload shouldn't
even be in the system if it was interrupted.

**Comment by atopal** [comment]
We've made some architectural changes, please reopen, if this is still an issue
