### ISSUE TITLE
After deleting file, it still exists

### ISSUE THREAD

**Issue by flee541** [web3-storage/web3.storage#370]
Did a test file upload and decided to delete it however it still exists after deleting. Do all files once uploaded stay permanently? This seems like a pretty big issue especially if there is a requirement for the file to be permanently removed once a user clicks delete.

**Comment by dchoi27** [comment]
Hey there, once a file is uploaded it stays on the IPFS network until all copies are unpinned (which is somewhat out of our control once it's there). We recommend storing only public data or encrypting data that's public.

This is in our docs and about page, but looks like you might not have seen these notes - what was your path to uploading your test file (so we know to put more obvious flags)? Thanks!

**Comment by flee541** [comment]
Yes, definitely missed this, is there a way to unpin? Alternatively, does this mean any project built on this will need to encrypted end to end? I'm currently using the web interface so none of this was apparent.

**Comment by dchoi27** [comment]
Unfortunately, unpinning across all peers in the IPFS network is outside our control. We'll add more warnings to make it more obvious - sorry for any inconvenience.

Yes, projects that are building on top of Web3.Storage that handle private data will have to consider this when building their project. We're discussing how to make this easier for users within Web3.Storage, but nothing solid on the roadmap at the moment.
