### ISSUE TITLE
Warning about deleted files still being accessible should be added to About page

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#372]
The warning about files deleted from the web3.storage UI potentially still having copies out there should be in our About page
![image.png](https://images.zenhubusercontent.com/5fa04bd64afb77249c77235b/2a07b236-6dc7-4f21-a8d7-39956f7767c2)

It's in the docs here: https://docs.web3.storage/how-tos/store/#uploading-to-web3-storage

Can we add this warning to the About page (last paragraph in the Storage Term section: https://web3.storage/about/#storage-term). Think the verbage in the docs warning is fine to use in the About page. cc @jnthnvctr if you have additional thoughts.

**Comment by alanshaw** [comment]
refs https://github.com/web3-storage/web3.storage/issues/370
