### ISSUE TITLE
Create and use Web3.Storage-focused gateway

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#381]
EPIC: Per #208, we're creating a dedicated gateway for Web3.Storage. We should ensure our all data stored on Web3.Storage is available on this gateway + serve our website from this gateway, and update our docs to recommend using it rather than the ipfs.io gateway.

**Comment by dchoi27** [comment]
Also includes this issue from NFT.Storage: https://github.com/ipfs-shipyard/nft.storage/issues/330

**Comment by olizilla** [comment]
@dchoi27 this feels like a duplicate of https://github.com/web3-storage/web3.storage/issues/208 and let's keep https://github.com/ipfs-shipyard/nft.storage/issues/330 as a seperate issue.

**Comment by olizilla** [comment]
ah i see! please make the title and description more specific on this issue. They are seperate, small pieces of work that we can tackle in the same sprint.

**Comment by dchoi27** [comment]
OK silly me - this issue is actually an Epic in Zenhub tracking #208 and #138 (the latter which I thought is why I created this issue when I opened this issue in Github, which doesn't show everything Zenhub shows).

**Comment by olizilla** [comment]
We can't pin all the data to the web3.storage gateway. It would need to be as large as the cluster. The goal is simply to have the `GET /car/:cid` requests to the http API be fetched from our gateway rather than the public one at ipfs.io.

**Comment by dchoi27** [comment]
Tracking in more general reliability epic #442
