### ISSUE TITLE
website: Unable to sign in using new magic.link sign in flow

### ISSUE THREAD

**Issue by luavixen** [web3-storage/web3.storage#382]
Users can no longer sign into the web3.storage admin panel using the new magic.link sign in flow.
 * When signing in with GitHub, the user is simply redirected back to the main page after hitting the login callback
 * When signing in with an email and magic link, an error message will be displayed no matter if the login failed or was successful

Relevant Discord messages:
https://discord.com/channels/806902334369824788/864892166470893588/878868112219463680
https://discord.com/channels/806902334369824788/864892166470893588/879056466454126592

Video demonstrating the issue:

https://user-images.githubusercontent.com/7506308/130366298-d3482718-dcbb-41b4-acfe-f7e1e75464b5.mp4

**Comment by luavixen** [comment]
Captured some errors from the console while logging in:

When logging in via email:
```
Error: failed to login user: {"code":"HTTP_ERROR","message":"Ref refers to undefined function 'createOrUpdateUser': {\"response\":{\"errors\":[{\"message\":\"Ref refers to undefined function 'createOrUpdateUser'\",\"extensions\":{\"code\":\"invalid ref\"}}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n    mutation CreateOrUpdateUser($data: CreateOrUpdateUserInput!) {\\n      createOrUpdateUser(data: $data) {\\n        issuer\\n      }\\n    }\\n  \",\"variables\":{\"data\":{\"name\":\"lua\",\"picture\":\"\",\"issuer\":\"did:ethr:0x...\",\"email\":\"lua@foxgirl.dev\",\"publicAddress\":\"0x...\"}}}}"}
```
Error body:
```javascript
{
  code: "HTTP_ERROR",
  message: `Ref refers to undefined function 'createOrUpdateUser': {
    response: {
      errors: [
        {
          message: "Ref refers to undefined function 'createOrUpdateUser'",
          extensions: { code: "invalid ref" }
        }
      ],
      status: 200,
      headers: {}
    },
    request: {
      query: \`
    mutation CreateOrUpdateUser($data: CreateOrUpdateUserInput!) {
        createOrUpdateUser(data: $data) {
            issuer
        }
    }
\`,
      variables: {
        data: {
          name: "lua",
          picture: "",
          issuer: "did:ethr:0x...",
          email: "lua@foxgirl.dev",
          publicAddress: "0x..."
        }
      }
    }
  }`
}
```

When logging in via GitHub:
```
Error: failed to login user: {"code":"HTTP_ERROR","message":"Ref refers to undefined function 'createOrUpdateUser': {\"response\":{\"errors\":[{\"message\":\"Ref refers to undefined function 'createOrUpdateUser'\",\"extensions\":{\"code\":\"invalid ref\"}}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n    mutation CreateOrUpdateUser($data: CreateOrUpdateUserInput!) {\\n      createOrUpdateUser(data: $data) {\\n        issuer\\n      }\\n    }\\n  \",\"variables\":{\"data\":{\"name\":\"Lua ✨\",\"picture\":\"https://avatars.githubusercontent.com/u/7506308?v=4\",\"issuer\":\"did:ethr:0x...\",\"email\":\"lua@foxgirl.dev\",\"github\":\"...\",\"publicAddress\":\"0x...\"}}}}"}
```
Error body:
```javascript
{
  code: "HTTP_ERROR",
  message: `Ref refers to undefined function 'createOrUpdateUser': {
    response: {
      errors: [
        {
          message: "Ref refers to undefined function 'createOrUpdateUser'",
          extensions: { code: "invalid ref" }
        }
      ],
      status: 200,
      headers: {}
    },
    request: {
      query: \`
    mutation CreateOrUpdateUser($data: CreateOrUpdateUserInput!) {
        createOrUpdateUser(data: $data) {
            issuer
        }
    }
\`,
      variables: {
        data: {
          name: "Lua ✨",
          picture: "https://avatars.githubusercontent.com/u/7506308?v=4",
          issuer: "did:ethr:0x...",
          email: "lua@foxgirl.dev",
          github: "...",
          publicAddress: "0x..."
        }
      }
    }
  }`
}
```

The problem appears to be with the `userLoginPost` and `loginOrRegister` functions in `/packages/api/user.js`, or atleast that's where the error is probably originating from.

![Screenshot from 2021-08-22 12-12-06](https://user-images.githubusercontent.com/7506308/130367207-9838f5ce-9810-46e0-bacc-f9520afa2623.png)

**Comment by olizilla** [comment]
Ok, that error message suggests that the graphql endpoint on fauna stopped recognising `createOrUpdateUser` as a valid mutation. I'm looking into it!

I am currently able to log in to web3.storage via email and github. @luavixen are you still seeing the same error when you try?

**Comment by dchoi27** [comment]
It looks like it's an issue with FaunaDB that their engineers are working on. It's unclear why some users are experiencing this issue whereas others aren't (I am but most of the team is not). They haven't given us an ETA yet but we'll keep you posted in this issue.

**Comment by luavixen** [comment]
Looks to be working properly on my end now, I'm surprised it was an issue with FaunaDB! Login still feels a bit slow, the callback takes a long time to redirect me, but I'm able to access all the content of the account page without issue.

**Comment by dchoi27** [comment]
Thanks for flagging! It works for me now too. I'll close once we have confirmation that it was due to an explicit fix deployed.
