### ISSUE TITLE
the data-sync between web3.storage and IPFS

### ISSUE THREAD

**Issue by caryyu** [web3-storage/web3.storage#383]
Hi `web3.storage` team

First of all, I would like to thank you guys having provided a cool product, which allows us to deploy our stuff more efficiently and cheaply comparing to the self-hosted servers, however, while I'm trying to use it, I'm facing a challenge that I couldn't find a direct way to migrate a group of existing CIDs from my self-hosted IPFS server since we previously have IPFS installed on our cloud servers, my questions here are:

1. Is there a direct or an easier way to migrate the existing data from IPFS to web3.storage?
2. Can we use `web3.storage` as one of the IPFS pin services in the future?

**Comment by dchoi27** [comment]
Hi there - at the moment, the easiest way is probably to upload CAR files to Web3.Storage (see #363). Directly making Web3.Storage a pinning service so you can easily pin your content is something that's potentially on the roadmap (see #289). Could you talk a little more about what your workflow would look like and what's the use case?

**Comment by caryyu** [comment]
Well I think the 2nd question can solve the 1st one, let's track on #289, which can be the easiest way for IPFS migration to web3 storage
