### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by rezarafeh** [web3-storage/web3.storage#384]
Hi
I tried to create an account but the system doesn't do anything. I tried my email as well as Github account both failed. I tried another browser an even another computer all unsuccessful. It seems the system goes through the authority checking but goes back to https://web3.storage/callback/ and the main page. When I try to login, I face with the same loop.

Cheers,
Reza

**Comment by rezarafeh** [comment]
It allowed me to login with my github account once but didn't allow me to create a token. After logging out, I'm unable to login again!

**Comment by dchoi27** [comment]
This is likely related to #382 - some users (including me) are experiencing this, and the FaunaDB team is working on a fix. Thanks for your patience!

**Comment by dchoi27** [comment]
Should be working as of yesterday - let us know if not!

**Comment by rezarafeh** [comment]
Hi David,

Yes, it is working , thanks.

Cheers,
Reza
