### ISSUE TITLE
backups: write CAR uploads to S3

### ISSUE THREAD

**Issue by mikeal** [web3-storage/web3.storage#395]
We have a lot of guarantees in our backend about replication across the IPFS cluster, and then asynchronously we have backups into Pinata, but there’s still the potential for us to lose data if there is a cluster wide issue in data that hasn’t made it to a Pinata backup.

On upload, we could write the CAR file to S3, perhaps keyed by a hash of the entire CAR file, and then we would just need to record that hash in the database for that upload.

We can go back and remove these once data is archived in enough Filecoin deals that we’re confident we don’t need them, but we can worry about that later, the first version of this can just leave them around until we decide to go through them.

**Comment by mikeal** [comment]
we need to make sure any schema changes for this make it into the Postgres refactoring.

**Comment by dchoi27** [comment]
Thanks for making this issue! Let's have a broader discussion with the team about whether this is the right backup solution.
