### ISSUE TITLE
Add support for upload sortBy pinStatus and size

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/web3.storage#398]
There are a few consideration we need to sort out and these two sortBy types were not included in #373 

Particularly in PinStatus:
- Would it be a sort by Pin status alphabetical order?
- What is the Pin Status when an upload has multiple Pins and they have different states?

For size itself, We need to list all uploads a user have sorted by size. So, we have a userId and need to get all the uploads for the user (which needs to be paginated…), and with that we need to get the Content Ref of them, get the content doc and sort by the content size, in order to than return the actual Uploads.
Sadly, we can’t do an index with two collections where we could get uploads from user and values for dagSize to sort.
So, I am not seeing any other solution except to replicate the dagSize of Content also in upload?

The size issues will be mitigated by the db migration as this will be way easier to get done

**Comment by atopal** [comment]
now handled by #652
