### ISSUE TITLE
Is possible to get the owner using the file CID? And other metadata like the created date? 

### ISSUE THREAD

**Issue by rodrigozago** [web3-storage/web3.storage#400]
How can i get the owner using the CID? Is this possible? If isn't this feature can be created? 

Thank you.

**Comment by olizilla** [comment]
No, it's not possible to get an owner. A CID is the Content ID of a file or some data. There is no concept of an owner for a CID, it's more like the hash of the content. 

You can get things like a directory listings with file sizes using IPFS, e.g.

```sh
$ ipfs dag get bafybeigpihbhozrk34bhjervdxqf576j3imfe4bd4tsnzxtpzvaeplqm6q/pics | jq                                                                                  15:17:39
{
  "data": "CAE=",
  "links": [
    {
      "Name": "dr-is-tired.jpg",
      "Size": 94482,
      "Cid": {
        "/": "bafkreiabltrd5zm73pvi7plq25pef3hm7jxhbi3kv4hapegrkfpkqtkbme"
      }
    },
    {
      "Name": "not-distributed.jpg",
      "Size": 414201,
      "Cid": {
        "/": "bafkreidrsgkip425zjamc3pvmil7dpatss7ncedyaatepxyionxi7py5fq"
      }
    },
    {
      "Name": "youareanonsense.jpg",
      "Size": 55415,
      "Cid": {
        "/": "bafkreiaqv66m5nd6mwgkk7h5lwqnjzj54s4f7knmnrjhb7ylzqfg2vdo54"
      }
    }
  ]
}
```

**Comment by rodrigozago** [comment]
I uploaded the same file using two different accounts, and the resulted timestemp is diferent for the two accounts, how this works? Is the CID related to the Web3 user account only internally for the user? 

I want to be sure of the ownership (IP) of the file uploaded, and I asked myself if is this possible using the Filecoin blockchain and the Web3 infrastructure.

 I was thoughing using an ethereum smartcontract to create and add a digital certificate to the blockchaing, but if i could relate the CID using the Filecoin blockchain, i could ommit the use of other blockchain, relating the Web3 user to a file.
This is why i asked if i can query the first user that uploaded the file by the CID.

Thank you for the attention.
