### ISSUE TITLE
IPFS CID v0 to WEB3 Storage CID v1 migration

### ISSUE THREAD

**Issue by AugustoL** [web3-storage/web3.storage#410]
I have to migrate or pin content form IPFS to WEB3 storage I want to reuse all the existent data that I have in IPFS. How do I do it? Can I write an script for it if I have the IPFS hashes and a WEB3 Storage api key?

**Comment by atopal** [comment]
You should be able to do that with the pinning API that we'll hopefully land soon.

**Comment by atopal** [comment]
see https://github.com/web3-storage/web3.storage/issues/289
