### ISSUE TITLE
delete’s don’t reflect in quota

### ISSUE THREAD

**Issue by mikeal** [web3-storage/web3.storage#413]
From Discord:

“I understand when a file is "deleted" it might still be pinned and will still be included the filecoin deals until they expire, but shouldn't the quota in the account page decrease the amount of storage used? I deleted some files and only have a single 48KB file remaining, but account usage still says ~19MB.”

https://discord.com/channels/806902334369824788/864892166470893588/880810832571797524

## next step
- [x] check to confirm post migration completetion that this is no longer an issue

**Comment by atopal** [comment]
We need to follow up on whether this is intermittent or consistent and where it comes from.

**Comment by atopal** [comment]
Confirmed that this is not an issue anymore.
