### ISSUE TITLE
status api lists undialable peer ids

### ISSUE THREAD

**Issue by andrew** [web3-storage/web3.storage#414]
url: https://api.web3.storage/status/bafybeibwtnukjkvxkbh3r4gza274w6qfomquekqqf7wddezytz5csylnja

response:
```json
{
  "cid": "bafybeibwtnukjkvxkbh3r4gza274w6qfomquekqqf7wddezytz5csylnja",
  "created": "2021-08-27T15:25:42.720612Z",
  "dagSize": 11245446,
  "pins": [
    {
      "status": "Pinned",
      "updated": "2021-08-27T15:28:54.410267Z",
      "peerId": "12D3KooWJeRQfPbiv5U2RqQ9yK3qijbNxKarKEGLMkGrfXJuZ2Bo",
      "peerName": "web3-storage-sv15-2",
      "region": "US-CA"
    },
    {
      "status": "Pinned",
      "updated": "2021-08-27T15:28:54.410267Z",
      "peerId": "12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV",
      "peerName": "web3-storage-dc13",
      "region": "US-DC"
    },
    {
      "status": "Pinned",
      "updated": "2021-08-27T15:28:54.410267Z",
      "peerId": "12D3KooWLWFUri36dmTkki6o9PwfQNwGb2gsHuKD5FdcwzCXYnwc",
      "peerName": "web3-storage-am6-2",
      "region": "NL"
    }
  ],
  "deals": []
}
```

I tried to connect to the listed peer ids using my ipfs node and all three failed with the same error:

```
$ ipfs swarm connect /p2p/12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV
Error: connect 12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV failure: routing: not found
```

The peer ids that do have the content according to the dht:

```
$ ipfs dht findprovs bafybeibwtnukjkvxkbh3r4gza274w6qfomquekqqf7wddezytz5csylnja
12D3KooWEDMw7oRqQkdCJbyeqS5mUmWGwTp8JJ2tjCzTkHboF6wK
12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien
12D3KooWSnniGsyAF663gvHdqhyfJMCjWJv54cGSzcPiEMAfanvU
12D3KooWNuoVEfVLJvU3jWY2zLYjGUaathsecwT19jhByjnbQvkj
12D3KooWPdXVdo7b1GUf4yWGPAtphDdqMby4bYh9q1csYniHAZKx
```

**Comment by vasco-santos** [comment]
In this case

The PeerId here is the Cluster PeerId and not the IPFS PeerId which address can be found at https://github.com/web3-storage/web3.storage/blob/main/PEERS.

For instance, in this example `12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV` is the cluster ID of `web3-storage-dc13`, but its IPFS peerId is `12D3KooWSnniGsyAF663gvHdqhyfJMCjWJv54cGSzcPiEMAfanvU`

**Comment by vasco-santos** [comment]
Created https://github.com/ipfs/ipfs-cluster/issues/1554 to see if we can include the PeerId of the actual IPFS Node. An alternative is to perform a follow up cluster request per upload and get the list of peers of a cluster and inspect the response.

Note: This will need a small migration window as we currently store the PeerId of the Cluster in our Database and previous rows would be linked with the old one (per SQL ON CONFLICT clauses)

**Comment by alanshaw** [comment]
[Maintenance scheduled to fix this on 2022-02-24 @ 14:30 UTC](https://status.web3.storage/incidents/sgfjvc50gm61)
