### ISSUE TITLE
TypeScript typings for WebFile not working correctly

### ISSUE THREAD

**Issue by realandrew** [web3-storage/web3.storage#424]
Per discussion in [Discord](https://discord.com/channels/806902334369824788/864892166470893588/882328626710851644), the following code should be valid (the function isn't fully implemented, but this shouldn't cause errors)
```js
async getFilesByCID(cid) {
    let res = await client.get(cid);
    const files = await res.files();
    for (const file of files) {
        file.stream();
    }
    return files;
}
```
But TypeScript throws an error here saying `Property 'stream' does not exist on type 'Web3File'. ts(2339)`. And trying to run the code anyways causes compilation to fail. For some reason, TypeScript isn't picking up the correct typings for Web3File.

My repository is currently closed-source, but I'm happy to share relevant snippets to help debug this problem.

Not sure it matters but here's my tsconfig.json
```json
{
   "compilerOptions": {
      "lib": [
         "es5",
         "es6",
         "esnext"
      ],
      "target": "es6",
      "module": "commonjs",
      "moduleResolution": "node",
      "esModuleInterop": true,
      "outDir": "./build",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "sourceMap": true
   }
}
```
I'm on Windows 10 and using Web3.Storage version 3.3.0 and updated to 3.3.1 (same issue still).

The other packages I'm using are
```json
"dependencies": {
    "axios": "^0.21.1",
    "blake3": "^2.1.4",
    "cors": "^2.8.5",
    "cryptr": "^6.0.2",
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "express-fileupload": "^1.2.1",
    "express-handlebars": "^5.3.3",
    "express-session": "^1.17.2",
    "jsonwebtoken": "^8.5.1",
    "morgan": "^1.10.0",
    "pg": "^8.7.1",
    "reflect-metadata": "^0.1.10",
    "sharp": "^0.29.0",
    "typeorm": "^0.2.37",
    "web3.storage": "^3.3.1"
 },
 "devDependencies": {
    "@types/express-fileupload": "^1.1.7",
    "@types/express-session": "^1.17.4",
    "@types/node": "^8.0.29",
    "@types/sharp": "^0.28.5",
    "nodemon": "^2.0.12",
    "ts-node": "3.3.0",
    "typescript": "3.3.3333"
 }
```
I'm happy to provide any other info that will help with solving this issue.

**Comment by yusefnapora** [comment]
Just noting that I see the same thing. If I click through in VSCode to the `Web3File` definition, it seems to think it's inheriting from the `File` definition in the main `typescript` node module, not `std-file`:

<img width="843" alt="Screen Shot 2021-08-31 at 4 53 26 PM" src="https://user-images.githubusercontent.com/678715/131574447-c47300c7-f9f5-469d-bd94-99fc776fadca.png">

So it can't find the `.stream` method. Not sure yet why it doesn't get the `File` definition from `std-file`, but I may dig a bit more.

**Comment by alanshaw** [comment]
Note: `.stream()` is a method on `Blob`, which `File` inherts from.

**Comment by alanshaw** [comment]
Quick fix is to add "DOM" to your `compilerOptions.lib`

**Comment by realandrew** [comment]
Thanks, that does fix the issue. However, it does cause a new issue with Web3Storages file, and even if I import under a different name like import { File as WebFile } from 'web3.storage' it still causes problems..
```js
makeFileObjects(obj, filename) : typeof File {
    const buffer = Buffer.from(obj);
    return new File([buffer], filename); // import { File } from 'web3.storage';
}
```

Error: `Property 'prototype' is missing in type 'File' but required in type '{ new (fileBits: BlobPart[], fileName: string, options?: FilePropertyBag): File; prototype: File; }'.ts(2741)
platform.d.ts(9, 5): 'prototype' is declared here.`

**Comment by realandrew** [comment]
Disregard that last message, it was due to setting return type to typeof File instead of just File.

**Comment by realandrew** [comment]
So it appears though adding DOM got rid of my error in Visual Studio Code, the TypeScript compiler is still throwing an error `Property 'stream' does not exist on type 'Web3File'. (2339)`.

**Comment by alanshaw** [comment]
hmm, are you sure you're compiling using the `tsconfig.json` you added the DOM lib to? `tsc --build tsconfig.json`?

**Comment by realandrew** [comment]
Hmm, it appears when I build with that command it works, it's ts-node acting weird that still throws the error. I'll close this issue since it's no longer related to web3.storage, but if anyone has an idea of why ts-node is throwing an error when tsc build isn't please let me know.

**Comment by realandrew** [comment]
TSC does throw 10 errors but the build seems to work even with them, they're all from web3.storage's interface.d.ts file.
`node_modules/web3.storage/dist/src/lib/interface.d.ts:1:13 - error TS1005: '=' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:1:34 - error TS1005: ';' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:2:13 - error TS1005: '=' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:2:26 - error TS1005: ';' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:3:1 - error TS1128: Declaration or statement expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:3:13 - error TS1005: ';' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:4:13 - error TS1005: '=' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:4:32 - error TS1005: ';' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:5:13 - error TS1005: '=' expected.`
`node_modules/web3.storage/dist/src/lib/interface.d.ts:5:35 - error TS1005: ';' expected.`

Also if anyone else gets a similar issue with ts-node in the future, you can work around it by supplying `--disableWarnings` to ts-node. Not the best solution, but it works until a better solution is found.
