### ISSUE TITLE
Nowrap for timestamp, CID and pin status columns in files listing

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#430]
The behavior looks correct to me, but you might have more context for this @alanshaw?

**Comment by alanshaw** [comment]
<img width="200" alt="Screenshot 2021-09-01 at 15 46 37" src="https://user-images.githubusercontent.com/152863/131868146-8b5ea678-de25-4a8c-894b-e93800e70cbf.png">

<img width="157" alt="Screenshot 2021-09-01 at 15 48 09" src="https://user-images.githubusercontent.com/152863/131868158-0c1aa27e-ac93-4387-8601-a264f7131887.png">

<img width="118" alt="Screenshot 2021-09-01 at 15 50 13" src="https://user-images.githubusercontent.com/152863/131868173-997b2666-ac1a-4cff-aa6b-dde525d56338.png">

**Comment by olizilla** [comment]
more generally the upload table needs more work to be useful. column widths need to be constrained and content needs to be truncated where sensible. This is what i see on my account, and it's not useable.

<img width="1504" alt="Screenshot 2021-09-03 at 10 18 20" src="https://user-images.githubusercontent.com/58871/131982331-d0c97110-0aa8-45a8-8cd0-5f8052f3ed3f.png">
