### ISSUE TITLE
Fix layout of top buttons on table layout on mobile

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#431]
The line breaks create a weird button for "upload more files" and the spacing is off.
<img width="418" alt="Files_-_Web3_Storage" src="https://user-images.githubusercontent.com/557852/131845067-9f6401b2-3d11-40ab-bb62-c4932cb5280a.png">

@alanshaw

**Comment by alanshaw** [comment]
<img width="269" alt="Screenshot 2021-09-01 at 15 48 44" src="https://user-images.githubusercontent.com/152863/131868262-758e4727-8849-4a92-8f69-54e5a9fb910a.png">
