### ISSUE TITLE
Fix alignment and text size of footer items on mobile

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#432]
I think the alignment is about the left padding.

<img width="467" alt="Files_-_Web3_Storage" src="https://user-images.githubusercontent.com/557852/131845205-80ba6723-e4ba-4670-91e0-925088489d49.png">

@alanshaw you might have more context for this.

**Comment by alanshaw** [comment]
"Made by..." seems too big also!

**Comment by rafaelramalho19** [comment]
This is already fixed in the latest main version by #251
