### ISSUE TITLE
Make delete button same size as copy button on tokens listing page

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#433]
Currently the button size is dictated by the text length, and it's uneven. @alanshaw for more context potentially.

**Comment by alanshaw** [comment]
<img width="236" alt="Screenshot 2021-09-01 at 15 51 38" src="https://user-images.githubusercontent.com/152863/131868335-42c92daa-8f0b-49e1-8631-5aec34fd15d6.png">
