### ISSUE TITLE
Define the database schema in SQL

### ISSUE THREAD

**Issue by Gozala** [web3-storage/web3.storage#439]
Define the database schema in SQL. Where sensible, match the schema that nft.storage is migrating to https://github.com/ipfs-shipyard/nft.storage/pull/395

This work is happening in https://github.com/web3-storage/web3-schema

### Normalisations to apply:
- [x] Singularize table names
- [x] Rename `auth_tokens` -> `auth_key`
- [x] Normalized cid field to V1 base32 encoded TEXT (https://github.com/web3-storage/web3-schema/pull/4)

## It's done when...

There exists an SQL file in the the db project in this repo, along with a README that explains the key decisions, and documented steps to apply it to a postgres instance.

**Comment by alanshaw** [comment]
We're specing this out in https://github.com/web3-storage/web3-schema

**Comment by Gozala** [comment]
Should I move all the issues there or do we keep them here ?

**Comment by olizilla** [comment]
I've consolidated the action items related to defining the web3.storage schema into this issue. The work can continue in https://github.com/web3-storage/web3-schema and we'll use this issue for tracking schema design issues.
