### ISSUE TITLE
Migrate data from fauna to Postgres

### ISSUE THREAD

**Issue by Gozala** [web3-storage/web3.storage#440]
Once #439 is ready and db is up, we can migrate data from fauna to Postgres.

## It's done when...

An comand exists that we can run to extract data from Fauna for; 
- documents created after a given time, or from the first one. (we want to be able to do a sync up to a specific time, flip the fauna db in to read-only mode, and then quickly sync an new documents that were created since the last sync)
- from all the relevant collections (ones that would be populated by dagcargo will be ignored)

and write it to a postgres instance 
- that the caller can chose which intances of fauna and postgres to connect to.
- that has the schema defined in #439

**Comment by Gozala** [comment]
I suggest to use same approach here as https://github.com/ipfs-shipyard/nft.storage/issues/381

**Comment by olizilla** [comment]
We should consider whether writing to an intermediate format would be helpful here. Postgres is very good at batch writes via the `COPY` where you pass it a csv or similar. https://www.postgresql.org/docs/current/sql-copy.html

It's really fast and was used to good effect in Sentinel work that was dealing with huge amounts of chain data.
