### ISSUE TITLE
Show the user when they are not on the first page of the uploads list

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#457]
As @rafaelramalho19 points out in https://github.com/web3-storage/web3.storage/pull/423#issuecomment-912603377 ... the uploads table can be long. If you paginate to older items, it is not clear when you scroll to the top of the table that you are still looking at older items. 

Clicking the refresh button when looking at older items will not show you a change... we should show more clearly that you are digging in the back catalog, and consider deactivating the refresh button, or chaning it so that it jumps you to the latest... it could be a "show me the latest" button instead. 

Either way, we should make it much clearer so the user knows they aren't going to see new things when looking at old things

**Comment by vasco-santos** [comment]
We moved out of fauna to postgres and now we can easily achieve this by actual pagination. Closing this as we already have a generic issue to improve upload listing page: https://github.com/web3-storage/web3.storage/issues/652
