### ISSUE TITLE
[Research] Understand Cluster scaling issues and have plan for scaling

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#475]
We should do digging and have the conversations needed to better understand what kinds of Cluster scaling issues we might face (at what thresholds of data volume - total and by user, what magnitude of request volumes we might start to see trouble, etc.), and our playbook for scaling in each situation. 

@alanshaw mentioned that we could spin our wheels a lot on this sort of research, and there will be nuances when we face these kinds of issues in practice, but we should probably at least a directional understanding, thresholds, and plans in place for scaling issues.

**Comment by olizilla** [comment]
A small step would be to experiment with deploying many smaller cluster nodes on demand to a cloud vm provider. A pain point we have is the turn-around time and potential for not being able to get additonal instances of the physical machines we currently deploy to. If we can significantly shrink the deploy time for additonal nodes we can ease that pain.

Most folks dont have this problem any more as they use virtual machines... if we can write some ansible / terraform / k8s to deploy many smaller cluster nodes, and provision more on demand. We need to take care that the persitance story for the cloud provider is guarantteed and backed up.

**Comment by atopal** [comment]
We decided to go with scaling in AWS.
