### ISSUE TITLE
Monitoring and alerting when data stored for individual users reach certain thresholds

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#479]
Regardless of plans moving forward with data thresholds per user, we should be tracking this to monitor when we need to scale our Cluster, when we want to do some digging to detect abuse, etc.

cc @olizilla for adding to the monitoring / alerting Epic

**Comment by atopal** [comment]
David, we have alerting disc space in cluster, is that enough? We have rate limiting for individuals and that ensures that no single user can upload too much too fast? Otherwise, what do we want to measure here?

**Comment by dchoi27** [comment]
We should know who our biggest users are and how much data they're uploading, especially if we want to put constraints around data tiers (even if these constraints are soft). After the migration is done it should be a pretty simple query - at the very generating a weekly table tracking this state (if we go with an Airtable for the request for more storage form, we can integrate them).
