### ISSUE TITLE
Multiple file upload in WebUI

### ISSUE THREAD

**Issue by capiflvcko** [web3-storage/web3.storage#487]
It's kinda a slow process transferring multiple files one by one

**Comment by vasco-santos** [comment]
Hey @capiflvcko 

Can you provide us more details?

- What environment you are using
- are you using the JS client, the website, the CLI
- what are the sizes of the files you are uploading

**Comment by capiflvcko** [comment]
Yes so when I go to upload a file it only give me the option to select one file at a time. it will be easier to upload files if I can select multiple files to upload

**Comment by olizilla** [comment]
@capiflvcko agreed, the website should let you upload more than one file. In the meantime have you tried the command line tool or the js-client? you can install the command line tool and upload a directory of files in one go. See: https://www.npmjs.com/package/@web3-storage/w3

**Comment by Abul22** [comment]
@capiflvcko 
This allows multi file upload.
https://bafybeigxve4jcuc5o5cq3sjifgw5ukzteb23xsqalzjltavk5bzn4bi3w4.ipfs.dweb.link/

You can use this -- or scape the sources and self host / rewrite the paths in index from /assets/ to just ./ and upload to your own web3.

**Comment by capiflvcko** [comment]
> @capiflvcko This allows multi file upload. https://bafybeigxve4jcuc5o5cq3sjifgw5ukzteb23xsqalzjltavk5bzn4bi3w4.ipfs.dweb.link/
> 
> You can use this -- or scape the sources and self host / rewrite the paths in index from /assets/ to just ./ and upload to your own web3.

thank you it worked

**Comment by zebateira** [comment]
I'm working on this. It's not a simple "allow multiple files to be selected/dropped", since the frontend upload logic needs to accommodate for uploading multiple files.

**Comment by zebateira** [comment]
Question: what limit should be enforced when uploading multiple files? Just to avoid situations where the user might select hundreds of files.

**Comment by Abul22** [comment]
> Question: what limit should be enforced when uploading multiple files? Just to avoid situations where the user might select hundreds of files.

Depends what you're trying to prevent? Is it to prevent the user from abusing the service? Then it won't stop it as they can do over different instances... Would need to rate limit server side the account.

If its just for protecting the user from shooting self in the foot not realising 400gb will take forever and possibly fail - then just an alert would suffice?

P.S Are you looking into it, in a way that will stream the files to be uploaded rather than a single bulk that seems to have issues with some browers cache limits / computer ram limits?

**Comment by capiflvcko** [comment]
Also it would be cool if we could make a virtual drive or local drive so you can access it like an external drive

**Comment by vasco-santos** [comment]
We will be merging #567 soon to allow this use case
