### ISSUE TITLE
Make it a PWA and Share Target

### ISSUE THREAD

**Issue by rafaelramalho19** [web3-storage/web3.storage#498]
- We should make web3.storage a PWA so we can use it as a Share Target for mobile phones. That way, users can quickly share files directly from their file explorer/gallery, helping us get users that would normally just upload that file to another platform. 
- More info at: https://web.dev/web-share-target/

---
- Making this app a [PWA has other benefits too](https://love2dev.com/pwa/benefits/).

**Comment by atopal** [comment]
Turns out that this is more involved than we originally thought. Closing for now
