### ISSUE TITLE
Total storage is miscalculated

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#500]
At least one user is seeing the wrong amount displayed on the website.
![Screenshot_20210928-182835](https://user-images.githubusercontent.com/557852/135092475-6084b05c-30f8-4330-9a1e-db053ff0e730.jpg)

**Comment by atopal** [comment]
Yes, it should be.

**Comment by atopal** [comment]
The real value should have been about 900GB according to the user.

I can't reproduce this, just tried uploading a file and it seems like the size is calculated correctly. I'm below 1GB.

**Comment by mehulagg** [comment]
Now, its working fine.

**Comment by olizilla** [comment]
we landing a fix to pre-calulate the entire dag size from the root block of a CAR, even if it's a partial, which is good, but it also ment we could end up double counting the entire dagSize for partial cars. This is fixed and deployed in #501
