### ISSUE TITLE
`502 Bad Gateway` When Using `client.get` in Local Development

### ISSUE THREAD

**Issue by frankfka** [web3-storage/web3.storage#510]
I have the following piece of code:

```
const fetchResponse = await web3StorageClient.get(cleanedCid);

if (fetchResponse == null || !fetchResponse.ok) {
  logger.warn(
    'Error response from web3 storage client',
    fetchResponse?.status,
    fetchResponse?.statusText
  );
  return;
}
```

In local development ("web3.storage": "^3.3.2" & "next": "11.1.2") - I get the response: `Error response from web3 storage client 502 Bad Gateway`. An example CID: `ipfs://bafkreifnzt6bwwcorejos4pk7sfyudj5wxr6svhldlgpwltoddlqqey3fe`

Interestingly, this doesn't happen in production deployments (only when running `next dev` locally).

**Comment by atopal** [comment]
Let's reopen, if this comes again.
