### ISSUE TITLE
home screen and files screen should both support dnd uploads

### ISSUE THREAD

**Issue by autonome** [web3-storage/web3.storage#521]
Eg, i kept trying to drop a file here:

<img width="604" alt="Screen Shot 2021-10-07 at 9 48 58 AM" src="https://user-images.githubusercontent.com/50103/136410169-9fc8fc59-f804-4c7a-8c14-8452d80df38f.png">

**Comment by vasco-santos** [comment]
This will be closed by https://github.com/web3-storage/web3.storage/pull/567 once it gets merged

**Comment by dchoi27** [comment]
@dashcraft should this be closed?

**Comment by JeffLowe** [comment]
yes
