### ISSUE TITLE
Create rate limits

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#535]
Sister issue to: https://github.com/ipfs-shipyard/nft.storage/issues/603

**Comment by atopal** [comment]
Discussed in Slack. Hugo will sync with Oli.

**Comment by atopal** [comment]
@hugomrdias has this been done already? Can we close this?

**Comment by hugomrdias** [comment]
no

@vasco-santos @alanshaw let get the rate limits enabled for web3

**Comment by vasco-santos** [comment]
@atopal I synced with @hugomrdias today to get the context and already added them into the worker. We might to some tweaks depending on usage over time, but we can close the issue

**Comment by vasco-santos** [comment]
I disabled rate limits. We need to find a solution for https://github.com/web3-storage/add-to-web3 as this was becoming an issue there, given same IP was doing multiple deploys fir many users, resulting in blocks. A naive solution can be a backoff retry in the action

**Comment by dchoi27** [comment]
Rate limits enabled, add to docs
