### ISSUE TITLE
Publish list of peerids

### ISSUE THREAD

**Issue by mikeal** [web3-storage/web3.storage#548]
We have a growing list of IPFS nodes that we’re using, all of which are peered with the Gateway.

If other gateways or services want to peer with these nodes because they are using or interoperating with our service i see no reason not to let them do that.

It would be great if we published this list, maybe just in a GitHub text file, for all the dotStorage IPFS nodes.

**Comment by dchoi27** [comment]
@alanshaw see any pitfalls here? Would they potentially put undue load on our nodes?

**Comment by yusefnapora** [comment]
We have a list at https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list that we should add our nodes to also.

**Comment by dchoi27** [comment]
Submitted to this list: https://github.com/ipfs/ipfs-docs/pull/987

@yusefnapora can we also add a list to the docs page?

**Comment by alanshaw** [comment]
https://github.com/web3-storage/web3.storage/blob/main/PEERS
https://github.com/nftstorage/nft.storage/blob/main/PEERS
