### ISSUE TITLE
Add admin website for web3.storage

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#563]
## User Story
As an admin user, I want an admin area on the website, so I can in the future manage users, turn and off features and administer the site. 

## Scope:  
* Unified admin for both web3 and nft.storage.  (But initial implementation needed only for web3) 

## Rough Approach:
* spin up next.js site, 
* confirm UI then connect to cloudflare (hugo to sync with Aaron to provide access)
* house codebase in the nft.storage github organization (per Mikel on 11.19)

AC:
- [ ] admins can see admin area
- [ ] users who have access to cloulflare worker we create for this can access the admin website (POSSIBLY using the cloudflare teams feature)

Linked to #536
Linked to nft.storage issue https://github.com/nftstorage/nft.storage/issues/606
Impacted by https://github.com/nftstorage/nft.storage/issues/826

**Comment by JeffLowe** [comment]
FYI, check in with Alan mid next week on progress to determine whether we need to split task up more (leading into next week's cycle goal)

**Comment by JeffLowe** [comment]
@alanshaw Are there any preferences in auth to use for the admin?  Apparently we still need to pick an auth solution even if that's a One Time Pin to integrate with Cloudflare for Teams: https://developers.cloudflare.com/cloudflare-one/identity

**Comment by JeffLowe** [comment]
Per convo with Mikel today, we'll house this codebase in nft org.  Thus to keep tasking DRY, eliminating the tasks here in web3 and leaving only the tasks in nft org.  First release will still provide ban key capabilities for web3.
