### ISSUE TITLE
Uploading from the browser using a signed link to avoid API keys leakage

### ISSUE THREAD

**Issue by jurgenwerk** [web3-storage/web3.storage#571]
I'd like to support uploading to web3.storage straight from the browser, but I don't want to leak my web3.storage client keys. Is there a way I can run a server which responds with a temporary set of keys, a signed link or a one time link to be used for the upload from the browser?

**Comment by atopal** [comment]
this is now handled in #577

**Comment by jurgenwerk** [comment]
Awesome!
