### ISSUE TITLE
Cron Pins Failing

### ISSUE THREAD

**Issue by Meowcat285** [web3-storage/web3.storage#589]
Hi, I noticed that the cron pins action is failing and files are not showing as pinned on the dashboard or API. It seems to be some sort of issue with FaunaDB. As you can see here ([https://github.com/web3-storage/web3.storage/runs/4098405958?check_suite_focus=true](here)) its failing. I also uploaded the log archive to this issue.
[logs_31113.zip](https://github.com/web3-storage/web3.storage/files/7470864/logs_31113.zip)

**Comment by vasco-santos** [comment]
Hey @Meowcat285 
Thanks for reaching out, We already reached out to FaunaDB and they are diagnosing the problem. Hope we can get it back as soon as possible

**Comment by alanshaw** [comment]
This is now resolved @vasco-santos correct?

**Comment by atopal** [comment]
Reopen, if still an issue.
