### ISSUE TITLE
[Testing] DB FDW with local DAG Cargo instance

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/web3.storage#590]
We need to use DAG Cargo for DB testing, so we should just have a Docker setup for it instead of relying on a deployed one.

**Comment by alanshaw** [comment]
Are you saying run a dagcargo instance? It might be better to run the dagcargo schema on the local DB and insert some tets data rather than setup the foreign data source and run another postgres. We could maybe pull the SQL from the dagcargo repo?
