### ISSUE TITLE
invalid upload record

### ISSUE THREAD

**Issue by qxxiao** [web3-storage/web3.storage#593]
Accidentally added a file, there are some errors, can't delete the file in web3.storage, and there are a lot of Storage Providers node records, how can I fix this problem, will File in web3.storage to be able to delete the record correctly?

![image](https://user-images.githubusercontent.com/43007848/140605688-0f0dd335-ba9e-482a-b449-115027935bb8.png)

**Comment by atopal** [comment]
Hey there, can you delete it now? Can you give us the CID to check on this?

**Comment by atopal** [comment]
@ribasushi cc, any idea why we have so many deals for this one CID?

**Comment by ribasushi** [comment]
@atopal `bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku` is the CID for raw-bytestring-of-length-0. It shows up in a *lot* of dags. At some point I added an escape specifically for this one, so it doesn't keep getting "listed". But it continues being included in more and more deals by virtue of being part of many dags.

**Comment by ribasushi** [comment]
@hugomrdias @vasco-santos @alanshaw note that it *might* make sense to limit the returned set to some number to work around cases like this. E.g. license files end up in *a lot* of deals too ;)

**Comment by atopal** [comment]
Thanks Riba. We'll track that work here: https://github.com/web3-storage/web3.storage/issues/665
