### ISSUE TITLE
Listing user uploads could be faster

### ISSUE THREAD

**Issue by andrew** [web3-storage/web3.storage#61]
The endpoint listing user uploads seems to be a little slow, could be because of the pagination options passed causing missed indexes perhaps?

Url: https://api-staging.web3.storage/user/uploads?before=2021-07-12T13%3A26%3A44.976Z&size=25
Number of files listed in response: 1
Avg time to load in firefox: ~1 second

Related to performance research in #94

**Comment by vasco-santos** [comment]
We moved to Postgres and this should not be the case anymore. Closing this, but feel free to reopen if this is still a problem

**Comment by andrew** [comment]
It's actually much worse for my account now:
```
$ time curl -H 'Accept: application/json' -H "Authorization: Bearer TOKEN" https://api.web3.storage/user/uploads
$ [jsonresultshere]
real	0m7.084s
user	0m0.022s
sys	0m0.010s
```

**Comment by orvn** [comment]
@dchoi27 I think this might be mislabeled/an issue outside of `stack/website`? 

(On the frontend, #1341 should help with displaying the list more quickly, but that's not directly related to this issue)

**Comment by drewdelano** [comment]
I think this a missing index issue
