### ISSUE TITLE
File queueing for 7 days

### ISSUE THREAD

**Issue by Trott** [web3-storage/web3.storage#613]
I have a file I uploaded that has been in the "Queueing" state for 7 days. The tooltip seems to suggest it shouldn't be longer than 48, so I think this is a bug? (If not, then I guess the tooltip should be updated/clarified so I know to be more patient when I read it?)

I try to download the file with IPFS desktop client and the public gateway and both fail.

The CID in question is bafybeig4yenjcrwd4eafa7tsfn7pxn2xjl7zuvpojcpok2arxpt43pw4ba. It was uploaded to web3.storage on November 5 and is still in the queueing state today (November 12).

**Comment by vasco-santos** [comment]
Thanks for reaching out. Cluster is claiming `PinError` on our cron job that checks pin status updates: 2021-11-23T08:56:42.269Z pins:updatePinStatuses 🙅 bafybeig4yenjcrwd4eafa7tsfn7pxn2xjl7zuvpojcpok2arxpt43pw4ba@12D3KooWHdBjmicdXu5X57mQ65oBpfy4p3ca5p31kfJT9FSUFu3P: No status change (PinError)

I will look into what can be done here

**Comment by vasco-santos** [comment]
@Trott 

Something odd happened and the upload likely failed. How did you upload this? Via website?

I tried to trigger IPFS Cluster to pin the content again, it can find the root block CID but it errors then. Can you upload it again?

**Comment by Trott** [comment]
> How did you upload this? Via website?

Yes, via website.

> Can you upload it again?

That file is now obsolete now so I'm OK to just let it go at this point.
