### ISSUE TITLE
This doesn't really work out of the box if end users follow the instructions on web3.storage website

### ISSUE THREAD

**Issue by bitcoinmeetups** [web3-storage/web3.storage#614]
Hello,

I'm MB. A very nice and polite guy.

This doesn't really work out of the box if end users follow the instructions on web3.storage website.

Many error messages. Tried both with the simple one (store.mjs) and the slightly more involved from the docs where you make a directory first.

A variety of error messages including:

"Module not found"
"ERR_Require_ESM"

And others.

Please check. I have tried this on several occasions on two different computers. I mean it's good if it actually works oout of the box for average users. NFT.storage works out of the box using the instructions on the website but web3.storage just don't in my experience.

Oh and a Python version would be good as well. In general things usually run more smoothly with Python than with JavaScript.

**Comment by atopal** [comment]
Hi there! You'll need Node version 14 or higher and NPM version 7. Can you please verify? Also, we can provide much better help in our interactive help channels, you can find them here: https://docs.web3.storage/community/help-and-support
