### ISSUE TITLE
Implement Postgres optimization configuration changes (replicated from nft)

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#615]
Immediate postgres DB optimizations were completed for nft.storage with https://github.com/nftstorage/nft.storage/pull/1664 
The task here is to complete these same/similar optimizations in Web3, following the pattern set with the nft work. 

See Initiative Document for greater context:  https://www.notion.so/Postgres-scaling-optimizations-4f560776d6384c58895b5890b9c40294

**Comment by atopal** [comment]
@dchoi27 do you have more information about this issue? Maybe AC's?

**Comment by vasco-santos** [comment]
I think this will come from changes made in nft.storage over the next weeks and adapted here

**Comment by JeffLowe** [comment]
Per @hugomrdias this one is currently blocking us from achieving #1209

**Comment by dchoi27** [comment]
Potato has someone who'll spend a few days next week landing this!
