### ISSUE TITLE
React app build folder returning a blank page

### ISSUE THREAD

**Issue by mh13test** [web3-storage/web3.storage#616]
Hello,

After uploading the build folder of a compiled react app on web3.storage, when I try to access it I get a blank page. I would like to know how I can solve that issue please.

Best regards

**Comment by mh13test** [comment]
Anyone (the team) could get in touch? I'm doing something wrong probably but I would like to know what so I can use your service. Thanks!

**Comment by atopal** [comment]
Are you getting any error messages? Can you also share the code?

**Comment by mh13test** [comment]
Thank you for your interest. When I check the browser console here is what I see:

![error](https://user-images.githubusercontent.com/93112873/142738291-56e34c88-c1ca-449d-aa92-b6fef49cf3a6.PNG)

**Comment by vasco-santos** [comment]
Hello @mh13test 

I think that the MIME Type error is happening because the css path is not correct. Likely you are not using relative paths and when using the build folder these paths break. Can you confirm you are using relative paths for the CSS files?

**Comment by atopal** [comment]
Let's reopen, if the above is not the cause.
