### ISSUE TITLE
Some files stay queued instead of being pinned

### ISSUE THREAD

**Issue by capiflvcko** [web3-storage/web3.storage#657]
some of my files get pinned and some just stay queued. also if it not pinned is possible the content could get deleted?

**Comment by atopal** [comment]
We always save your files, even before they are pinned, but how long did it take for them to get pinned?

**Comment by vasco-santos** [comment]
> Some of my files been in the queue for months

Can you share CIDs of them to have a look

> I had more files stored then is being showed and then my used gigs number has changed since your last recent maintenance update

Can you share your login details? 

Please join Filecoin slack https://docs.filecoin.io/community/chat-and-discussion-forums/ and share with me in private and I will have a look on these

**Comment by atopal** [comment]
Please reopen, if this is still an issue.
