### ISSUE TITLE
Http API to Delete shows ERROR_MAGIC_TOKEN_REQUIRED Error

### ISSUE THREAD

**Issue by MdYeasinSamadArnob** [web3-storage/web3.storage#664]
I was trying Http Api to fetch and Delete the file using CID but fetch was getting response but Delete throws an error.

The server Delete request was made here:

 https://api.web3.storage/user/uploads/:cid

Response were: 
{
    "code": "ERROR_MAGIC_TOKEN_REQUIRED",
    "message": "Must be logged in with magic.link"
}

**Comment by vasco-santos** [comment]
Hello @MdYeasinSamadArnob 
We currently do not support this via HTTP API, but only via the website as you can see in https://github.com/web3-storage/web3.storage/tree/main/packages/api#-delete-useruploadscid `👮 Magic Token (admin operations)`
However, we want to make this possible and you can follow https://github.com/web3-storage/web3.storage/issues/314 to track progress on this.
