### ISSUE TITLE
Cap listing of storage providers

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#665]
Some files (like license files) are uploaded very frequently. When we list them in the WebUI they show up as being stored in a large number of storage deals. While it's true, it seems confusing to users. We should cap the listing to a small number, eg.5. Here's an example: 
![grafik](https://user-images.githubusercontent.com/557852/142624394-2260f3eb-311d-4947-be0b-d714b8089194.png)

The API should probably keep returning the full list, but not entirely sure of that.

**Comment by atopal** [comment]
Had a conversation: let's cap at 5 and add something like (and 10 more), add explainer.

**Comment by orvn** [comment]
Resolved in #1001, only 5 SPs are shown, with an option to toggle open the rest.
