### ISSUE TITLE
Validate auth works in Docs

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#669]
Continuation of #473

## AC
- [x] user can logout from docs site
- [x] user can login from docs site

**Comment by joannaong** [comment]
This will be fixed when https://github.com/web3-storage/web3.storage/issues/1138 is resolved

**Comment by orvn** [comment]
Merged #1138, and the navigation is now consolidated. This includes the logged in and logged out states being reflected in the nav, and the ability to perform login/logout actions.
