### ISSUE TITLE
Delete via CID rather than id

### ISSUE THREAD

**Issue by andrew** [web3-storage/web3.storage#67]
Currently you need the id of a file to be able to delete it using the `DELETE /user/uploads/:id` end point, but the id is hard to get, would be great to be able to delete via CID instead: `DELETE /user/uploads/:cid`

**Comment by vasco-santos** [comment]
`:cid` might be problematic given a user can do multiple uploads with partially the same the content. You can get the uploadId by listing your uploads, , but it is not the same as using the CID itself.

**Comment by andrew** [comment]
@vasco-santos agreed, getting the uploadId by paging through a list will be painful once you get to large numbers of uploads, this was suggested by @alanshaw in slack as a alternative to having to properly expose the uploadid elsewhere.

**Comment by olizilla** [comment]
I think we avoid creating multiple uploads where we are getting partials... the user cannot create more than 1 upload per CID. I'd much rather refer to uploads by CID, I think it's easier to explain to users too.
