### ISSUE TITLE
I'm getting blocked when deploying to ipfs

### ISSUE THREAD

**Issue by karczuRF** [web3-storage/web3.storage#673]
Deployment to IPFS causing the error "Unexpected token < in JSON at position 0". That is because I'm blocked as described in this tutorial https://community.cloudflare.com/t/sorry-you-have-been-blocked/110790. The error has occurred in a few cases, so below is my ip and list of connections' Ray ID.
IP: 83.14.237.138
Cloudflare Ray ID: 6b2269f49a36f29c, 6b226a05da3b1661, 6b226a1d3f955031, 6b226a411dce5013, 6b226a7eb9290008, 6b226aed685a5030

**Comment by vasco-santos** [comment]
Hello @karczuRF 

How are you deploying to web3.storage? We have rate limit enabled for recurrent requests from a single IP. If you only do a single request it should not be a problem.

**Comment by vasco-santos** [comment]
This is from the github action. Should not be a problem now, can you please try again?

**Comment by karczuRF** [comment]
Hey @vasco-santos! Thanks for reply. As you wrote I'm using github action. I've re-run the action a sec ago but nothing has changed. Any idea?

**Comment by vasco-santos** [comment]
Please give it a few more minutes and try again. Changes should be propagating through the Cloudflare workers

**Comment by karczuRF** [comment]
Looks like it works fine now. Thanks @vasco-santos for your help!
