### ISSUE TITLE
As part of Docs move, implement rewrite rules

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#675]
Yusef called out that we will need rewrite rules for docs once we move routes. 
We likely need to do this server side. 

This is required for #473

**Comment by JeffLowe** [comment]
@yusefnapora 
Is the intent for this to be a redirect, or a transparent redirect?
Also, can you point us to whomever can give us (Jesse & Adam) access to Cloudflare?

**Comment by JeffLowe** [comment]
nudge @yusefnapora see questions above.

**Comment by yusefnapora** [comment]
Hey @JeffLowe, sorry about the delay.

I think ideally we'd have server-side 301s that forward from `docs.web3.storage/$path` to `web3.storage/docs/$path`, which seems [doable with CloudFlare pages](https://support.cloudflare.com/hc/en-us/articles/200172286-Configuring-URL-forwarding-or-redirects-with-Cloudflare-Page-Rules).

However, there's a complication there, in that I never actually got around to switching the deployment from Fleek to CF pages; CF pages is enabled, but just for preview builds ATM.  So we would need to do that first, then add the rewrite rules.

I think @olizilla and @alanshaw would be most likely to have the cloudflare credentials needed. I actually don't have access to our Fleek account, but we can ping `@Spoke` on PL slack to get help there on disabling the fleek deploy.

Alternatively, we could publish a build full of client-side redirects and publish that to the `docs` subdomain with Fleek.

**Comment by JeffLowe** [comment]
not needed, since this is handled in soon to release website update
