### ISSUE TITLE
Add filtering support for GET /pins endpoint

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#685]
### User story
As a dev, I want to be able to list all my pin objects and be able to filter them.

### Acceptance criteria
* Can filter by name - with the different types of matching defined by the spec
* Can filter by status
* Can filter by timestamp (before and after)
* Can filter by specific metadata
* Is authorised via user’s API key

### Tasks
- [ ] ...

**Comment by flea89** [comment]
This will be completed as part of #684
