### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#704]
Came through to support email. Probably related to #341

---

I'm trying to upload my nft-collection on Web3.Storage. I need 12 Gb for it (10k images). When i use the upload-command "node put-files.js ..." i get an error message:
Uploading 10000 files
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\Users\khanp\OneDrive\Desktop\hashlips_art_engine-main\build\images\8370.png'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\khanp\\OneDrive\\Desktop\\hashlips_art_engine-main\\build\\images\\8370.png'
}

**Comment by fahimaltinordu** [comment]
I have the same problem, did you fix @dchoi27 ?

**Comment by yusefnapora** [comment]
Googling the error message led me to [this issue](https://github.com/webpack-contrib/copy-webpack-plugin/issues/59), which suggests that node on Windows has a limit of 2048 simultaneously open files.

That thread suggests using [graceful-fs](https://www.npmjs.com/package/graceful-fs), which will backoff and retry if it gets an EMFILE error. @vasco-santos maybe we could pull graceful-fs into the `files-from-path` lib? Or else implement the retry logic there ourselves.

**Comment by vasco-santos** [comment]
@yusefnapora thanks for that research.

@fahimaltinordu what node version are you using? From Yusef's linked issue, it looks like older versions of Node have this problem.

`graceful-fs` seems widely used and an option to consider, but as their README suggests we might need to wait on their updates if something changes in Node core. But I would rather try to understand if this is likely a problem with older Node versions before exploring the usage of graceful-fs

**Comment by olizilla** [comment]
There is a [fix](https://github.com/web3-storage/files-from-path/pull/18) for the issue that landed in `files-for-path@v0.2.5` that is re-exported by the `web3.storage`. 

Running `npm install web3.storage@latest` in same folder that your package.json file is for your copy of `put-files.js` should fix the issue.

Run `npm ls files-from-path` and check it gives you a version number at 0.2.5 or above to verify you have the fixed version.
