### ISSUE TITLE
API package testing - Spin out docker containers for db and IPFS cluster

### ISSUE THREAD

**Issue by flea89** [web3-storage/web3.storage#717]

**Comment by vasco-santos** [comment]
DB part is done in https://github.com/web3-storage/web3.storage/pull/765

Will do the cluster once we get https://github.com/web3-storage/web3.storage/pull/650 merged in

**Comment by vasco-santos** [comment]
So, I spent some time trying to get the cluster to work, but I am getting CORS headers problem.

I think we need to setup in go-ipfs https://discuss.ipfs.io/t/how-to-enable-cors-in-go-ipfs-dockerfile/8543 , which is not possible via ENV vars. We need to setup a custom docker image with a configuration file to make it possible.
