### ISSUE TITLE
Customise the dag params when making CARs

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#72]
Logging this as it's a discussion that we didn't resolve yet... we have the option of using non-default options for creating the DAG when the client creates the CAR on put. e.g Using a larger fixed chunk size e.g 2MB would reduce the total number of CIDs we'd have to announce.

The list of options we can tweak in the js-unix-fs importer are defined here https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs-importer#api

We'd need update ipfs-car.pack to accept overrides here https://github.com/web3-storage/ipfs-car/blob/9bf13783b25d92c093ebcc076cb7c47810c58f12/src/pack/index.ts#L20-L26

**Comment by vasco-santos** [comment]
I added support for this in `ipfs-car` https://github.com/web3-storage/ipfs-car/pull/61

**Comment by olizilla** [comment]
Max safe chunk size is 1MiB https://github.com/ipfs-rust/ipfs-embed/issues/72#issuecomment-823422728

**Comment by alanshaw** [comment]
I think I duplicated this in https://github.com/web3-storage/web3.storage/issues/173. Read that issue for information on what we did.
