### ISSUE TITLE
Increased account limits not shown in Web UI

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#723]
When users request an increased storage limit, we don't reflect this on their account page. We should!

Potentially this would involve exposing an API endpoint that would return the account limit for a given account, then using this in the web UI.

**Comment by vasco-santos** [comment]
We should also track enabling limit increase via the admin dashboard

**Comment by dchoi27** [comment]
Closing this given this is in the redesign, cc @orvn

**Comment by orvn** [comment]
Ack, thanks!
