### ISSUE TITLE
Some files in a large uploaded directory are retrievable, and some aren't

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#745]
A user uploaded a large directory, where some files are retrievable through the ipfs.io gateway and some aren't.

The directory CID is `bafybeiaba2haznuzwvwd7ztunksv2lbr5sk7biv3zgpzazprgzb3nabp6i`.

If there's an issue with uploading large directories, we should flow the fix over to NFT.Storage as well.

**Comment by mikeal** [comment]
From George:

```
root@web3-storage-am6-2:~# ipfs-cluster-ctl --host /dnsaddr/web3.storage.ipfscluster.io --basic-auth autopin: status bafybeiaba2haznuzwvwd7ztunksv2lbr5sk7biv3zgpzazprgzb3nabp6i
bafybeiaba2haznuzwvwd7ztunksv2lbr5sk7biv3zgpzazprgzb3nabp6i:
    > web3-storage-am6     : PIN_ERROR: context canceled | 2021-12-02T22:28:11.218725032Z
    > 12D3KooWFe387JFDpgNEVCP5ARut7gRkX7YuJCXMStpkq714ziK6 : REMOTE | 2021-12-02T23:07:11.275748524Z
    > web3-storage-dc13-2  : PIN_ERROR: context canceled | 2021-12-02T22:38:37.257924378Z
    > 12D3KooWJeRQfPbiv5U2RqQ9yK3qijbNxKarKEGLMkGrfXJuZ2Bo : REMOTE | 2021-12-02T23:07:11.275748524Z
    > web3-storage-am6-2   : PIN_ERROR: context canceled | 2021-12-02T22:09:47.873838921Z
    > 12D3KooWMbibcXHwkSjgV7VZ8TMfDKi6pZvmi97P83ZwHm9LEsvV : REMOTE | 2021-12-02T23:07:11.275748524Z
```

So the pin status is failed.

Sounds like one of the CAR files from the carbites sharding is missing. Can we look in Postgres to see the entries we have for this root. 

Hopefully this is an issue in the service and we can pull the CAR file out of S3, if the client failed to send one of the CAR files then they’ll need to resend.

**Comment by dchoi27** [comment]
Update here - looks like the CAR file didn't finish uploading. However, this surfaces a broader UX error that the upload shows successful even when the file didn't finish uploading. Tracking this in #754.
