### ISSUE TITLE
Is there any way to upload folder/directory?

### ISSUE THREAD

**Issue by rcieszew** [web3-storage/web3.storage#779]
It is important when you try serve html. If you place index.html and other files in one directory (multiple files in one directory) then you can use relative path with filenames in html (otherwise you have to use long CIDs and full links with IPFS gateways).
Is there any way to create directory explicitly and build directory structure?

**Comment by brambox** [comment]
You can use the nodejs or go api's to upload folders and they will keep all in one cid. There is an example for folder upload using nodejs at 
web3.storage/packages/client/examples/node.js/put-files-from-fs.js

**Comment by dchoi27** [comment]
^ yes exactly! Alternatively, if you want to just use the command line, it's simple to convert a directory into a CAR file using ipfs-car: https://github.com/web3-storage/ipfs-car
