### ISSUE TITLE
No session permanence on firefox

### ISSUE THREAD

**Issue by nath1as** [web3-storage/web3.storage#780]
Using linux firefox nightly:
97.0a1 (2021-12-09) (64-bit)

Whenever I change routes on website I need to re-login.

**Comment by dchoi27** [comment]
Thanks! Do you have the same issue with FIrefox not Nightly? And if you have Chrome, mind checking that too?

**Comment by nath1as** [comment]
> Thanks! Do you have the same issue with FIrefox not Nightly? And if you have Chrome, mind checking that too?

Chrome works, but Firefox always has issues.

Tested also on Firefox 95.0.2 (64-bit)

**Comment by orvn** [comment]
I believe this might be related to Firefox tracking protection. @nath1as, do you still experience the issue today? If so, does toggling tracking protection (by clicking the shield to the left of the URL bar) fix it?

**Comment by nath1as** [comment]
There seems to be a completely new frontend, the issue is gone (didn't have to disable tracking).
Very nice and smooth.

**Comment by orvn** [comment]
There is a new frontend, glad you like it! Thanks so much for re-testing so quickly. 

Note for posterity: this was resolved by the release of the new site, #1001.
