### ISSUE TITLE
web3.storage fails to upload a file after ~3.5gb, Then shows the file in "my files" every time it fails, with a different CID.

### ISSUE THREAD

**Issue by redaphid** [web3-storage/web3.storage#789]
...Then the file can't be downloaded past the ~3.5gb that was uploaded. Uploads and downloads were tried many times.

Let me know if there's anything I can do to help.

Screenshot of the failure here: 
![crab-upload-fail](https://bafybeih4wirau7i6bdwb4piugsqssuy4ujwzyzyc66nqtmvg5w5fq44vt4.ipfs.dweb.link/crab-fail-to-download.png)

And the different CIDs here:
![too-many-crabs](https://bafybeiauxz4kknowqqb36almpxwowt72x3w4zvrpgvk6qnqnw3w4lgip4e.ipfs.dweb.link/too-,amy-crabs.png)

*I* understand why the CIDs are different, but someone getting started with IPFS will probably be confused.

Here's a screenshot of Firefox failing to download the link. This was attempted many times

![crab-failure-to-download](https://bafybeifuvuf45u5lupigjevvpgu36lxh3kj5visnfgc5l7m2cnxqdhgqvm.ipfs.dweb.link/crab-download-fail.png)

Finally, here's a log from my browser that seems to indicate there are some problems:
XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 5052ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 5201ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 3963ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 4153ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 5323ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 4985ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2395ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 3990ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 3830ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2227ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 3111ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 3539ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2311ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2175ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2213ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2192ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2249ms]

XHRPOSThttps://api.web3.storage/car
[HTTP/2 401 Unauthorized 2566ms]

Error uploading:  Error: Could not parse provided API token
    NextJS 31
react_devtools_backend.js:2540:25
```

**Comment by vasco-santos** [comment]
Hello @redaphid 

Thanks for reaching out. Can you please give us more information, specifically:
- What was the method you used to upload the CAR file?
- What are the CIDs you are having problems with?
- The crab upload file was the same in both uploads but resulted in different CIDs?

**Comment by alanshaw** [comment]
Closing this as it's stale. We've made a bunch of improvements to the UI since.
