### ISSUE TITLE
put and purCar Request time-out

### ISSUE THREAD

**Issue by gregorym** [web3-storage/web3.storage#803]
Hello,

I have a node script that uploaded a folder of images then a folder of json files consecutively. 
The script works perfectly fine from my local machine, however when run from DigitalOcean it behaves differently.

When the node scripts runs from DigitalOcean, the first sections runs fine, it's able to upload +2000 images, however the section ALWAYS fails with a 529 Request Time-out. I can't figure you why. Both folders have the same amount of files.

I have exactly the same behavior when I replace the `putCar` and `put` with a list of files.

Any recommendations? I wondered if you throttled the IP from DigitalOcean maybe?

```js
const storage = new Web3Storage({ token: process.env.WEB3_STORAGE_KEY });
const _path = zipPath + ".unzipped/assets/";
const output = `${_path}../${id}-assets.car`;
const cmd = `./node_modules/.bin/ipfs-car --wrapWithDirectory false --pack ${_path} --output ${output}`;
execSync(cmd);
const car = await CarReader.fromIterable(fs.createReadStream(output));
// @ts-ignore
const cid1 = await storage.putCar(car);

...

const _path = zipPath + ".unzipped/metadata-updated/";
const output = `${_path}../${id}-metadata.car`;
const cmd = `./node_modules/.bin/ipfs-car --wrapWithDirectory false --pack ${_path} --output ${output}`;
execSync(cmd);
const car = await CarReader.fromIterable(fs.createReadStream(output));
const cid1 = await storage.putCar(car);
```

**Comment by gregorym** [comment]
It was in `storage.putCar` since this is where the API call is made.

**Comment by dchoi27** [comment]
Closing this for now!
