### ISSUE TITLE
Metrics - usage of the pinning api service

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#807]
We need to prepare the backend for adding new metrics regarding the new pinning APIs' usage.

* Dashboards used: Grafana
* Metrics exposed through APIs
* First analyse what metrics we now have for uploads
* Mimic that for PIN requests

**Comment by mbommerez** [comment]
https://api.nft.storage/metrics
https://api.web3.storage/metrics

**Comment by LeslieOA** [comment]
We'll start with adding the following (to mirror NFT and support expose the pinning services metrics):

* Uploads by type:
  * `web3storage_uploads_total`
    * `web3storage_uploads_total{type="Car"}`
    * `web3storage_uploads_total{type="Blob"}`
    * `web3storage_uploads_total{type="Multipart"}`
    * `web3storage_uploads_total{type="Upload"}`
* Pins:
	* `web3storage_pins_total{status="PinQueued"}`
	* `web3storage_pins_total{status="Pinning"}`
	* `web3storage_pins_total{status="Pinned"}`
	* `web3storage_pins_total{status="PinError"}`

@vasco-santos @alanshaw Would we need the pinning service (name) similar to NFT.Storage (e.g.`IpfsCluster*` or `Pinata`)?


See: 
  * https://api.web3.storage/metrics
    * Source: [web3.storage/packages/api/src/metrics.js](https://github.com/web3-storage/web3.storage/blob/main/packages/api/src/metrics.js)

**Comment by LeslieOA** [comment]
A fast follow for this ticket could be [caching the results](https://github.com/web3-storage/web3.storage/issues/967), but isn't imperative for the first iteration.

**Comment by dchoi27** [comment]
Hm - I think the pin statuses are the same ones between the two (only difference is how they're labeled)? But might be misunderstanding the question. @alanshaw would know better what statuses we want to track in Cluster.
