### ISSUE TITLE
throw new Error('Unexpected end of data');

### ISSUE THREAD

**Issue by AllanOricil** [web3-storage/web3.storage#840]
Im getting this type of error quite often. What could be the cause for that?

![image](https://user-images.githubusercontent.com/55927613/148123816-e0b57d44-35e7-48cc-b90d-ded2a8584a67.png)

These are the files Im downloading. To secure my file, I divided it into multiple parts, then encrypted the parts with aes, each using its own iv. To retrieve it, I have to download all parts, decrypt them, and finally join them together. But for some reason I keep getting this error while downloading. Sometimes everything works without a problem.

![image](https://user-images.githubusercontent.com/55927613/148123924-32b337cd-998c-4e60-80c5-e8f834baac2c.png)

**Comment by AllanOricil** [comment]
To show it is random, here is another try output

![image](https://user-images.githubusercontent.com/55927613/148124225-7740f49c-c561-4d55-aa07-1d3bed633039.png)

**Comment by AllanOricil** [comment]
And without changing anything in the code, it now worked:

![image](https://user-images.githubusercontent.com/55927613/148125282-3fd2c25c-4193-4ea7-9759-c7fa7ef0e9bd.png)

**Comment by AllanOricil** [comment]
It was probably an instability on your servers/providers. But I would like a revision on that part of the code.  Im using the lib as this:

````js
const { Web3Storage } = require('web3.storage');

const web3StorageClient = new Web3Storage({
  token: process.env.WEB3STORAGE_TOKEN,
});

web3StorageClient
      .get(cid)
      .then((response) => {
        //Im doing stuff here
      })
      .catch((error) =>
         
      );
  });
````
Even with a catch, my server stops when I have this type of exception.

**Comment by alanshaw** [comment]
It depends what you're doing in `//Im doing stuff here` - it could be throwing asynchronously...

Want to share the code?

**Comment by vasco-santos** [comment]
@AllanOricil can you provide us more information on the module failing here?

**Comment by AllanOricil** [comment]
@vasco-santos it is the @ipld/car/cjs/lib/decoder.js
One of the points I postei here has the line where the exception happens
