### ISSUE TITLE
Ready to go templates with the most used frameworks

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#889]
Need to identify which ones. Great idea @vasco-santos 

Also can have them being tested in CI as part of our release process

**Comment by LeslieOA** [comment]
#### Popular framework suggestions*:  

- **Next.js (React)**
  - Example: [Strapi Starter Next Blog](https://github.com/strapi/strapi-starter-next-blog)
  - Use case: IPFS hosted blog (with IPNS, DNSLink or ENS)
- **Expo (React Native)**
  - Example: [Expo AWS Amplify with Storage Example](https://github.com/expo/examples/tree/master/with-aws-storage-upload)
  - Use case: A simple mobile and desktop image gallery (@yusefnapora's [example-image-gallery](https://github.com/web3-storage/example-image-gallery/blob/main/src/js/storage.js))



#### Questions

* Would there be any interest in a Web3.Storage Terraform/Pulumi module?
* Would many of the [js-ipfs-examples](https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples) would be good to port over at a later date?

&nbsp;

*<small><em>heavily biased by my exposure and preferences</em></small>

**Comment by awcchungster** [comment]
I second-- could we get a React Native example of how to integrate this? 

My use case involves uploading 150mb videos, so the resiliency and multi-part uploading that S3 has done is super critical for us to prevent inefficient retries.

**Comment by mbommerez** [comment]
This ticket is no longer current. With the new w3ui you will be able to see examples and use generic components that will showcase how to integrate web3.storage services.
https://github.com/web3-storage/w3ui
Closing ticket.
