### ISSUE TITLE
Switch to using nitro dotStorage s3 bucket

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#904]
Just needs updated credentials and copy over existing bucket contents.

**Comment by vasco-santos** [comment]
Duplicated of https://github.com/web3-storage/web3.storage/issues/640

**Comment by alanshaw** [comment]
1. Switch credentials and re-deploy
2. Copy existing data to new bucket
3. Update URLs in database

**Comment by vasco-santos** [comment]
When we do this change, we need to loop in @ribasushi

**Comment by alanshaw** [comment]
No PR it was just a secrets change.

**Comment by francois-potato** [comment]
Hey @alanshaw,

> Copy existing data to new bucket

I think we could run [S3 sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) to synchronise the `raw` folder between buckets. Can another team be able to run that as we don't have access to the production buckets?

> Update URLs in database

We will prepare a migration script for the database (backup.url should point to the new bucket). Could you please remind me the new bucket name and region?

**Comment by mbommerez** [comment]
All files were copied. Closing ticket.
