### ISSUE TITLE
tmpfs is not cleared after adding files

### ISSUE THREAD

**Issue by ljmf00** [web3-storage/web3.storage#920]
By using the code available in the web3.storage website, after adding files to the IPFS network, the `tmpfs` `/tmp` is not cleaned up properly, cluttering it over time. This seem to be an issue also with `nft.storage` but I can't understand the root of the problem.

**Comment by alanshaw** [comment]
Can you share the code you're using? Temporary files should be being cleaned up.

**Comment by ljmf00** [comment]
> By using the code available in the web3.storage website, after adding files to the IPFS network, the `tmpfs` `/tmp` is not cleaned up properly, cluttering it over time. This seem to be an issue also with `nft.storage` but I can't understand the root of the problem.

I tried to reduce the problem and made a reproducable snippet. Seem to be an issue only with `nft.storage`. Moved to https://github.com/nftstorage/nft.storage/issues/1186

**Comment by vasco-santos** [comment]
@ljmf00 I could replicate this in nft land and fixed it. But not in web3.storage side of things. The only place where we pack files we close the blockstore in the end. Could you let me know a code snipped where I could replica this?

**Comment by ljmf00** [comment]
As I mentioned above, I can't replicate it too. I got a bit confused and reduced the testing surface to prove it, so no problem with web3.storage. 😌
