### ISSUE TITLE
Dealing with metrics as the db grows

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#93]
Re: the thread in the metrics PR #70 

- We curretly have a pattern of "Count and aggregate over all docs in several collections" on-demaned to generate prometheus pull-style metrics.
- FaunaDB has page size limits of 100,000, so once any counts near that, we'll have to include pagination walking to get the full numbers.
- Prometheus integrations usually assume that you can keep some state in your app, so you'd be programatically incrementing in-memory counters to keep track of long running aggregations.
- We don't have the luxury of shared state in Cloudflare Workers. As an alternative approach actively incrementing a metrics collection "in-band" as part of any FaunaDB mutation is undesirable. Fauna warns against as the first point in their best practices 
> Counter data is not well-suited for database storage. In Fauna, each document update stores a new version of the document. For frequently-updated fields, a lot of document history can be collected very quickly.
– https://docs.fauna.com/fauna/current/api/best_practices?lang=javascript
- Similarly the eventually consistent nature of the Cloudflare KV store doesn't lend itself to read/update/write style on-the-fly metric counting.
- We have a 30s processing timout on a worker invokation, so if Fauna takes longer than that to calculate the answers then we can't return it.
- There are processing limits per query in Fauna too (that we hit with trying to ingest 100k+ batch entries in a single update)

**Proposals**

_aggregate on the diff since the last run_

Write the output of our metrics queries to a metrics colleciton in the DB along with the timestamp, and upgrade our queries to only process documents / edits that occured since the last run. Some care should be taken to ensure we can get metrics across all the collections at a particular timestamp... but I think Fauna is good at that with it's serializability guarantees and document history tracking.

With that, we could theoretically drop the metrics info and rebuild, while keeping the overheads down as we go.

_use the Cloudflare Cache to store the metrics repsonse_

We can just let CF return the same response for ~10mins or whaterver we set our prometheus scrape interval to.

**Comment by dchoi27** [comment]
Think this has some overlap with @ribasushi's and @hugomrdias's work getting Fauna data into Postgres, which would let us query the data without having to run aggregates in Fauna. Does that solve this issue or are there concerns beyond that?
