### ISSUE TITLE
Form for requesting pinning service API allowlist access

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#931]
Sister issue to https://github.com/nftstorage/nft.storage/issues/1025

We should check if they are on the allowlist, and if not, we probably just need to ask them for their project description, why they need to use the pinning services API, and example CIDs of content they're looking to pin. An email form like we currently do for account limit increases would work fine.

FYI @orvn for after launch of redesign

**Comment by orvn** [comment]
Ack! Are we still on board with eventually integrating Airtable and using that as the form data destination? @dchoi27

**Comment by dchoi27** [comment]
Oh yeah totally forgot we talked about doing that. I'll ask the Trigram folks to explore using an Airtable form on the NFT.Storage side and we can just port over the integration on the Web3.Storage side.

**Comment by LeslieOA** [comment]
@dchoi27 On a related note, in the near future, would it be useful to surface to a user in the web UI they're on the allowlist (or that they're not, so they can request access)?

**Comment by dchoi27** [comment]
great point - added to the issue

**Comment by dchoi27** [comment]
@orvn for now, just an email link is good!

**Comment by JeffLowe** [comment]
This will be handled by the admin request initiative and integrated in with the admin application (which will manage all user requests).
