### ISSUE TITLE
Investigate PSA QA test suite

### ISSUE THREAD

**Issue by GaryHomewood** [web3-storage/web3.storage#936]
Look at tooling to provide a test suite for the pinning APIs. 

Possible tech:
- [Postman](https://www.postman.com/)
- [Thunder Client VSCode extension](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)
- [Hurl](https://hurl.dev/index.html)

Requirements:
- Test suite should cover all use cases of the pinning specification.
- Test suite could provide speed test metrics.
- Test suite can be easily used for smoke testing.

**Comment by vasco-santos** [comment]
@lidel pointed me to https://github.com/ipfs/pinning-services-api-spec/issues/64 and with it we will be able to test the API spec in CI
