### ISSUE TITLE
Block uploads, new PSA pins and API tokens when `ACCOUNT_ENABLED` is `false` 

### ISSUE THREAD

**Issue by LeslieOA** [web3-storage/web3.storage#988]
In the new `user_tag` table, when `ACCOUNT_ENABLED` is set to `false` (by an admin via [admin.storage](https://github.com/nftstorage/admin.storage)) we'll need to update auth logic to prevent/block:

* Web UI uploads
* HTTP API
	* Upload a CAR (`/car`)
	*  Upload and store files (`/upload`)
* Pinning Service API
	* Add pin object
	* Replace pin 
	* Delete a pin
* API tokens

It would be good to surface to a user that their account has been blocked with a simple message before UX/design is thought through.

In the web3 UI:
- [ ] A blocked user is still able to login to web application
- [ ] Upon login to web UI, a blocked user gets a message explaining their account was blocked, and to reach out to support (if they haven't already reached out)
- [ ] A blocked user is unable to create any new API keys (users get a message explaining the issue)
- [ ] A blocked user is unable to upload any files
- [ ] A blocked user still able to see their uploaded files in `/files`, complete copy functions, and even delete functions

> Note: "soft" blocking a user should only prevent CUD (Create, Update and Delete), not prevent them from accessing their account(s) and listing/viewing their files.
> There may be a need to ban in a user in the near future ([tracked here](https://github.com/nftstorage/admin.storage/issues/19)).

#### When would `ACCOUNT_ENABLED` = `false` be set?
* When an admin explicitly disables an account in admin.storage

See also:

* [Extended features for Admin.storage (PSA, Storage limits, User block) #9](https://github.com/nftstorage/admin.storage/issues/9)
* [Addressing PR feedback for user_tag table to allow tag value type (see #955) #979](https://github.com/web3-storage/web3.storage/pull/979)

Mirror issue in nft.storage https://github.com/nftstorage/nft.storage/issues/1383

**Comment by JeffLowe** [comment]
See https://github.com/web3-storage/web3.storage/pull/984 implementing ACCOUNT_ENABLED user_tag_type that supports blocking/unblocking user.

**Comment by trigramdev9** [comment]
please see https://github.com/web3-storage/web3.storage/issues/1002#issuecomment-1043141895 in regards to renaming `ACCOUNT_ENABLED` to `ACCOUNT_RESTRICTED`.

**Comment by trigramdev9** [comment]
@adamalton if you always check the value of the tag you don't have to worry about whether or not it is present, and thereby the name doesn't really matter.

if ACCOUNT_ENABLED is not set to "false", then they are allowed.
if PSA_ENABLED is set to "true" then they are allowed.

**Comment by mbommerez** [comment]
Closing this.

Replaced by
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1054
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1055
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1056
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1066
https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1067
