### ISSUE TITLE
Distinguish 'uploads' used storage vs 'pins' used storage in User Account

### ISSUE THREAD

**Issue by LeslieOA** [web3-storage/web3.storage#989]
Since the introduction of pinning services into Web3.Storage, we now have two sources of used storage for users.
* Uploaded files ('uploads')
* Pinned files ('pins')

Both of the above count towards a user's storage quota, so we need to accurately display to a user how much storage they are currently using for both categories.

One important specification to make is that only a small subset of users currently have access to pinning services. So we would need to make this distinction dynamic, so 99% of users will not get a 0 MB used for pins and wonder what that is for (and why their access to it is not working)

At the least, this would require [updating the `user_used_storage` function](https://github.com/web3-storage/web3.storage/blob/486a0cdcb82d73f2f07b76ffdc4f8d08b41a9d6a/packages/db/postgres/functions.sql#L254). 

<img width="350" alt="Screenshot 2022-02-16 at 12 23 09" src="https://user-images.githubusercontent.com/145453/154264389-fec5a065-aad9-4653-acd5-327d41908a14.png">

**Comment by JeffLowe** [comment]
Seems like a good idea to differentiate source and display both.  
Posting the new interface below for reference on this.  
Suggestion:  Maybe instead of displaying source of storage in the graph, we jsut show total with tooltip or explainer text saying this total includes all sources (listing sources).  May not be important to build and show the exact amounts of the data, but is important to convey that this total is comprised of all sources.  But, maybe showing in graph is best way (defer to design/design thinking on this)
<img width="697" alt="Screen Shot 2022-02-16 at 8 11 03 AM" src="https://user-images.githubusercontent.com/2078567/154282026-f299e052-2a7c-426f-ad97-9304552c1874.png">

**Comment by orvn** [comment]
@dchoi27 had a slight modification to the storage quota bar design, in preparation for the nature of tiers changing in the future @JeffLowe. Here's what it looks like when a user has used up some of their quota:

![account-usage-bar](https://user-images.githubusercontent.com/3689720/154389898-1b3ec34b-34d5-416b-b6d3-4bce50c9e35d.png)

With that in mind, I think @LeslieOA's solution still works well, but adapted to the new design: we'd just use a less visible hue/shade/gradient to differentiate between data from CIDs stored vs PSA pins. 

> Maybe instead of displaying source of storage in the graph, we jsut show total with tooltip or explainer text saying this total includes all sources (listing sources)

Agree. To let the user know what the difference is between the two shades in the bar, we can use a tooltip or a legend.

**Comment by alexandrastoica** [comment]
Hi @orvn! Nice to see the new design taking shape. I was wondering if it's possible to share a mockup with how you'd display the different types of storage in the progress bar. My concern is that the gradient will confuse the users as it's hard to differentiate between categories (i.e. what's a gradient vs what's a color change) and has potential to compromise accessibility (i.e. color contrast). Ideally we wouldn't rely only on color, so tooltips/annotations is a good shout. 

Let me know if you want to bounce ideas or have any designs to share. Thanks!

**Comment by orvn** [comment]
👋 @alexandrastoica! 

So right now, when the user is authorized to store more than `1 TiB` and does, there isn't a clear distinction of their previously-reached milestone. But other than that, the fill level seems pretty clear, no? The gradient isn't abrupt at any point, so it shouldn't look like it has any lines within it that could be confused for separate segments (unless I'm misunderstanding something)?

![storage-bar](https://user-images.githubusercontent.com/3689720/159207638-236db077-ecff-4d19-b507-ed03348332b3.gif)

**Comment by alexandrastoica** [comment]
@orvn 👋 

Sorry for the confusion. What I meant was making a difference between uploads storage and pin requests storage coming from the [Pinning Service API](https://docs.web3.storage/how-tos/pinning-services-api).

What I'm thinking is something like this:

<img width="485" alt="Screenshot 2022-03-16 at 12 43 20" src="https://user-images.githubusercontent.com/9439090/159516725-51814e9b-f2a7-4d20-8ad8-a755f58951b8.png">

In our case we'd have storage coming from the uploads in one color and storage from PSA in another, and tooltips to support that distinction. If we use gradients, this will get tricky to visualise. Do you see something like this working with the new design?

**Comment by orvn** [comment]
> @orvn 👋
> 
> Sorry for the confusion. What I meant was making a difference between uploads storage and pin requests storage coming from the [Pinning Service API](https://docs.web3.storage/how-tos/pinning-services-api).
> 
> What I'm thinking is something like this:
> 
> In our case we'd have storage coming from the uploads in one color and storage from PSA in another, and tooltips to support that distinction. If we use gradients, this will get tricky to visualise. Do you see something like this working with the new design?

Oh, that makes sense! 

cc @emilymariahh and @d3as8a for design solution

**Comment by D3AS8A** [comment]
Hey everyone, thanks for breaking this down. We're going to try a few variations (including a possible double graph, or two distinct patterns with a legend). We can also try the tool tip/color solution but that sorta drops us down to color alone to distinguish on mobile (which isn't ideal). @em

**Comment by emilymariahh** [comment]
Here's a couple options I came up with - the first utilizes a tooltip to differentiate pinning vs uploaded storage, the second has a leg
![Option One](https://user-images.githubusercontent.com/70724758/163244083-fddb7b09-a48c-41de-a0a5-89f5ee7df68b.png)
![Option Two](https://user-images.githubusercontent.com/70724758/163244087-32914657-b4af-4ebf-8ed2-40dab7e5fee9.png)
end.

**Comment by JeffLowe** [comment]
This appears complete in the UI.  Closing this out as complete.  If and when we need to refine or extend this, we'll do so in new ticket.

**Comment by dchoi27** [comment]
@orvn are pins appearing in storage used now?

**Comment by orvn** [comment]
They _were_, but it looks like another issue might have caused them to not appear again. Tracked in #1473.
