### ISSUE TITLE
Storage limit - Framework to get users and record emails sent

### ISSUE THREAD

**Issue by LeslieOA** [web3-storage/web3.storage#990]
Overarching user needs:
* Users need to receive warning emails from about nearing (milestones) their storage quota or exceeding it. User gets an email notification from support@web3.storage when they’ve hit the following thresholds: 75%, 80%, 85%, 90%, with instructions on how to request more.
* Admins (support@web3.storage) need to receive an email when a user has gone over their allowed storage quota.

[Notion - Enforcing-user-storage-capacity-limits](https://www.notion.so/pl-strflt/Enforcing-user-storage-capacity-limits-a29aa59f28484842bea2721f5982234a)

We can compare a users default (1TiB) or increased (`user_tag` table, `tag` of `STORAGE_LIMIT_BYTES`)  storage quota to what their current used storage. 

## Tasks

1. DB function to retrieve all users with storage used with a percentage from/to range of their allocated storage quota
User details returned:

- Email
- First and last name
- Storage quota
- Storage used

2. DB function to save details of sent email

- User ID
- Email type
- Email message ID
- Sent at

2. Node function in the `cron` package to call the DB functions to get the users that need emailing and save details of email sent.

**NOTE** 
Sending the email with MailChimp in a follow-up ticket:
[Add MailChimp email service](https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/1153)

---

#### Threshold milestones and email frequency (TBC):

* Weekly email: equal to or greater than 75% of storage quota used (but below 85%)
* Weekly email: equal to or greater than 85% of storage quota used (but below 95%)
* Daily email: equal to or greater than 90% of storage quota used

> Note: This quota includes both uploads via the web UI and pins via the PSA (Pinning Service API). 

A cron job every `{daily}` (at a minimum). 

MailChimp's API is the preferred method of email automation. 

#### Questions

Do we need a `storage_usage_exceeded` table (as a snapshot of users who are over their quota) or will querying on cron and upload/pin suffice?

CC @dchoi27 for email frequency.

**Comment by dchoi27** [comment]
SGTM - I'd say crank it up to daily at 90% (and replace the last 2 bullets)

**Comment by adamalton** [comment]
I'm re-opening this, because #1273 is marked as fixing this, so as that is not yet closed, it makes sense for this to still be open. (Although it's slightly confusing, as both #1156 and #1273 are both marked as fixing this!)
