### ISSUE TITLE
Log storage increase requests and approvals

### ISSUE THREAD

**Issue by LeslieOA** [web3-storage/web3.storage#991]
## User story
We currently have no tracking of storage increase requests from users. We also do not have any other way to track requests from users. The advantage of storing such requests is that we will have justification and further detail around requests (how much storage do they want). This lets us know whether a request is the first or the last in a long series of requests, who the user is, whether we denied them before etc. This is in turn will then inform:
* which emails we send them
* which decision we take on a new request
* whether we automatically or manually block them.

Furthermore there could be different types of requests in the future and if we keep this logging generic enough we will be able to cover those as well and make interaction and approvals between w3 and users fluid.

This table would not be the source of truth for the allowed storage amount for a user. This is handled by user_tags.

This ticket only describes the back-end part of this solution. No front-end implementation for the time being. Possible solutions:
* form in admin.storage to log requests sent by email
* form in web3.storage to let the user log a storage increase request
* actions to take in admin.storage to reply to/approve requests. If approved, this would automatically update the user_tag to a new entry with the new allowed storage amount.

## Potential solution:
One solution could be to create a table (e.g. named `storage_requests` or `user_requests`) containing all storage quota increase requests made from users with a justification and how much storage the user thinks they need (e.g. number in TB or bytes).

Fields could be:
- `user_id`
- `requested_at`
- `limit_requested`
- `user_justification`
- `decision` is granted / not granted / partially granted
- `decision_taken_at`
- `limit_granted` Suggestion to be a value as they might not get what they originally requested. We need a clear field of how much was granted.
- `decision_justification`

## Acceptance criteria:
* We can store user requests, with a user, a date, a requested storage limit and a reason
* We can store a decision in the same record with a status, a date, a confirmed new limit and a reason

**Comment by JeffLowe** [comment]
This seems like a reasonable request, given what I understand of current internal needs and likely use cases.  
If we do land on logging these requests from UI, we could easily surface these requests in the admin, giving internal admins an easy way to review requests & manage them.

**Comment by JeffLowe** [comment]
Scope of the user requests is currently being addressed in the active "Admin.dag.house user request management & refinements" initiative.  Removing the "pi/account-limits" tag from this and applying the "pi/admin-requests" tag.  Plan is to implement requests system on nft.storage side starting with PSA then implementing storage increase for web3.  Will provide more information after kickoff.

**Comment by JeffLowe** [comment]
Note:  Per decisions in admin initiative, and upcoming UCAN, we will not be implementing any user request table or system (no conversion of mailtos into web forms for user requests).
